### PR TITLE
bsd: debitrot

### LINKED ISSUE #19234: NetBSD build failure - more bitrot to sort out?
### Zig Version

0.12.0-dev.3161+377ecc6af

### Steps to Reproduce and Observed Behavior

On a fresh 'git clone' the usual:

```
mkdir build 
cd build 
cmake -DCMAKE_BUILD_TYPE=Release -GNinja ..
ninja install
```

I get:
...
```
[15/20] Running zig1.wasm to produce /home/xci/src/zig/build/zig2.c
FAILED: zig2.c /home/xci/src/zig/build/zig2.c
cd /home/xci/src/zig && /home/xci/src/zig/build/zig1 /home/xci/src/zig/lib build-exe -ofmt=c -lc -OReleaseSmall --name zig2 -femit-bin="/home/xci/src/zig/build/zig2.c" -target x86_64-netbsd --dep build_options -
-dep aro --mod root src/main.zig --mod build_options /home/xci/src/zig/build/config.zig --mod aro lib/compiler/aro/aro.zig
/lib/std/os.zig:6036:25: error: ambiguous reference
/lib/std/c.zig:1514:16: note: declared here
/lib/std/c/netbsd.zig:40:5: note: declared here
/lib/std/os.zig:5936:25: error: ambiguous reference
/lib/std/c.zig:1505:16: note: declared here
/lib/std/c/netbsd.zig:25:5: note: declared here
ninja: build stopped: subcommand failed.
```

### Expected Behavior

Build to complete. My last successful build on this platform was `0.12.0-dev.3008+b2374c4d7` (on amd64) and `0.12.0-dev.3161+377ecc6af` (on aarch64).

### PR DESCRIPTION
**Pull request by mikdusan**
The usual trying to keep the BSDs capable of cmake-bootstrap and passing behavior and std test.

closes #19234

### CODE REVIEW

**Comment by andrewrk** [comment]
Thanks!
