### ISSUE TITLE
compilation error when building with io_mode evented

### ISSUE THREAD

**Issue by vrischmann** [ziglang/zig#6715]
Hi,

using Zig version `0.6.0+245d98d32` compiling the following code fails:
```
const std = @import("std");

pub const io_mode = .evented;

pub fn main() anyerror!void {
    std.log.warn("done", .{});
}
```

This is the error:
```
/home/vincent/dev/devtools/zig/lib/std/start.zig:268:24: error: @Frame() of generic function
            var frame: @Frame(callMainAsync) = undefined;
                       ^
/home/vincent/dev/devtools/zig/lib/std/start.zig:240:36: note: called from here
    return initEventLoopAndCallMain(u8, callMain);
                                   ^
/home/vincent/dev/devtools/zig/lib/std/start.zig:234:72: note: called from here
fn callMainWithArgs(argc: usize, argv: [*][*:0]u8, envp: [][*:0]u8) u8 {
                                                                       ^
```
[You can check it on godbolt](https://gcc.godbolt.org/z/jnxPnr)

I've bisected it down to c7c38e72793df53e6582b6f8b501e18314ab07e9.
