### ISSUE TITLE
Importing SDL2 no longer works

### ISSUE THREAD

**Issue by chwayne** [ziglang/zig#7551]
```zig
const sdl = @cImport({
    @cInclude("SDL2/SDL.h");
});

pub fn main() anyerror!void {
    _ = sdl;
}
```

Trying to build this with a simple build.zig produces this error:
```
./zig-cache/o/07cbe812ef4f928336aee8ccbd93531d/cimport.zig:22297:5: error: non-extern function is variadic
pub fn _saveprevssp(...) callconv(.C) void {
    ^
./zig-cache/o/07cbe812ef4f928336aee8ccbd93531d/cimport.zig:22324:5: error: non-extern function is variadic
pub fn _setssbsy(...) callconv(.C) void {
    ^
./src/main.zig:6:9: note: referenced here
    _ = sdl;
        ^
```

git bisect points to this commit: https://github.com/ziglang/zig/commit/ccdb81fb31f3fa1384b44b74ecdae345457bd0b5

**Comment by ehaas** [comment]
I'll talk about `_setssbsy` but the same exact analysis applies to `_saveprevssp`

Prior to `ccdb81f`, `_setssbsy` translated to (file path comments removed):
```zig
pub const _setssbsy = @compileError("unable to translate function");
// warning: TODO implement translation of CastKind BuiltinFnToFnPtr
```
This is due to the presence of the compiler builtin `__builtin_ia32_setssbsy` in that function.

Post-`ccdb81f` the function gets translated but there are two problems:

First is that `_setssbsy` (defined in `lib/include/cetintrin.h`) is defined as an inline function with empty args list (not `void`) so it's a varargs function, which can't currently be created in Zig AFAIK. The second issue is that it uses `__builtin_ia32_setssbsy` which is an Intel "shadow stack" instruction (PDF warning, see page 10: https://software.intel.com/sites/default/files/managed/4d/2a/control-flow-enforcement-technology-preview.pdf). I don't know enough about those to know whether they actually need to be varargs due to whatever stack/shadow stack manipulation is going on, but even if the varargs function is solved there will need to be an inline assembly definition for `__builtin_ia32_setssbsy` created in `lib/std/c/builtins.zig`. I doubt it was an oversight to not include a `void` parameter declaration for `_setssbsy` and `_saveprevssp` but I really don't know.

If `_saveprevssp` / `_setssbsy` need to be varargs to work, I don't know a good way to solve the issue without reverting or special casing them, which is a hack. I did confirm that those are the only 2 functions that cause problems when using current translate-c with `SDL.h`.

`SAVEPREVSSP` is described on page 121 and `SETSSBSY` is described on page 132 of the linked PDF. As far as I can tell neither of them take any operands.

**Comment by zigazeljko** [comment]
> I doubt it was an oversight to not include a `void` parameter declaration for `_setssbsy` and `_saveprevssp` but I really don't know.

It was an oversight. Both [Intel](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=shadow) and [GCC](https://github.com/gcc-mirror/gcc/blob/master/gcc/config/i386/cetintrin.h) include the `void` parameter.
