### ISSUE TITLE
std.builtin.SourceLocation.line - @src() is NOT a comptime value

### ISSUE THREAD

**Issue by roig** [ziglang/zig#17031]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

This code should print the line correctly and it fails to compile:

```rust
const std = @import("std");

pub fn main() void {
    const line_text = comptime std.fmt.comptimePrint("{}", .{@src().line});
    std.debug.print(line_text, .{});
}
```
```rust
example.zig:4:61: error: unable to evaluate comptime expression
example.zig:4:61: note: operation is runtime due to this operand
```
This doesn't compile in 0.10 without -fstage1 and in 0.11.
This compiles correctly in 0.9 and in 0.10 with -fstage1.

### Expected Behavior

Compile and print correctly the line number at runtime.

**Comment by ifreund** [comment]
This is working as intended: https://github.com/ziglang/zig/issues/2029#issuecomment-645793168
