### PR TITLE
Default std.posix.system.ucontext_t is void

### LINKED ISSUE #20710: std.debug.StackIterator in embedded throws compile error for ucontext_t being missing in std.posix.system
### Zig Version

0.14.0-dev.468+aa73bb6bc

### Steps to Reproduce and Observed Behavior

1. Write a kernel (or something else embedded)
2. Implement a custom panic handler which uses std.debug.StackIterator
3. Get a compile error (`std/posix.zig:153:30: error: struct 'posix.system__struct_2080' has no member named 'ucontext_t'`)

### Expected Behavior

I expected this compilation to work, as it did some days ago. 

As far as I know, this behavior regressed in e8c4e79.

### PR DESCRIPTION
**Pull request by rootbeer**
PR https://github.com/ziglang/zig/pull/20679 ("std.c reorganization") switched feature-detection code to use `T != void` checks in place of `@hasDecl`.  However, the default std.posix.system struct (used by freestanding targets) is empty, so compile-time feature detection against symbols in there (specifically `std.posix.system.ucontext_t` in this case), fail at compile time.

This PR adds a void ucontext_t into the std.posix.system default.  While I'm confident this fixes the particular problem, it may not be the right approach (it seems like this struct will eventually have to be padded out with a lot of void symbols).  I'm not sure if deeper fixes to std.debug are in order, or something else entirely.

This PR also adds pseudo-"freestanding" variation of the existing StackIterator "unwind" test.  The new test is somewhat hacky (its freestanding, but assumes it can invoke a Linux exit syscall), but it does detect this problem.

Fixes #20710

### CODE REVIEW

**Comment by andrewrk** [comment]
Nice work on the test.
