### ISSUE TITLE
Bug in zig build system, wrong include search on macos

### ISSUE THREAD

**Issue by zhaozg** [ziglang/zig#9289]
# Info

When I want to do c build with zig build system, I got errors. That in zig master and 0.8.x branchs.

run `uname -a` got
```
Darwin zhaozgMBP 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
```

run `brew info llvm` outputs
```
llvm: stable 12.0.0 (bottled), HEAD [keg-only]
Next-gen compiler infrastructure
https://llvm.org/
/usr/local/Cellar/llvm/12.0.0_1 (9,789 files, 1.5GB)
  Poured from bottle on 2021-05-16 at 23:29:01
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/llvm.rb
License: Apache-2.0 with LLVM-exception
==> Dependencies
Build: cmake ✔, swig ✘
Required: python@3.9 ✔
==> Options
--HEAD
        Install HEAD version
==> Caveats
To use the bundled libc++ please add the following LDFLAGS:
  LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"

llvm is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have llvm first in your PATH, run:
  echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.zshrc

For compilers to find llvm you may need to set:
  export LDFLAGS="-L/usr/local/opt/llvm/lib"
  export CPPFLAGS="-I/usr/local/opt/llvm/include"

==> Analytics
install: 18,104 (30 days), 68,769 (90 days), 247,318 (365 days)
install-on-request: 11,324 (30 days), 51,653 (90 days), 193,493 (365 days)
build-error: 0 (30 days)

```
Details info describle below.

Files structure

```
.
├── a
├── b
│   └── b.h
└── m.c
```

b.h content:

```b.h
//empty
```

m.c content:

```m.c
#include "b.h"

int main()
{
  printf("Hello from Zig\n");
  return 0;
}
```

#  Errors.

When run `zig cc -Ia -Ib m.c`,got:

```
m.c:1:10: fatal error: cannot open file './b.h': No such file or directory
#include "b.h"
         ^
1 error generated.
```

run `zig cc -Ia -Ib m.c -v`, got:
```
clang version 12.0.0
Target: x86_64-unknown-macosx-gnu
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
 (in-process)
 "/usr/local/bin/zig" -cc1 -triple x86_64-unknown-macosx11.4.0-gnu -Wundef-prefix=TARGET_OS_ -Werror=undef-prefix -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj --mrelax-relocations -disable-free -disable-llvm-verifier -discard-value-names -main-file-name m.c -mrelocation-model pic -pic-level 2 -mframe-pointer=none -fno-rounding-math -target-sdk-version=11.3 -fcompatibility-qualified-id-block-type-checking -fvisibility-inlines-hidden-static-local-var -target-cpu penryn -tune-cpu generic -debugger-tuning=lldb -target-linker-version 609.8 -v -nostdsysteminc -nobuiltininc -resource-dir /usr/local/lib/clang/12.0.0 -dependency-file /Users/zhaozg/.cache/zig/tmp/25bcd59bdd73b85b-m.o.d -MT /Users/zhaozg/.cache/zig/tmp/25bcd59bdd73b85b-m.o -sys-header-deps -MV -isystem /usr/local/lib/zig/include -isystem /usr/local/lib/zig/libc/include/x86_64-macos-gnu -isystem /usr/local/lib/zig/libc/include/generic-darwin -isystem /usr/local/lib/zig/libc/include/x86_64-macos-any -isystem /usr/local/lib/zig/libc/include/any-macos-any -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iwithsysroot /usr/local/include -iframeworkwithsysroot /Library/Frameworks -iframeworkwithsysroot /System/Library/Frameworks -D _DEBUG -I a -I b -Og -fdebug-compilation-dir /Users/zhaozg/tmp/zig -ferror-limit 19 -fsanitize=alignment,array-bounds,bool,builtin,enum,float-cast-overflow,function,integer-divide-by-zero,nonnull-attribute,null,object-size,pointer-overflow,return,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,unreachable,vla-bound -fsanitize-trap=alignment,array-bounds,bool,builtin,enum,float-cast-overflow,function,integer-divide-by-zero,nonnull-attribute,null,object-size,pointer-overflow,return,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,unreachable,vla-bound -stack-protector 2 -stack-protector-buffer-size 4 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fmax-type-align=16 -fcolor-diagnostics -fno-spell-checking -target-cpu skylake -target-feature -16bit-mode -target-feature -32bit-mode -target-feature -3dnow -target-feature -3dnowa -target-feature +64bit -target-feature +adx -target-feature +aes -target-feature -amx-bf16 -target-feature -amx-int8 -target-feature -amx-tile -target-feature +avx -target-feature +avx2 -target-feature -avx512bf16 -target-feature -avx512bitalg -target-feature -avx512bw -target-feature -avx512cd -target-feature -avx512dq -target-feature -avx512er -target-feature -avx512f -target-feature -avx512ifma -target-feature -avx512pf -target-feature -avx512vbmi -target-feature -avx512vbmi2 -target-feature -avx512vl -target-feature -avx512vnni -target-feature -avx512vp2intersect -target-feature -avx512vpopcntdq -target-feature -avxvnni -target-feature +bmi -target-feature +bmi2 -target-feature -branchfusion -target-feature -cldemote -target-feature +clflushopt -target-feature -clwb -target-feature -clzero -target-feature +cmov -target-feature +cx16 -target-feature +cx8 -target-feature -enqcmd -target-feature +ermsb -target-feature +f16c -target-feature -false-deps-lzcnt-tzcnt -target-feature +false-deps-popcnt -target-feature -fast-11bytenop -target-feature +fast-15bytenop -target-feature -fast-7bytenop -target-feature -fast-bextr -target-feature +fast-gather -target-feature -fast-hops -target-feature -fast-lzcnt -target-feature +fast-scalar-fsqrt -target-feature -fast-scalar-shift-masks -target-feature +fast-shld-rotate -target-feature +fast-variable-shuffle -target-feature +fast-vector-fsqrt -target-feature -fast-vector-shift-masks -target-feature +fma -target-feature -fma4 -target-feature +fsgsbase -target-feature -fsrm -target-feature +fxsr -target-feature -gfni -target-feature -hreset -target-feature -idivl-to-divb -target-feature +idivq-to-divl -target-feature +invpcid -target-feature -kl -target-feature -lea-sp -target-feature -lea-uses-ag -target-feature -lvi-cfi -target-feature -lvi-load-hardening -target-feature -lwp -target-feature +lzcnt -target-feature +macrofusion -target-feature +mmx -target-feature +movbe -target-feature -movdir64b -target-feature -movdiri -target-feature -mwaitx -target-feature +nopl -target-feature -pad-short-functions -target-feature +pclmul -target-feature -pconfig -target-feature -pku -target-feature +popcnt -target-feature -prefer-128-bit -target-feature -prefer-256-bit -target-feature -prefer-mask-registers -target-feature -prefetchwt1 -target-feature +prfchw -target-feature -ptwrite -target-feature -rdpid -target-feature +rdrnd -target-feature +rdseed -target-feature -retpoline -target-feature -retpoline-external-thunk -target-feature -retpoline-indirect-branches -target-feature -retpoline-indirect-calls -target-feature +rtm -target-feature +sahf -target-feature -serialize -target-feature -seses -target-feature +sgx -target-feature -sha -target-feature -shstk -target-feature +slow-3ops-lea -target-feature -slow-incdec -target-feature -slow-lea -target-feature -slow-pmaddwd -target-feature -slow-pmulld -target-feature -slow-shld -target-feature -slow-two-mem-ops -target-feature -slow-unaligned-mem-16 -target-feature -slow-unaligned-mem-32 -target-feature -soft-float -target-feature +sse -target-feature +sse2 -target-feature +sse3 -target-feature +sse4.1 -target-feature +sse4.2 -target-feature -sse4a -target-feature -sse-unaligned-mem -target-feature +ssse3 -target-feature -tbm -target-feature -tsxldtrk -target-feature -uintr -target-feature -use-aa -target-feature -use-glm-div-sqrt-costs -target-feature -vaes -target-feature -vpclmulqdq -target-feature +vzeroupper -target-feature -waitpkg -target-feature -wbnoinvd -target-feature -widekl -target-feature +x87 -target-feature -xop -target-feature +xsave -target-feature +xsavec -target-feature +xsaveopt -target-feature +xsaves -o /Users/zhaozg/.cache/zig/tmp/25bcd59bdd73b85b-m.o -x c m.c
clang -cc1 version 12.0.0 based upon LLVM 12.0.0 default target x86_64-apple-darwin20.5.0
ignoring nonexistent directory "/usr/local/lib/zig/libc/include/generic-darwin"
ignoring nonexistent directory "/usr/local/lib/zig/libc/include/x86_64-macos-any"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 a
 b
 /usr/local/lib/zig/include
 /usr/local/lib/zig/libc/include/x86_64-macos-gnu
 /usr/local/lib/zig/libc/include/any-macos-any
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
End of search list.
m.c:1:10: fatal error: cannot open file './b.h': No such file or directory
#include "b.h"
         ^
1 error generated.
```

run `zig cc -Ia -Ib m.c -v -target x86_64-linux-gnu`, got
```
clang version 12.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
 (in-process)
 "/usr/local/bin/zig" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj --mrelax-relocations -disable-free -disable-llvm-verifier -discard-value-names -main-file-name m.c -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=none -fmath-errno -fno-rounding-math -mconstructor-aliases -target-cpu x86-64 -tune-cpu generic -fno-split-dwarf-inlining -debugger-tuning=gdb -target-linker-version 609.8 -v -nostdsysteminc -nobuiltininc -resource-dir /usr/local/lib/clang/12.0.0 -dependency-file /Users/zhaozg/.cache/zig/tmp/59f84a5856239926-m.o.d -MT /Users/zhaozg/.cache/zig/tmp/59f84a5856239926-m.o -sys-header-deps -MV -isystem /usr/local/lib/zig/include -isystem /usr/local/lib/zig/libc/include/x86_64-linux-gnu -isystem /usr/local/lib/zig/libc/include/generic-glibc -isystem /usr/local/lib/zig/libc/include/x86_64-linux-any -isystem /usr/local/lib/zig/libc/include/any-linux-any -D _DEBUG -I a -I b -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -Og -fdebug-compilation-dir /Users/zhaozg/tmp/zig -ferror-limit 19 -fsanitize=alignment,array-bounds,bool,builtin,enum,float-cast-overflow,function,integer-divide-by-zero,nonnull-attribute,null,object-size,pointer-overflow,return,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,unreachable,vla-bound -fsanitize-trap=alignment,array-bounds,bool,builtin,enum,float-cast-overflow,function,integer-divide-by-zero,nonnull-attribute,null,object-size,pointer-overflow,return,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,unreachable,vla-bound -stack-protector 2 -stack-protector-buffer-size 4 -fgnuc-version=4.2.1 -fcolor-diagnostics -fno-spell-checking -target-cpu x86-64 -target-feature -16bit-mode -target-feature -32bit-mode -target-feature -3dnow -target-feature -3dnowa -target-feature +64bit -target-feature -adx -target-feature -aes -target-feature -amx-bf16 -target-feature -amx-int8 -target-feature -amx-tile -target-feature -avx -target-feature -avx2 -target-feature -avx512bf16 -target-feature -avx512bitalg -target-feature -avx512bw -target-feature -avx512cd -target-feature -avx512dq -target-feature -avx512er -target-feature -avx512f -target-feature -avx512ifma -target-feature -avx512pf -target-feature -avx512vbmi -target-feature -avx512vbmi2 -target-feature -avx512vl -target-feature -avx512vnni -target-feature -avx512vp2intersect -target-feature -avx512vpopcntdq -target-feature -avxvnni -target-feature -bmi -target-feature -bmi2 -target-feature -branchfusion -target-feature -cldemote -target-feature -clflushopt -target-feature -clwb -target-feature -clzero -target-feature +cmov -target-feature -cx16 -target-feature +cx8 -target-feature -enqcmd -target-feature -ermsb -target-feature -f16c -target-feature -false-deps-lzcnt-tzcnt -target-feature -false-deps-popcnt -target-feature -fast-11bytenop -target-feature -fast-15bytenop -target-feature -fast-7bytenop -target-feature -fast-bextr -target-feature -fast-gather -target-feature -fast-hops -target-feature -fast-lzcnt -target-feature -fast-scalar-fsqrt -target-feature -fast-scalar-shift-masks -target-feature -fast-shld-rotate -target-feature -fast-variable-shuffle -target-feature -fast-vector-fsqrt -target-feature -fast-vector-shift-masks -target-feature -fma -target-feature -fma4 -target-feature -fsgsbase -target-feature -fsrm -target-feature +fxsr -target-feature -gfni -target-feature -hreset -target-feature -idivl-to-divb -target-feature +idivq-to-divl -target-feature -invpcid -target-feature -kl -target-feature -lea-sp -target-feature -lea-uses-ag -target-feature -lvi-cfi -target-feature -lvi-load-hardening -target-feature -lwp -target-feature -lzcnt -target-feature +macrofusion -target-feature +mmx -target-feature -movbe -target-feature -movdir64b -target-feature -movdiri -target-feature -mwaitx -target-feature +nopl -target-feature -pad-short-functions -target-feature -pclmul -target-feature -pconfig -target-feature -pku -target-feature -popcnt -target-feature -prefer-128-bit -target-feature -prefer-256-bit -target-feature -prefer-mask-registers -target-feature -prefetchwt1 -target-feature -prfchw -target-feature -ptwrite -target-feature -rdpid -target-feature -rdrnd -target-feature -rdseed -target-feature -retpoline -target-feature -retpoline-external-thunk -target-feature -retpoline-indirect-branches -target-feature -retpoline-indirect-calls -target-feature -rtm -target-feature -sahf -target-feature -serialize -target-feature -seses -target-feature -sgx -target-feature -sha -target-feature -shstk -target-feature +slow-3ops-lea -target-feature +slow-incdec -target-feature -slow-lea -target-feature -slow-pmaddwd -target-feature -slow-pmulld -target-feature -slow-shld -target-feature -slow-two-mem-ops -target-feature -slow-unaligned-mem-16 -target-feature -slow-unaligned-mem-32 -target-feature -soft-float -target-feature +sse -target-feature +sse2 -target-feature -sse3 -target-feature -sse4.1 -target-feature -sse4.2 -target-feature -sse4a -target-feature -sse-unaligned-mem -target-feature -ssse3 -target-feature -tbm -target-feature -tsxldtrk -target-feature -uintr -target-feature -use-aa -target-feature -use-glm-div-sqrt-costs -target-feature -vaes -target-feature -vpclmulqdq -target-feature +vzeroupper -target-feature -waitpkg -target-feature -wbnoinvd -target-feature -widekl -target-feature +x87 -target-feature -xop -target-feature -xsave -target-feature -xsavec -target-feature -xsaveopt -target-feature -xsaves -faddrsig -o /Users/zhaozg/.cache/zig/tmp/59f84a5856239926-m.o -x c m.c
clang -cc1 version 12.0.0 based upon LLVM 12.0.0 default target x86_64-apple-darwin20.5.0
#include "..." search starts here:
#include <...> search starts here:
 a
 b
 /usr/local/lib/zig/include
 /usr/local/lib/zig/libc/include/x86_64-linux-gnu
 /usr/local/lib/zig/libc/include/generic-glibc
 /usr/local/lib/zig/libc/include/x86_64-linux-any
 /usr/local/lib/zig/libc/include/any-linux-any
End of search list.
m.c:1:10: fatal error: cannot open file './b.h': No such file or directory
#include "b.h"
         ^
1 error generated.
In file included from <built-in>:347:
/usr/local/lib/zig/libc/glibc/include/libc-symbols.h:886:10: fatal error: cannot open file '/usr/local/lib/zig/libc/glibc/include/symbol-hacks.h': No such file or directory
#include <symbol-hacks.h>
         ^
1 error generated.

```
# Zig info

zig build with
```
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$(brew --prefix llvm) -DCMAKE_INSTALL_PREFIX=/usr/local
make install
```

# Possible causes

Not lookup headers files foreach include dirs.

**Comment by wilsonk** [comment]
Just a quick note that the above example works on Linux Lite 5.4 (Ubuntu based linux with kernel 5.8) with zig-0.8.0. It also properly cross compiles with:
```
zig cc -Ia -Ib m.c -v -target aarch64-macos
```

So it certainly seems to be MacOS specific...although I didn't test/confirm on Mac!

**Comment by zhaozg** [comment]
Thanks @wilsonk, and welcome anyone to help me to narrow possibility.

**Comment by wilsonk** [comment]
Hmm, this might be a 'brew llvm' issue or an x86_64 issue as this example builds fine on my arm64 Big Sur system with a source build of llvm.  Could also be fixed with a newer zig maybe? I am running
```
0.9.0-dev.5814+63d3c5d45
```
Here are my other specs:

```
Darwin user1s-Mac-mini.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 arm64
```

LLVM-12.0.0 with clang/lld built from source and installed to /usr/local/.  Here is the ouput of 'zig cc -Ia -Ib m.c -v':

```
zig cc -Ia -Ib m.c -v
clang version 12.0.0
Target: aarch64-unknown-macosx-gnu
Thread model: posix
InstalledDir: /usr/local/bin
 (in-process)
 "/Users/wilsonk/zig/build/zig" -cc1 -triple arm64-unknown-macosx11.4.0-gnu -Wundef-prefix=TARGET_OS_ -Werror=undef-prefix -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj --mrelax-relocations -disable-free -disable-llvm-verifier -discard-value-names -main-file-name m.c -mrelocation-model pic -pic-level 2 -mframe-pointer=none -fno-rounding-math -target-sdk-version=11.3 -fcompatibility-qualified-id-block-type-checking -fvisibility-inlines-hidden-static-local-var -target-cpu apple-a12 -target-feature +v8.3a -target-feature +fp-armv8 -target-feature +neon -target-feature +crc -target-feature +crypto -target-feature +fullfp16 -target-feature +ras -target-feature +lse -target-feature +rdm -target-feature +rcpc -target-feature +zcm -target-feature +zcz -target-feature +sha2 -target-feature +aes -target-abi darwinpcs -fallow-half-arguments-and-returns -debugger-tuning=lldb -target-linker-version 650.9 -v -nostdsysteminc -nobuiltininc -resource-dir /Users/wilsonk/zig/lib/clang/12.0.0 -dependency-file /Users/wilsonk/.cache/zig/tmp/2cb9e1331b5cc3-m.o.d -MT /Users/wilsonk/.cache/zig/tmp/2cb9e1331b5cc3-m.o -sys-header-deps -MV -isystem /Users/wilsonk/zig/lib/include -isystem /Users/wilsonk/zig/lib/libc/include/aarch64-macos-gnu -isystem /Users/wilsonk/zig/lib/libc/include/generic-darwin -isystem /Users/wilsonk/zig/lib/libc/include/aarch64-macos-any -isystem /Users/wilsonk/zig/lib/libc/include/any-macos-any -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iwithsysroot /usr/local/include -iframeworkwithsysroot /Library/Frameworks -iframeworkwithsysroot /System/Library/Frameworks -D _DEBUG -I a -I b -Og -fdebug-compilation-dir /Users/wilsonk/zig/build/tmp -ferror-limit 19 -fsanitize=alignment,array-bounds,bool,builtin,enum,float-cast-overflow,function,integer-divide-by-zero,nonnull-attribute,null,object-size,pointer-overflow,return,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,unreachable,vla-bound -fsanitize-trap=alignment,array-bounds,bool,builtin,enum,float-cast-overflow,function,integer-divide-by-zero,nonnull-attribute,null,object-size,pointer-overflow,return,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,unreachable,vla-bound -stack-protector 2 -stack-protector-buffer-size 4 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fmax-type-align=16 -fcolor-diagnostics -fno-spell-checking -target-cpu apple-a14 -target-feature -a65 -target-feature -a76 -target-feature +aes -target-feature +aggressive-fma -target-feature +alternate-sextload-cvt-f32-pattern -target-feature +altnzcv -target-feature +am -target-feature -amvs -target-feature -apple-a12 -target-feature -apple-a13 -target-feature -apple-a7 -target-feature +arith-bcc-fusion -target-feature +arith-cbz-fusion -target-feature -balance-fp-ops -target-feature -bf16 -target-feature -brbe -target-feature -bti -target-feature -call-saved-x10 -target-feature -call-saved-x11 -target-feature -call-saved-x12 -target-feature -call-saved-x13 -target-feature -call-saved-x14 -target-feature -call-saved-x15 -target-feature -call-saved-x18 -target-feature -call-saved-x8 -target-feature -call-saved-x9 -target-feature +ccdp -target-feature +ccidx -target-feature +ccpp -target-feature -cmp-bcc-fusion -target-feature +complxnum -target-feature +CONTEXTIDREL2 -target-feature -cortex-a78c -target-feature -cortex-r82 -target-feature +crc -target-feature +crypto -target-feature -custom-cheap-as-move -target-feature +disable-latency-sched-heuristic -target-feature +dit -target-feature +dotprod -target-feature -ecv -target-feature -ete -target-feature -exynos-cheap-as-move -target-feature -exynosm4 -target-feature -f32mm -target-feature -f64mm -target-feature -fgt -target-feature +flagm -target-feature -force-32bit-jump-tables -target-feature +fp16fml -target-feature +fp-armv8 -target-feature +fptoint -target-feature +fullfp16 -target-feature +fuse-address -target-feature +fuse-aes -target-feature +fuse-arith-logic -target-feature +fuse-crypto-eor -target-feature +fuse-csel -target-feature +fuse-literals -target-feature -harden-sls-blr -target-feature -harden-sls-retbr -target-feature -hcx -target-feature -i8mm -target-feature +jsconv -target-feature +lor -target-feature -ls64 -target-feature +lse -target-feature -lsl-fast -target-feature +mpam -target-feature -mte -target-feature +neon -target-feature -neoversee1 -target-feature -neoversen1 -target-feature -neoversen2 -target-feature -neoversev1 -target-feature -no-neg-immediates -target-feature +nv -target-feature -outline-atomics -target-feature +pan -target-feature +pan-rwv -target-feature +pauth -target-feature +perfmon -target-feature +pmu -target-feature -predictable-select-expensive -target-feature +predres -target-feature -rand -target-feature +ras -target-feature +rcpc -target-feature +rcpc-immo -target-feature +rdm -target-feature -reserve-x1 -target-feature -reserve-x10 -target-feature -reserve-x11 -target-feature -reserve-x12 -target-feature -reserve-x13 -target-feature -reserve-x14 -target-feature -reserve-x15 -target-feature -reserve-x18 -target-feature -reserve-x2 -target-feature -reserve-x20 -target-feature -reserve-x21 -target-feature -reserve-x22 -target-feature -reserve-x23 -target-feature -reserve-x24 -target-feature -reserve-x25 -target-feature -reserve-x26 -target-feature -reserve-x27 -target-feature -reserve-x28 -target-feature -reserve-x3 -target-feature -reserve-x30 -target-feature -reserve-x4 -target-feature -reserve-x5 -target-feature -reserve-x6 -target-feature -reserve-x7 -target-feature -reserve-x9 -target-feature +sb -target-feature +sel2 -target-feature +sha2 -target-feature +sha3 -target-feature -slow-misaligned-128store -target-feature -slow-paired-128 -target-feature -slow-strqro-store -target-feature -sm4 -target-feature -spe -target-feature -spe-eef -target-feature +specrestrict -target-feature +ssbs -target-feature -strict-align -target-feature -sve -target-feature -sve2 -target-feature -sve2-aes -target-feature -sve2-bitperm -target-feature -sve2-sha3 -target-feature -sve2-sm4 -target-feature -tagged-globals -target-feature +tlb-rmi -target-feature -tme -target-feature -tpidr-el1 -target-feature -tpidr-el2 -target-feature -tpidr-el3 -target-feature +tracev8.4 -target-feature -trbe -target-feature +uaops -target-feature -use-aa -target-feature -use-experimental-zeroing-pseudos -target-feature -use-postra-scheduler -target-feature -use-reciprocal-square-root -target-feature +v8.1a -target-feature +v8.2a -target-feature +v8.3a -target-feature +v8.4a -target-feature -v8.5a -target-feature -v8.6a -target-feature -v8.7a -target-feature -v8r -target-feature +vh -target-feature -wfxt -target-feature -xs -target-feature +zcm -target-feature +zcz -target-feature +zcz-fp -target-feature -zcz-fp-workaround -target-feature +zcz-gp -o /Users/wilsonk/.cache/zig/tmp/2cb9e1331b5cc3-m.o -x c m.c
clang -cc1 version 12.0.0 based upon LLVM 12.0.0 default target arm64-apple-darwin20.5.0
ignoring nonexistent directory "/Users/wilsonk/zig/lib/libc/include/generic-darwin"
ignoring nonexistent directory "/Users/wilsonk/zig/lib/libc/include/aarch64-macos-any"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 a
 b
 /Users/wilsonk/zig/lib/include
 /Users/wilsonk/zig/lib/libc/include/aarch64-macos-gnu
 /Users/wilsonk/zig/lib/libc/include/any-macos-any
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
End of search list.
m.c:5:3: warning: implicitly declaring library function 'printf' with type 'int (const char *, ...)' [-Wimplicit-function-declaration]
  printf("Hello from Zig\n");
  ^
m.c:5:3: note: include the header <stdio.h> or explicitly provide a declaration for 'printf'
1 warning generated.
zig ld -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk /Users/wilsonk/.cache/zig/o/49f222a3887c659b7b55576758f41231/m.o /Users/wilsonk/.cache/zig/o/0590854c89331994b975831bc0b3d616/libcompiler_rt.a -o /Users/wilsonk/.cache/zig/o/cb3b16297bd5f42e18a25604386f0062/a.out -L/usr/lib -L/usr/local/lib
```

**Comment by zhaozg** [comment]
Maybe this is a bug in llvm.

**Comment by zhaozg** [comment]
Make sure that a bug in brew llvm.

I download (LLVM 12.0.0)(https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.0/clang+llvm-12.0.0-x86_64-apple-darwin.tar.xz), and build zig againest with that, that make test pass.
