### ISSUE TITLE
macOS 10.15: dyld: lazy symbol binding failed: Symbol not found: ___ulock_wait2

### ISSUE THREAD

**Issue by rsms** [ziglang/zig#14405]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

Repro:

```sh
wget https://ziglang.org/download/0.10.1/zig-macos-x86_64-0.10.1.tar.xz
tar -xf zig-macos-x86_64-0.10.1.tar.xz
cd zig-macos-x86_64-0.10.1
mkdir hello-world
cd hello-world
../zig init-exe
../zig build
```

Result:

```
dyld: lazy symbol binding faileddyld: lazy symbol binding faileddyld: lazy symbol binding failed: Symbol not found: ___ulock_wai: Symbol not found: ___ulock_wait2
  Referenced from: /Users/rsmt2
  Referenced from: /Users/rsm: Symbol not found: ___ulock_wais/Downloads/zig-macos-x86_64-0.1dyld: lazy symbol binding failed0.1/hello-world/zig-macos-x86_64s/Downloads/zig-macos-x86_64-0.1t2
  Referenced from: /Users/rsm: Symbol not found: ___ulock_wai0.1/hello-world/zig-macos-x86_64s/Downloads/zig-macos-x86_64-0.1t2
  Referenced from: /Users/rsm0.1/hello-world/zig-macos-x86_64-0.10.1/hello-world/../zig (whic-0.10.1/hello-world/../zig (whic-0.10.1/hello-world/../zig (whics/Downloads/zig-macos-x86_64-0.1dyld: lazy symbol binding failedh was built for Mac OS X 11.7)
 h was built for Mac OS X 11.7)
 : Symbol not found: ___ulock_wai Expected in: /usr/lib/libSystem0.1/hello-world/zig-macos-x86_64 Expected in: /usr/lib/libSystemh was built for Mac OS X 11.7)
 -0.10.1/hello-world/../zig (whic.B.dylib

.B.dylib

h was built for Mac OS X 11.7)
 dyld: Symbol not found: ___ulock Expected in: /usr/lib/libSystemt2
  Referenced from: /Users/rsm Expected in: /usr/lib/libSystem.B.dylib

_wait2
  Referenced from: /Userss/Downloads/zig-macos-x86_64-0.1.B.dylib

/rsms/Downloads/zig-macos-x86_640.1/hello-world/zig-macos-x86_64dyld: Symbol not found: ___ulock-0.10.1/hello-world/zig-macos-x8-0.10.1/hello-world/../zig (whicdyld: Symbol not found: ___ulockdyld: Symbol not found: ___ulock6_64-0.10.1/hello-world/../zig (h was built for Mac OS X 11.7)
 _wait2
  Referenced from: /Users_wait2
  Referenced from: /Users Expected in: /usr/lib/libSystem_wait2
  Referenced from: /Users/rsms/Downloads/zig-macos-x86_64/rsms/Downloads/zig-macos-x86_64which was built for Mac OS X 11./rsms/Downloads/zig-macos-x86_64-0.10.1/hello-world/zig-macos-x8-0.10.1/hello-world/zig-macos-x8-0.10.1/hello-world/zig-macos-x8.B.dylib

6_64-0.10.1/hello-world/../zig (6_64-0.10.1/hello-world/../zig (7)
  Expected in: /usr/lib/libSywhich was built for Mac OS X 11.which was built for Mac OS X 11.stem.B.dylib

dyld: Symbol not found: ___ulockdyld: lazy symbol binding faileddyld: dyld: lazy symbol binding failed6_64-0.10.1/hello-world/../zig (: Symbol not found: ___ulock_waidyld: lazy symbol binding failed_wait2
  Referenced from: /Users7)
  Expected in: /usr/lib/libSydyld: lazy symbol binding failedlazy symbol binding failed7)
  Expected in: /usr/lib/libSy[1]    18782 abort      ../zig build
```

Host environment:

```
$ uname -vm
Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64 x86_64
$ zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)
```

### Expected Behavior

Built to succeed

**Comment by rsms** [comment]
Seems like zig thinks my libSystem is from the future (macOS 11; my system is macOS 10.15)

**Comment by rsms** [comment]
Trying with older versions:

0.10.0 (fails)

```
$ ../zig build
info: Created build.zig
info: Created src/main.zig
info: Next, try `zig build --help` or `zig build run`
dyld: lazy symbol binding failed: Symbol not found: ___ulock_wait2
  Referenced from: /Users/rsms/Downloads/zig-macos-x86_64-0.10.0/hello-world/../zig (which was built for Mac OS X 11.7)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___ulock_wait2
  Referenced from: /Users/rsms/Downloads/zig-macos-x86_64-0.10.0/hello-world/../zig (which was built for Mac OS X 11.7)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: lazy symbol binding failed: Symbol not found: ___ulock_wait2
  Referenced from: /Users/rsms/Downloads/zig-macos-x86_64-0.10.0/hello-world/../zig (which was built for Mac OS X 11.7)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: lazy symbol binding failed[1]    18909 abort      ../zig build
```

0.9.1 (succeeds)

```
$ ../zig build
info: Created build.zig
info: Created src/main.zig
info: Next, try `zig build --help` or `zig build run`
```

So seems like something happened between 0.9.1 → 0.10.0 (I'm guessing that's when the zig-native linker appeared?)

**Comment by rsms** [comment]
Adding some additional info about my system. It seems that the SDK provided for macOS 10.15.7 is the same as for macOS 11.1:

```
$ xcrun -sdk macosx --show-sdk-path
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk
$ sha256sum $(xcrun -sdk macosx --show-sdk-path)/usr/lib/libSystem.tbd
0c5c2b892b2a78f80fec6becdb643138387b80bcde8e3266470d1e25c9d68eb7  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/lib/libSystem.tbd
```

I can build a simple "hello world" program against it:

```
$ cat << END > hello.c
#include <stdio.h>
int main(int argc, char* argv[]) {
  printf("hello from %s\n", argv[0]);
  return 0;
}
END
$ clang --version
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ clang --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk hello.c -o hello
$ ./hello
hello from ./hello
```

**Comment by kubkon** [comment]
This is by design [0.10.0 release notes - macOS](https://ziglang.org/download/0.10.0/release-notes.html#macOS). You are still be able to target earlier versions of macOS but you will need to provide the sysroot yourself. Also, the zig-native linker as you call it appeared with Zig 0.8.0 as the default macOS linker.

What I think we should do in such an instance is to error out on missing sysroot rather than try building against a newer version when the user has no explicitly provided macOS version in the target triple. I have created an issue to track this https://github.com/ziglang/zig/issues/14407.

In the meantime, you should be able to build a working binary by specifying the sysroot like so:

```
zig build --sysroot $(xcrun --show-sdk-path)
```

**Comment by kubkon** [comment]
Now that I think about this, you are building native and targeting native, correct? So normally Zig should find the SDK automatically but perhaps because this is on unsupported version of macOS, it doesn't do that anymore. If you could provide some printouts from re-running the `build-exe` with `--verbose-link` that might be useful.

**Comment by kubkon** [comment]
Oh, I think I remember now. Zig will look for the SDK automatically when the user needs to build against the libc headers, otherwise it resorts to `libSystem.tbd` stubs we ship with Zig. I think we might have to augment it to error out on unsupported version of macOS and/or consider always preferring macOS SDK if available and building native targeting native.

**Comment by rsms** [comment]
Ah, thank you for clearing that up! I agree that detecting this and showing an error message like "macOS 10.15 is not natively supported. Please provide --sysroot=" is a good idea. Would have made me not think it was a bug.

----

> If you could provide some printouts from re-running the build-exe with --verbose-link that might be useful.

```
$ ../zig version
0.10.1
$ ../zig build-exe --verbose-link src/main.zig
dyld: lazy symbol binding failed: Symbol not found: ___ulock_wait2
  Referenced from: /Users/rsms/Downloads/zig-macos-x86_64-0.10.1/hello-world/../zig (which was built for Mac OS X 11.7)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: lazy symbol binding failed: Symbol not found: ___ulock_wait2
  Referenced from: /Users/rsms/Downloads/zig-macos-x86_64-0.10.1/hello-world/../zig (which was built for Mac OS X 11.7)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___ulock_wait2
  Referenced from: /Users/rsms/Downloads/zig-macos-x86_64dyld: Symbol not found: ___ulock-0.10.1/hello-world/../zig (whic_wait2
  Referenced from: /Usersh was built for Mac OS X 11.7)
 /rsms/Downloads/zig-macos-x86_64 Expected in: /usr/lib/libSystem-0.10.1/hello-world/../zig (whic.B.dylib

h was built for Mac OS X 11.7)
  Expected in: /usr/lib/libSystem.B.dylib

[1]    20524 abort      ../zig build-exe --verbose-link src/main.zig
```

----

> In the meantime, you should be able to build a working binary by specifying the sysroot like so: `zig build --sysroot $(xcrun --show-sdk-path)`

This did not work:

```
$ xcrun --show-sdk-path
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
$ ../zig build --sysroot $(xcrun --show-sdk-path)
dyld: lazy symbol binding faileddyld: lazy symbol binding faileddyld: lazy symbol binding failed: Symbol not found: ___ulock_wai: Symbol not found: ___ulock_waidyld: lazy symbol binding faileddyld: lazy symbol binding failedt2
  Referenced from: /Users/rsmt2
  Referenced from: /Users/rsm: Symbol not found: ___ulock_wai: Symbol not found: ___ulock_wai: Symbol not found: ___ulock_wais/Downloads/zig-macos-x86_64-0.1t2
  Referenced from: /Users/rsms/Downloads/zig-macos-x86_64-0.1t2
  Referenced from: /Users/rsmdyld: lazy symbol binding failed0.1/hello-world/../zig (which wat2
  Referenced from: /Users/rsm0.1/hello-world/../zig (which was/Downloads/zig-macos-x86_64-0.1: Symbol not found: ___ulock_wais built for Mac OS X 11.7)
  Expt2
  Referenced from: /Users/rsms/Downloads/zig-macos-x86_64-0.1s built for Mac OS X 11.7)
  Exps/Downloads/zig-macos-x86_64-0.10.1/hello-world/../zig (which waected in: /usr/lib/libSystem.B.ds built for Mac OS X 11.7)
  Expected in: /usr/lib/libSystem.B.ds/Downloads/zig-macos-xected in: /usr/lib/libSystem.B.d86_64-0.1ylib

dyld: lazy symbol binding failed0.1/hello-world/../zig (which waylib

0.1/hello-world/../zig (which wa0.1/hello-world/../zig (which wadyld: lazy symbol binding faileds built for Mac OS X 11.7)
  Expylib

s built for Mac OS X 11.7)
  Expdyld: lazy symbol binding failed: Symbol not found: ___ulock_waidyld: lazy symbol binding failed: Symbol not found: ___ulock_wai: Symbol not found: ___ulock_wait2
  Referenced from: /Users/rsmt2
  Referenced from: /Users/rsmected in: /usr/lib/libSystem.B.dt2
  Referenced from: /Users/rsms/Downloads/zig-macos-x86_64-0.1: Symbol not found: ___ulock_waiylib

s built for Mac OS X 11.7)
  Exps/Downloads/zig-macos-x86_64-0.10.1/hello-world/../zig (which wat2
  Referenced from: /Users/rsmected in: /usr/lib/libSystem.B.dected in: /usr/lib/libSystem.B.ds/Downloads/zig-macos-x86_64-0.1ylib

dyld: Symbol not found: ___ulocks built for Mac OS X 11.7)
  Exp0.1/hello-world/../zig (which waylib

ected in: /usr/lib/libSystem.B.d_wait2
  Referenced from: /Usersdyld: Sdyld: lazy symbol binding faileddyld: lazy symbol binding failedylib

dyld: lazy symbol binding faileddyld: Symbol not found: ___ulock: Symbol not found: ___ulock_waidyld: lazy symbol binding faileddyld: Symbol not found: ___ulockdyld: lazy symbol binding faileddyld: Symbol not found: ___ulocks/Downloads/zig-macos-x86_64-0.1: Symbol not found: ___ulock_waidyld: Symbol not found: ___ulock/rsms/Downloads/zig-macos-x86_64_wait2
  Referenced from: /Usersdyld: lazy symbol binding failed0.1/hello-world/../zig (which wa0.1/hello-world/../zig (which wa: Symbol not found: ___ulock_wai/rsms/Downloads/zig-macos-x86_64t2
  Referenced from: /Users/rsmt2
  Referenced from: /Users/rsm-0.10.1/hello-world/../zig (whic_wait2
  Referenced from: /Usersh was built for Mac OS X 11.7)
 s/Downloads/zig-macos-x86_64-0.1 Expected in: /usr/lib/libSystemymbol not found: ___ulock_wait2
  Referenced from: /Userss built for Mac OS X 11.7)
  Exp_wait2
  Referenced from: /Users0.1/hello-world/../zig (which was/Downloads/zig-macos-x86_64-0.1dyld: lazy symbol binding failed0.1/hello-world/../zig (which wadyld: lazy symbol binding faileddyld: lazy symbol binding faileddyld: lazy symbol binding failed.B.dylib

ected in: /usr/lib/libSystem.B.d-0.10.1/hello-world/../zig (whics built for Mac OS X 11.7)
  Exp: Symbol not foundected in: /usr/lib/libSystem.B.dt2
  Referenced from: /Users/rsmh was built for Mac OS X 11.7)
 /rsms/Downloads/zig-macos-x86_64: Symbol not found: ___ulock_wai: ___ulock_waiylib

: Symbol not found: ___ulock_wai/rsms/Downloads/zig-macos-x86_64s built for Mac OS X 11.7)
  Exps built for Mac OS X 11.7)
  Exp: Symbol not found: ___ulock_wai: Symbol not found: ___ulock_wai/rsms/Downloads/zig-macos-x86_64: Symbol not found: ___ulock_wai: Symbol not found: ___ulock_wais built for Mac OS X 11.7)
  Expdyld: Symbol not found: ___ulock_wait2
  Referenced from: /Users[1]    20599 abort      ../zig build --sysroot $(xcrun --show-sdk-path)
```

Explicitly asking for macos doesn't either, but yields fewer errors:

```
$ xcrun -sdk macosx --show-sdk-path
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk
$ ../zig build --sysroot $(xcrun -sdk macosx --show-sdk-path)
dyld: lazy symbol binding faileddyld: lazy symbol binding failed: Symbol not found: ___ulock_waidyld: lazy symbol binding failed: Symbol not found: ___ulock_wait2
  Referenced from: /Users/rsm: Symbol not found: ___ulock_wait2
  Referenced from: /Users/rsms/Downloads/zig-macos-x86_64-0.1t2
  Referenced from: /Users/rsms/Downloads/zig-macos-x86_64-0.10.1/hello-world/../zig (which was/Downloads/zig-macos-x86_64-0.10.1/hello-world/../zig (which was built for Mac OS X 11.7)
  Exp0.1/hello-world/../zig (which was built for Mac OS X 11.7)
  Expected in: /usr/lib/libSystem.B.dected in: /usr/lib/libSystem.B.ds built for Mac OS X 11.7)
  Expylib

ylib

ected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___ulockdyld: Symbol not found: ___ulock_wait2
  Referenced from: /Usersdyld: Symbol not found: ___ulock_wait2
  Referenced from: /Users/rsms/Downloads/zig-macos-x86_64_wait2
  Referenced from: /Users/rsms/Downloads/zig-macos-x86_64-0.10.1/hello-world/../zig (whic/rsms/Downloads/zig-macos-x86_64dyld: lazy symbol binding failed-0.10.1/hello-world/../zig (whicdyld: lazy symbol binding failed-0.10.1/hello-world/../zig (whic: Symbol not found: ___ulock_waih was built for Mac OS X 11.7)
 h was built for Mac OS X 11.7)
 dyld: lazy symbol binding failedh was built for Mac OS X 11.7)
  Expected in: /usr/lib/libSystem Expected in: /usr/lib/libSystem: Symbol not found: ___ulock_wai Expected in: /usr/lib/libSystemdyld: lazy symbol binding failed.B.dylib

.B.dylib

t2
  Referenced from: /Users/rsmdyld: lazy symbol binding failed.B.dylib

dyld: lazy symbol binding failedt2
  Referenced from: /Users/rsm: Symbol not found: ___ulock_wai: Symbol not found: ___ulock_wais/Downloads/zig-macos-x86_64-0.1dyld: lazy symbol binding failedt2
  Referenced from: /Users/rsm: Symbol not found: ___ulock_wait2
  Referenced from: /Users/rsms/Downloads/zig-macos-x86_64-0.1: Symbol not found: ___ulock_wait2
  Referenced from: /Users/rsms/Downloads/zig-macos-x86_64-0.1: Symbol not found: ___ulock_wait2
  Referenced from: /Users/rsm0.1/hello-world/../zig (which was/Downloads/zig-macos-x86_64-0.10.1/hello-world/../zig (which wa0.1/hello-world/../zig (which wat2
  Referenced from: /Users/rsms/Downloads/zig-macos-x86_64-0.1[1]    20631 abort      ../zig build --sysroot $(xcrun -sdk macosx --show-sdk-path)
```

**Comment by kubkon** [comment]
Oh, I just noticed now that it's zig that fails to bind symbols from libSystem at runtime and not your output binary. Hmm, I'll need to noodle on this to figure out if we should set the minimum platform version differently when packaging zig toolchain.

**Comment by rsms** [comment]
Just did so myself too! Ha ha. `llvm-objdump -p zig` reveals minos 11.7:

```
$ llvm-objdump -p zig
...
Load command 13
       cmd LC_BUILD_VERSION
   cmdsize 32
  platform macos
       sdk 11.7
     minos 11.7
    ntools 1
      tool ld
   version 0.0
...
```

**Comment by kubkon** [comment]
Yeah, I'll need to think carefully if there's any way to relax this plus possibly version of linked libSystem, though the latter might not be possible. Anyhow, please leave the issue open in the meantime.

**Comment by rsms** [comment]
I think it might be possible to build with a recent SDK but limit the linker via `-mmacosx-version-min=10.15`

**Comment by kubkon** [comment]
We actually have a related problem I am trying to figure out related to this flag which is problematic https://github.com/ziglang/zig/pull/14389

**Comment by rsms** [comment]
Just grabbed the latest Go release (including arm64) and it seems the have done just that, plus _increased_ compatibility (lowered requirements to macOS 10.13)

```
$ llvm-objdump -p ~/Downloads/go/bin/go
...
Load command 5
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.13
      sdk 12.3
...
```

**Comment by kubkon** [comment]
Gotcha, thanks for checking!

**Comment by KellanHiggins** [comment]
I am definitely interested in this as I am running Mac OS 10.13 High Sierra and love the oldschoolness of it.

**Comment by motjuste** [comment]
I have the same issue as well.  macOS Catalina 10.15.7.

zig 0.9.1 is the latest one that does work.

**Comment by KellanHiggins** [comment]
> Just grabbed the latest Go release (including arm64) and it seems the have done just that, plus _increased_ compatibility (lowered requirements to macOS 10.13)
> 
> ```
> $ llvm-objdump -p ~/Downloads/go/bin/go | grep -A3 LC_VERSION_MIN_MACOSX
>       cmd LC_VERSION_MIN_MACOSX
>   cmdsize 16
>   version 10.13
>       sdk 12.3
> ```

So what is happening here? I some library not being found in default macOS 10.13?

**Comment by kgrz** [comment]
aarch64-0.12.0-dev.286  `b0d9bb0bb` worked for me. I was facing issues with the brew-installed 0.10.x

**Comment by kubkon** [comment]
> aarch64-0.12.0-dev.286 `b0d9bb0bb` worked for me. I was facing issues with the brew-installed 0.10.x

I don't think this is relevant to the issue at hand. Also, first macOS release with support for `aarch64` was macOS 11 and here we discuss supporting older macOS versions.

**Comment by kgrz** [comment]
@kubkon Oh, no. My bad. I was looking at a few of the dyld symbol issues, and commented on the wrong ticket.

**Comment by kubkon** [comment]
Great news, thanks to @mikdusan's excellent work in https://github.com/ziglang/zig/pull/17152 targeting older macOS versions should work now! Marking it as closed, but please do let me know if there's more to do and will reopen.

**Comment by mikdusan** [comment]
#17152 won't fix this issue; zig's std library introduces a direct reference to that symbol

**Comment by kubkon** [comment]
> #17152 won't fix this issue; zig's std library introduces a direct reference to that symbol
> 
> * not that it matters, that symbol is not public API
> * symbol was introduced to `libsystem_kernel` sometime in 10.12
> * symbol was moved to `libSystem` sometime in 10.15

Are you sure your PR won't fix this issue? The use of the symbol is behind a version gate after all https://github.com/ziglang/zig/blob/d1e39b6914ba0f79fb25c5bba7375964d865a69a/lib/std/Thread/Futex.zig#L176

**Comment by mikdusan** [comment]
> Are you sure your PR won't fix this issue? The use of the symbol is behind a version gate after all

Ah my eyes didn't notice the difference between `ulock_wait` and `ulock_wait2` when checking symbols. This issue can be closed:

```sh
$ cat hello.zig
const std = @import("std");
const Futex = std.Thread.Futex;

pub fn main() void {
    var value = std.atomic.Atomic(u32).init(0);

    // Try waits with invalid values.
    Futex.wait(&value, 0xdeadbeef);
    Futex.timedWait(&value, 0xdeadbeef, 0) catch {};
}

$ zig build-exe hello.zig --sysroot `xcrun --show-sdk-path` -target x86_64-macos.10.13 --verbose-link
MachO Flush... zig ld -dynamic -platform_version macos 10.13.0 14.0 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk hello.o /Users/mike/project/zig/work/main/zig-cache/o/259eecb325635816dd20b09b8f87467d/libcompiler_rt.a -o hello -lSystem

# executable runs fine on macOS 10.13 host
```

small note, the `ulock_wait` symbol is not version guarded, and a 10.11 targeted executable fails to run on 10.11 as follows. this is what tripped me up originally.

```
dyld: lazy symbol binding failed: Symbol not found: ___ulock_wait
  Referenced from: /Users/mike/./hello
  Expected in: /usr/lib/system/libsystem_kernel.dylib

dyld: Symbol not found: ___ulock_wait
  Referenced from: /Users/mike/./hello
  Expected in: /usr/lib/system/libsystem_kernel.dylib

zsh: trace trap  ./hello
```

so if we want to go back any further than 10.12, some Futex work will need to be done.

**Comment by Mikastiv** [comment]
Hi, for me this is not fixed. I'm on MacOSX 10.15.17 and using zig v0.12.0-dev.629+1606717b5.

I'm getting an error similar to OP (my terminal output seems a little messed up)
```
zig build --sysroot $(xcrun --show-sdk-path)
dyld: lazy symbol binding faileddyld: lazy symbol binding faileddyld: lazy symbol binding faileddyld: lazy symbol binding failed: Symbol not found: ___ulock_wai: Symbol not found: ___ulock_wai: Symbol not found: ___ulock_wait2
  Referenced from: /Users/mledyld: lazy symbol binding failedt2
  Referenced from: /Users/mleblanc/.local/zig/zig (which was blanc/.local/zig/zig (which was t2
  Referenced from: /Users/mlebuilt for Mac OS X 11.7)
  Expec: Symbol not found: ___ulock_waibuilt for Mac OS X 11.7)
  Expec: Symbol not found: ___ulock_waited in: /usr/lib/libSystem.B.dylted in: /usr/lib/libSystem.B.dylt2
  Referenced from: /Users/mlet2
  Referenced from: /Users/mleib

ib

blanc/.local/zig/zig (which was blanc/.local/zig/zig (which was built for Mac OS X 11.7)
  Expecbuilt for Mac OS X 11.7)
  Expected in: /usr/lib/libSystem.B.dylted in: /usr/lib/libSystem.B.dylib

ib

dyld: Symbol not found: ___ulockdyld: Symbol not found: ___ulockdyld: Symbol not found: ___ulock_wait2
  Referenced from: /Users_wait2
  Referenced from: /Users_wait2
  Referenced from: /Users/mleblanc/.local/zig/zig (which /mleblanc/.local/zig/zig (which /mleblanc/.local/zig/zig (which was built for Mac OS X 11.7)
  Ewas built for Mac OS X 11.7)
  Edyld: Symbol not found: ___ulockwas built for Mac OS X 11.7)
  Expected in: /usr/lib/libSystem.Bdyld: lazy symbol binding failed_wait2
  Referenced from: /Usersxpected in: /usr/lib/libSystem.Bdyld: lazy symbol binding failedxpected in: /usr/lib/libSystem.B/mleblanc/.local/zig/zig (which .dylib

.dylib

was built for Mac OS X 11.7)
  E.dylib

: Symbol not found: ___ulock_waixpected in: /usr/lib/libSystem.Bblanc/.local/zig/zig (which was : Symbol not found: ___ulock_wai.dylib

built for Mac OS X 11.7)
  Expectt2
  Referenced from: /Users/mleted in: /usr/lib/libSystem.B.dylblanc/.local/zig/zig (which was 2
  Referenced from: /Users/mleib

[1]    9660 abort      zig build --sysroot $(xcrun --show-sdk-path)
```

I've also tried to build the compiler from source and I also get ```Symbol not found: ___ulock_wait2```

**Comment by Mikastiv** [comment]
@kubkon Hi, I'm bumping this so my last message doesn't fall into cracks 🙂. For me it is not working on older MacOS (10.15.17) I don't know if I'm alone with this issue, but I still have the same error as OP not finding ___ulock_wait2. I've tried again with the latest version of the compiler (zig-macos-x86_64-0.12.0-dev.706+62a0fbdae) and it still doesn't work.

**Comment by mikdusan** [comment]
here's the state of affairs...

1. zig master/nightly builds produce binaries for macOS 11.0 or higher (actually 11.7.1)
2. the default bootstrap target on _any_ macOS version is `x86_64-macos.11.7.1`
3. to bootstrap on older systems, manually target an older macOS version:
```sh
$ cmake ... -DZIG_HOST_TARGET_TRIPLE=x86_64-macos.10.15
```
4. this is only required for bootstrap because once we have a stage3 compiler it detects your host and factors that into the target minver

**Comment by Mikastiv** [comment]
Thank you it worked!
