### ISSUE TITLE
stage1+stage3: regression: if tagged union fields and enum ordering do not match, switch gets wrong types

### ISSUE THREAD

**Issue by slimsag** [ziglang/zig#12543]
### Zig Version

0.10.0-dev.3620+7d674d5fb

### Steps to Reproduce

This occurs even if using `-fstage1`, and even if using the stage1 or stage3 build of the compiler. I encountered this when trying to build zigimg, which worked with a slightly older version of 0.10.x.

```zig
const MyTag = enum(u32) {
    b = 1337,
    a = 1666,
};

const MyUnion = union(MyTag) {
    a: f32,
    b: []const u8,
};

pub fn main() !void {
    var x: MyUnion = .{.a = 666};
    switch (x) {
        .a => |my_f32| {
            var y: f32 = my_f32;
            _ = y;
        },
        .b => |my_string| {
            var y: []const u8 = my_string;
            _ = y;
        }
    }
}
```

### Expected Behavior

The captures in the type switch, `my_f32` for example, should be of the right type.

### Actual Behavior

```
% zig build-exe bug.zig
bug.zig:16:26: error: expected type 'f32', found '[]const u8'
            var y: f32 = my_f32;
                         ^~~~~~
```

This only occurs because the enum/union field names _match_ and are in _a different order_. If the order is changed to match eachother, things work:

```zig
const MyTag = enum(u32) {
    a = 1666,
    b = 1337,
};

const MyUnion = union(MyTag) {
    a: f32,
    b: []const u8,
};
```

**Comment by bfredl** [comment]
I also occurred upon this, and I thought about a different possible solution. Would it be feasible to _re-order_ the `Module.Union.Fields` arrayhash to have the same order as the underlying tag enum ? Then there wouldn't be a confusion between two possible field indices for a `union(ExistingEnum)`. Or does the declaration order of the union itself need to be preserved for some other usecase?

**Comment by Vexu** [comment]
The order matters for `@typeInfo` since fields and declarations are defined to be in the same order as defined. Another option would be to make it an error for union fields to not be in the same order as the backing enum type.
