### ISSUE TITLE
Switch expression crashes the compiler or returns unformatted error message  when switching on boolean

### ISSUE THREAD

**Issue by r1bilski** [ziglang/zig#16424]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

There are 2 different test cases.
For each of them start with fresh `zig init-exe` and replace `src/main.zig` with the provided code:

1. Const bool literal crashing compiler:
```
pub fn main() !void {
    const x = false;
    _ = switch (x) {
        true => 1,
        true => 2,
    };
}
```
Executing `zig build` for this code will result in the following error being printed in the console:
```
error: zig_switch_bug...
error: The following command terminated unexpectedly:
/usr/bin/zig build-exe /home/rb/source/zig_switch_bug/src/main.zig --cache-dir /home/rb/source/zig_switch_bug/zig-cache --global-cache-dir /home/rb/.cache/zig --name zig_switch_bug --enable-cache
error: the following build command failed with exit code 11:
/home/rb/source/zig_switch_bug/zig-cache/o/1e0730b26d18b51e081723901a4e96e2/build /usr/bin/zig /home/rb/source/zig_switch_bug /home/rb/source/zig_switch_bug/zig-cache /home/rb/.cache/zig
```

2. Var bool returns unformatted error message
```
pub fn main() !void {
    var x = true;

    _ = switch (x) {
        true => 1,
        true => 2,
    };
}
```

This code will result in the following error message after `zig build`:
```
LLVM Emit Object... Duplicate integer as switch case
  switch i1 %2, label %Else [
    i1 true, label %Case
    i1 true, label %Case1
  ], !dbg !4198
i1 true
LLVM ERROR: Broken module found, compilation aborted!
error: zig_switch_bug...
error: The following command terminated unexpectedly:
/usr/bin/zig build-exe /home/rb/source/zig_switch_bug/src/main.zig --cache-dir /home/rb/source/zig_switch_bug/zig-cache --global-cache-dir /home/rb/.cache/zig --name zig_switch_bug --enable-cache
error: the following build command failed with exit code 6:
/home/rb/source/zig_switch_bug/zig-cache/o/1e0730b26d18b51e081723901a4e96e2/build /usr/bin/zig /home/rb/source/zig_switch_bug /home/rb/source/zig_switch_bug/zig-cache /home/rb/.cache/zig
```

### Expected Behavior

For contrast, here's the same code, but instead of switching on bool, we're switching on an integer:
1. Case with const:
```
pub fn main() !void {
    const x = 1;

    _ = switch (x) {
        1 => 1,
        1 => 2,
    };
}
```

2. Case with var:
```
pub fn main() !void {
    var x: i32 = 1;

    _ = switch (x) {
        1 => 1,
        1 => 2,
    };
}
```

Both result in the following error, showcasing the duplicate switch value:
```
/home/rb/source/zig_switch_bug/src/main.zig:6:9: error: duplicate switch value
        1 => 2,
        ^
/home/rb/source/zig_switch_bug/src/main.zig:5:9: note: previous value here
        1 => 1,
        ^
...
```

**Comment by mlugg** [comment]
This should be fixed on master - I remember fixing this as a part of my switch changes a while ago.

**Comment by r1bilski** [comment]
My bad, then. I couldn't find related issue. I'll retest on master.

**Comment by r1bilski** [comment]
I retested on `0.11.0-dev.4002+7dd1cf26f` and it does now print out the correct error, but it's still different from the integer one.
Here's the error message:
```
src/main.zig:6:9: error: duplicate switch value
        true => 2,
        ^~~~
```
while the integer error also has:
```
src/main.zig:5:9: note: previous value here
        1 => 1,
        ^
```

**Comment by andrewrk** [comment]
Code samples work fine with `0.11.0-dev.4183+32a175740`.
