### ISSUE TITLE
`@compileError` stack traces still lacking key info

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#12969]
### Zig Version

`0.10.0-dev.4176+6d7b0690a`

### Steps to Reproduce

```
git clone https://github.com/nektro/zigmod/releases/tag/r82
zig build
```

it contains a reference to `std.builtin.TypeInfo` which is `pub const TypeInfo = @compileError("deprecated; use Type");`

### Expected Behavior

removing the declaration altogether shows me exactly where the issue lies

```
/home/meghan/zig-cache/zigmod/deps/git/github.com/nektro/iguanaTLS/c9403b8414d7f80b5e2c04c8f1f8780ca1d2827f/src/ciphersuites.zig:429:46: error: container 'std.builtin' has no member called 'TypeInfo'
    var fields: [ciphersuites.len]std.builtin.TypeInfo.UnionField = undefined;
                                             ^
/home/meghan/zig-cache/zigmod/deps/git/github.com/nektro/iguanaTLS/c9403b8414d7f80b5e2c04c8f1f8780ca1d2827f/src/main.zig:1740:52: note: called from here
        const InRecordState = ciphers.InRecordState(_ciphersuites);
                                                   ^
/home/meghan/zig-cache/zigmod/deps/git/github.com/nektro/iguanaTLS/c9403b8414d7f80b5e2c04c8f1f8780ca1d2827f/src/main.zig:1740:52: note: called from here
        const InRecordState = ciphers.InRecordState(_ciphersuites);
                                                   ^
/home/meghan/zig-cache/zigmod/deps/git/github.com/nektro/iguanaTLS/c9403b8414d7f80b5e2c04c8f1f8780ca1d2827f/src/main.zig:1743:13: note: while checking this field
            in_record: struct {
            ^
/home/meghan/zig-cache/zigmod/deps/git/github.com/nektro/iguanaTLS/c9403b8414d7f80b5e2c04c8f1f8780ca1d2827f/src/main.zig:1754:9: note: while checking this field
        read_state: ReadState = .none,
        ^
/home/meghan/zig-cache/zigmod/deps/git/github.com/truemedian/zfetch/829973144f680cd16be16923041fa810c1dee417/src/connection.zig:66:5: note: while checking this field
    secure_context: ?TlsClient = null,
    ^
/home/meghan/zig-cache/zigmod/deps/git/github.com/truemedian/zfetch/829973144f680cd16be16923041fa810c1dee417/src/request.zig:76:5: note: while checking this field
    socket: Connection,
    ^
error: zigmod...
error: The step exited with error code 1
error: the following build command failed with exit code 1:
/home/meghan/zig-cache/o/a1aea7840d7c6cb225314ff3837e83d7/build /home/meghan/.local/share/zig/zig /run/media/meghan/dev/zigmod /home/meghan/zig-cache /home/meghan/.cache/zig
```

### Actual Behavior

stack trace with `@compileError` decl missing key frames

```
/home/meghan/.local/share/zig/lib/std/builtin.zig:187:22: error: deprecated; use Type
pub const TypeInfo = @compileError("deprecated; use Type");
                     ^
/home/meghan/zig-cache/zigmod/deps/git/github.com/nektro/iguanaTLS/c9403b8414d7f80b5e2c04c8f1f8780ca1d2827f/src/main.zig:1743:13: note: while checking this field
            in_record: struct {
            ^
/home/meghan/zig-cache/zigmod/deps/git/github.com/nektro/iguanaTLS/c9403b8414d7f80b5e2c04c8f1f8780ca1d2827f/src/main.zig:1754:9: note: while checking this field
        read_state: ReadState = .none,
        ^
/home/meghan/zig-cache/zigmod/deps/git/github.com/truemedian/zfetch/829973144f680cd16be16923041fa810c1dee417/src/connection.zig:66:5: note: while checking this field
    secure_context: ?TlsClient = null,
    ^
/home/meghan/zig-cache/zigmod/deps/git/github.com/truemedian/zfetch/829973144f680cd16be16923041fa810c1dee417/src/request.zig:76:5: note: while checking this field
    socket: Connection,
    ^
error: zigmod...
error: The step exited with error code 1
error: the following build command failed with exit code 1:
/home/meghan/zig-cache/o/294af99d93717dfe975e0353957d293b/build /home/meghan/.local/share/zig/zig /run/media/meghan/dev/zigmod /home/meghan/zig-cache /home/meghan/.cache/zig
```

**Comment by nektro** [comment]
reduction:

```zig
test {
    if (foo()) {
        return;
    }
    return error.TestFailed;
}

fn foo() Foo() {
    return true;
}

fn Foo() type {
    @compileError("oops");
}
```

```
test.zig:13:5: error: oops
    @compileError("oops");
    ^~~~~~~~~~~~~~~~~~~~~
test.zig:8:13: note: called from here
fn foo() Foo() {
         ~~~^~
```

no notes of line 2 where `foo()` is called and no mention of `-freference-trace`

adding the latter also has no effect

**Comment by perillo** [comment]
@nektro the example seems to work with `0.12.0-dev.2341+92211135`:

```console
test.zig:13:5: error: oops
    @compileError("oops");
    ^~~~~~~~~~~~~~~~~~~~~
test.zig:8:13: note: called from here
fn foo() Foo() {
         ~~~^~
referenced by:
    test_0: test.zig:2:9
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

The problem is that, in my experience, most of the time you **need** to add the `freference-trace` flag when `@compileError` is used, especially when using `fmt`.

**Comment by Vexu** [comment]
Looks like the original issue could have been fixed by f32b9bc776bfffe0a1adadc013ff3fa3e5d6d34b
