### PR TITLE
std: Skip `comptime` struct fields in `mem.zeroes()`

### LINKED ISSUE #9934: `std.mem.zeroes` does not work with `std.PackedIntArray` error: cannot assign to constant
### Zig Version

0.9.0-dev.1277+c4df9bf56

### Steps to Reproduce

```zig
const std = @import("std");
test "foo" {
    _ = std.mem.zeroes(std.PackedIntArray(u2, 4));
}
```

Note: `git bisect` indicates that this was introduced with commit 526191bfafe722700323df30647eed0c03fc2403

### Expected Behavior

Compile without error.

### Actual Behavior

```
➜  bugs zig test zeroes.zig
/Users/ehaas/source/zig/build/lib/zig/std/mem.zig:258:59: error: cannot assign to constant
                    @field(structure, field.name) = zeroes(@TypeOf(@field(structure, field.name)));
                                                          ^
./zeroes.zig:3:23: note: called from here
    _ = std.mem.zeroes(std.PackedIntArray(u2, 4));
                      ^
./zeroes.zig:2:15: note: called from here
test "zeroes" {
              ^
```

### PR DESCRIPTION
**Pull request by AliChraghi**
closes #9934

### CODE REVIEW

**Review by andrewrk — CHANGES_REQUESTED** [review]
Thank you for the fix. Could we please get test coverage for it?

**Comment by andrewrk** [comment]
the zig fmt check is failing

**Comment by AliChraghi** [comment]
sorry for slow response, the CI results does't email to me and I forget
