### ISSUE TITLE
SDL2 C import fails on M1 Mac

### ISSUE THREAD

**Issue by clebs** [ziglang/zig#12774]
### Zig Version

0.10.0-dev.3883+924679abc

### Steps to Reproduce

On an M1 Mac do the following steps:
- Install SDL2 via Homebrew (currently version 2.24.0)
- Create a new project with `zig init-exe` and add the following lines to the `build.zig` file:
```
    exe.linkSystemLibrary("sdl2");
    exe.linkLibC();
```
- Add the following import to the `src/main.zig` file:
```
const c = @cImport({
     @cInclude("SDL.h");
});
```

### Expected Behavior

The cImport is resolved.

### Actual Behavior

Following error appears:
```
/Path/to/project/zig-cache/o/30b7a6b66304648761f2822fc8352b4d/cimport.zig:205:39: error: use of undeclared identifier 'struct__OSUnalignedU16'
    return _OSSwapInt16(@intToPtr([*c]struct__OSUnalignedU16, @intCast(usize, @ptrToInt(_base)) +% _offset).*.__val);
                                      ^~~~~~~~~~~~~~~~~~~~~~
/Path/to/project/zig-cache/o/30b7a6b66304648761f2822fc8352b4d/cimport.zig:210:39: error: use of undeclared identifier 'struct__OSUnalignedU32'
    return _OSSwapInt32(@intToPtr([*c]struct__OSUnalignedU32, @intCast(usize, @ptrToInt(_base)) +% _offset).*.__val);
                                      ^~~~~~~~~~~~~~~~~~~~~~
/Path/to/project/zig-cache/o/30b7a6b66304648761f2822fc8352b4d/cimport.zig:215:39: error: use of undeclared identifier 'struct__OSUnalignedU64'
    return _OSSwapInt64(@intToPtr([*c]struct__OSUnalignedU64, @intCast(usize, @ptrToInt(_base)) +% _offset).*.__val);
                                      ^~~~~~~~~~~~~~~~~~~~~~
/Path/to/project/zig-cache/o/30b7a6b66304648761f2822fc8352b4d/cimport.zig:221:19: error: use of undeclared identifier 'struct__OSUnalignedU16'
    @intToPtr([*c]struct__OSUnalignedU16, @intCast(usize, @ptrToInt(_base)) +% _offset).*.__val = _OSSwapInt16(_data);
                  ^~~~~~~~~~~~~~~~~~~~~~
/Path/to/project/zig-cache/o/30b7a6b66304648761f2822fc8352b4d/cimport.zig:227:19: error: use of undeclared identifier 'struct__OSUnalignedU32'
    @intToPtr([*c]struct__OSUnalignedU32, @intCast(usize, @ptrToInt(_base)) +% _offset).*.__val = _OSSwapInt32(_data);
                  ^~~~~~~~~~~~~~~~~~~~~~
/Path/to/project/zig-cache/o/30b7a6b66304648761f2822fc8352b4d/cimport.zig:233:19: error: use of undeclared identifier 'struct__OSUnalignedU64'
    @intToPtr([*c]struct__OSUnalignedU64, @intCast(usize, @ptrToInt(_base)) +% _offset).*.__val = _OSSwapInt64(_data);
                  ^~~~~~~~~~~~~~~~~~~~~~
/Path/to/project/src/main.zig:1:20: error: C import failed: AnalysisFail
const c = @cImport({
                   ^~~~~~~~
```

**Comment by Vexu** [comment]
Duplicate of #12737

**Comment by clebs** [comment]
I am not sure these are the same issue, the proposed fix on #12737 does not fix the problem for this particular case.

**Comment by clebs** [comment]
Interesting might be that the proposed fix actually works on Mac OSX 12.5 on an Intel Macbook from 2018, but it does not work on a 2022 M1 Macbook.
That is the main reason I was sure it was something different happening only on M1.
