### ISSUE TITLE
`@import("myfile.zig")` has stopped working when using `zig build-obj` directly

### ISSUE THREAD

**Issue by mikdusan** [ziglang/zig#13665]
### Zig Version

0.11.0-dev.334+2df47df39

### Steps to Reproduce and Observed Behavior

```sh
[master] tiberius▸ zig build-obj z0.zig
z0.zig:4:35: error: import of file outside package path: 'z1.zig'
    std.log.debug("{}", .{@import("z1.zig").num});
                                  ^~~~~~~~
referenced by:
    comptime_0: /Users/mike/project/zig/work/main/lib/std/start.zig:59:50
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

##### `z0.zig`
```zig
const std = @import("std");

pub fn main() !void {
    std.log.debug("{}", .{@import("z1.zig").num});
}
```

##### `z1.zig`
```zig
pub const num = 5;
```

note: bisected to d24aaf8847336e12b6571e13d57f6d112452d97d (but 58d3ee2a08f5a1f1c66d5e3b4f215361073c6372 is needed to build zig

### Expected Behavior

```sh
[21bd13626] tiberius▸ zig build-obj z0.zig
# success
```

note: last working commit: 21bd13626d66c36c327bb317bd09cad979d92327

**Comment by gitusel** [comment]
Using zig build --build-file also create issues like:
- Using default zig init-exe directory
-create a zig module next to build.zig example 
b1.zig 
pub fn t () void {}

- add b1 to build.zig
const std = @import("std");
const b1 = @import("b1.zig");

pub fn build(b: *std.build.Builder) void {
    b1.t();
../..

tree
├── b1.zig
├── build.zig
└── src
    └── main.zig

zig build  -> ok
zig build --build-file build.zig -> failure
build.zig:2:20: error: import of file outside package path: 'b1.zig'
const b1 = @import("b1.zig");

**Comment by gitusel** [comment]
commit 0.11.0-dev.339+3ae4931dc changed last example error to:
error: Unable to create path ../../../../../../zig-cache: ReadOnlyFileSystem
error: ReadOnlyFileSystem

**Comment by andrewrk** [comment]
Fixed by 3ae4931dc1a3b1b338d2fd3a49a5a79b445bebf6

**Comment by gitusel** [comment]
Issues sill present.

**Comment by mikdusan** [comment]
issue still manifests on macOS

**Comment by gitusel** [comment]
As a reminder, one way to test the issue:
zig init-exe
zig build --build-file build.zig

**Comment by leecannon** [comment]
@gitusel That error is similar to one zls was experiencing https://github.com/zigtools/zls/pull/789
The issue is was caused by the `cache_root` being resolved to `/zig-cache` on this line https://github.com/ziglang/zig/blob/52e1be9c68aba87c1c530461c794b9c87c8a2016/lib/std/build.zig#L181

A build root of /path/to/my/project with a cache_root of zig-cache resolves to ../../../../zig-cache which results in zig using a cache path of /zig-cache.

**Comment by gitusel** [comment]
@leecannon, the error exists with a default build.zig generated by zig init-exe.

**Comment by leecannon** [comment]
Yea looks like issue happens with `zig build --build-file build.zig` but not `zig build --build-file ./build.zig`
