### ISSUE TITLE
Errors running the compiler test-suite locally: `zig.h` not found, memory leaks and more

### ISSUE THREAD

**Issue by IntegratedQuantum** [ziglang/zig#14193]
### Zig Version

0.11.0-dev.1183+2b9478ce1

### Steps to Reproduce and Observed Behavior

```
git clone https://github.com/ziglang/zig
cd zig
zig build --search-prefix ~/zig-bootstrap/out/native-linux-gnu-native/ --zig-lib-dir lib -Dstatic-llvm
./zig-out/bin/zig build --zig-lib-dir lib test -Dskip-release
```

## Observed behaviour
full log: [log.txt](https://github.com/ziglang/zig/files/10344380/log.txt)
There appear to be several different error patterns:
### Not Built With Extensions (lines 1 to 93)
```
compiler [9/1188] adding_numbers_at_runtime_and_comptime (stage2, x86_64-windows) [1/3]... 
Case 'adding_numbers_at_runtime_and_comptime (stage2, x86_64-windows)': unexpected errors at update_index=0:
================================================================================
error: unable to generate DLL import .lib file: ZigCompilerNotBuiltWithLLVMExtensions
================================================================================
```
I guess these are to be expected? I built llvm using zig-bootstrap.

### 'zig.h' not found (lines 94 to 177)
```
compiler [948/1188] CBE: hello world with updates [1/4] update [3/4] execute... 
error(compilation): clang failed with stderr: ../0DSsHuCaiTVC9jd4/test_case.c:1:10: fatal error: 'zig.h' file not found

../0DSsHuCaiTVC9jd4/test_case.c:1:1: error: unable to build C object: clang exited with code 1

CBE: hello world with updates: execution exited with code 1:
/home/mint/zig2/zig/zig-out/bin/zig run -cflags -std=c99 -pedantic -Werror -Wno-incompatible-library-redeclaration -- -lc ../0DSsHuCaiTVC9jd4/test_case.c -I lib
```
### This seems to be a seperate thing (line 178)
```
compiler [971/1188] header with multiple includes [1/1] update [2/3] parse/analysis/cod... adding_numbers_at_runtime_and_comptime (stage2, x86_64-windows) failed: UnexpectedCompileErrors
```

### memory leaks (lines 216 to 11823)
a lot of memory leaks (see the full log)

### Expected Behavior

The test should run without errors or leaks.
When the compiler isn't built with llvm extensions the corresponding tests should be skipped.

**Comment by Vexu** [comment]
The first issue is caused by not passing `--search-prefix` and `-Dstatic-llvm` to `build test` though it should know to skip the test.

The second one I'm guessing is caused by the same as the first one but again it should work.

Most or all memory leaks are caused by #13017.

**Comment by IntegratedQuantum** [comment]
Running with
```
./zig-out/bin/zig build --search-prefix ~/zig-bootstrap/out/x86_64-linux-gnu-native/ --zig-lib-dir lib -Dstatic-llvm test
```
I still get the `'zig.h' not found`, all the other issues, including the memory leak, are gone.
full log: [log.txt](https://github.com/ziglang/zig/files/10345846/log.txt)

**Comment by IntegratedQuantum** [comment]
Also I would suggest adding a node to `CONTRIBUTING.md` that these commands need to be added to the test command as well.

**Comment by Vexu** [comment]
> Also I would suggest adding a note to `CONTRIBUTING.md` that these flags need to be added to the test command as well.

They aren't needed for the tests, only if you want to run tests that require the LLVM backend.

For the `zig.h` issue I'm guessing you're not running the tests from the same directory as `build.zig`? Should work either way.

**Comment by IntegratedQuantum** [comment]
> I'm guessing you're not running the tests from the same directory as build.zig?

I'm running them from the root directory of the zig repository which also contains the build.zig.

**Comment by Vexu** [comment]
Seems like `build test-cases` needs to be ran in your build directory (or any directory one level higher than `build.zig`)

**Comment by IntegratedQuantum** [comment]
I used [Option B: Use a Pre-Built Zig Binary](https://github.com/ziglang/zig/wiki/Building-Zig-From-Source#option-b-use-a-pre-built-zig-binary), so I don't have a build directory.

I tried to create an empty build directory and run the tests from there, but it didn't work:
```
mint@mint:~/zig2/zig$ mkdir build
mint@mint:~/zig2/zig$ cd build
mint@mint:~/zig2/zig/build$ ../zig-out/bin/zig build --build-file ../build.zig --search-prefix ~/zig-bootstrap/out/x86_64-linux-gnu-native/ --zig-lib-dir ../lib -Dstatic-llvm test
error: Failed to add package at path /home/mint/zig2/zig-cache/options/upOCK9ImSJUwW6szqDpojBfaSftacU-5YfnDCQs98L_0rUtWoEvD9n9H4GRm39pN: FileNotFound
```

**Comment by Vexu** [comment]
Works for me with:
```
$ cd build
$ zig build test-cases -Dno-lib -Dstatic-llvm --search-prefix /home/vexu/Documents/zig/zig-bootstrap/out/x86_64-linux-musl-haswell+aes/ 
```
