### ISSUE TITLE
Cross-compiling to macos or building inside nix sandbox fails to find headers from -isystem path

### ISSUE THREAD

**Issue by Cloudef** [ziglang/zig#18571]
### Zig Version

zig-0.12.0-dev.2063+804cee3b9

### Steps to Reproduce and Observed Behavior

On linux:
```bash
mkdir tmp; cd tmp
nix flake init -t github:Cloudef/mach-flake#engine
nix develop
zig build -Dtarget=aarch64-macos-none
```

On osx:
```bash
mkdir tmp; cd tmp
nix flake init -t github:Cloudef/mach-flake#engine
nix build .
```

Fails with
```
       > #include <libDER/DERItem.h>
       >          ^
       > error: the following command failed with 2 compilation errors:
```
Log: https://github.com/Cloudef/mach-flake/actions/runs/7524739371/job/20479986373

Strace shows:
```
[pid 1028258] stat("/home/nix/.cache/zig/p/12207bc2707695102c636c26b60343e634127ee4d6e23210b1ae1664b2b2fea6076f/Frameworks/libDER.framework", 0x7ffc4ab8ce40) = -1 ENOENT (No such file or directory)
[pid 1028258] stat("/home/nix/dev/personal/test/zig-cache/i/4cdd73579f470868b9b32c39128a7690/include/libDER", 0x7ffc4ab8d500) = -1 ENOENT (No such file or directory)
[pid 1028258] stat("/nix/store/rj8w2d3qsljak7b7ql55jxlffxz5q1c5-zig-0.12.0-dev.2063+804cee3b9/lib/libcxx/include/libDER", 0x7ffc4ab8d500) = -1 ENOENT (No such file or directory)
[pid 1028258] stat("/nix/store/rj8w2d3qsljak7b7ql55jxlffxz5q1c5-zig-0.12.0-dev.2063+804cee3b9/lib/libcxxabi/include/libDER", 0x7ffc4ab8d500) = -1 ENOENT (No such file or directory)
[pid 1028258] stat("/nix/store/rj8w2d3qsljak7b7ql55jxlffxz5q1c5-zig-0.12.0-dev.2063+804cee3b9/lib/include/libDER", 0x7ffc4ab8d500) = -1 ENOENT (No such file or directory)
[pid 1028258] stat("/nix/store/rj8w2d3qsljak7b7ql55jxlffxz5q1c5-zig-0.12.0-dev.2063+804cee3b9/lib/libc/include/any-macos-any/libDER", 0x7ffc4ab8d500) = -1 ENOENT (No such file or directory)
[pid 1028258] stat("/home/nix/.cache/zig/p/12207bc2707695102c636c26b60343e634127ee4d6e23210b1ae1664b2b2fea6076f/Frameworks/Security.framework/Frameworks/libDER.framework", 0x7ffc4ab8dd50) = -1 ENOENT (No such file or directory)
[pid 1028258] stat("/home/nix/.cache/zig/p/12207bc2707695102c636c26b60343e634127ee4d6e23210b1ae1664b2b2fea6076f/Frameworks/CoreServices.framework/Frameworks/libDER.framework", 0x7ffc4ab8dd50) = -1 ENOENT (No such file or directory)
[pid 1028258] stat("/home/nix/.cache/zig/p/12207bc2707695102c636c26b60343e634127ee4d6e23210b1ae1664b2b2fea6076f/Frameworks/ApplicationServices.framework/Frameworks/libDER.framework", 0x7ffc4ab8dd50) = -1 ENOENT (No such file or directory)
[pid 1028258] stat("/home/nix/.cache/zig/p/12207bc2707695102c636c26b60343e634127ee4d6e23210b1ae1664b2b2fea6076f/Frameworks/Security.framework/Headers/libDER", 0x7ffc4ab8de50) = -1 ENOENT (No such file or directory)
```

Which doesn't try the path 
`/home/nix/.cache/zig/p/12207bc2707695102c636c26b60343e634127ee4d6e23210b1ae1664b2b2fea6076f/include`

### Expected Behavior

Zig picks the headers from the given -isystem path.

Weirdly it works fine if you build on osx without sandbox (follow the linux steps, or simply `nix run .`), which leads me to believe it picks the system headers.

**Comment by Cloudef** [comment]
With `0.12.0-dev.1092+68ed78775` cross-compiling works.

```bash
mkdir tmp; cd tmp
nix flake init -t 'github:Cloudef/mach-flake?rev=8cc73d4b924132b13c2e64157a9234c74d0abfa1#engine'
nix develop
zig build -Dtarget=aarch64-macos-none
file ./zig-out/bin/myapp
# ./zig-out/bin/myapp: Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE|HAS_TLV_DESCRIPTORS>
```

**Comment by kubkon** [comment]
Would you be able to bisect the offending commit(s)?

**Comment by slimsag** [comment]
We are seeing this without Nix, when cross-compiling Mach from a Linux host for macOS.

Nothing on our end has really changed that I know of. All we know is that this setup worked in `0.12.0-dev.1092+68ed78775`, and stopped working once we upgraded to `0.12.0-dev.2063+804cee3b9` (a quite large jump unfortunately)

You can see [here]() that the way we include the macOS SDK has not changed (and still is done via a compile step, instead of the newer module API):

```zig
pub fn addPaths(step: *std.Build.Step.Compile) void {
    step.addSystemFrameworkPath(.{ .path = sdkPath("/Frameworks") });
    step.addSystemIncludePath(.{ .path = sdkPath("/include") });
    step.addLibraryPath(.{ .path = sdkPath("/lib") });
}
```

Note that we do not use a sysroot (and never have), this same setup has worked for us with `0.12.0-dev.1092+68ed78775` for certain.

In [the build logs](https://gist.githubusercontent.com/slimsag/a46a773546303b7a76f3e14ff3065a11/raw/208556ae62c0605189b2ad9b5b5ab5b7befa99e5/log.txt) during cross-compilation, I am able to see that the `step.addSystemFrameworkPath` above has correctly translated to `-iframework $CACHE_DIR/Frameworks`, as well as the other two translating to `-isystem` and `-L` properly:

```
Run zig build -Dtarget=aarch64-macos
...
/home/runner/.cache/zig/p/$XCODE_FRAMEWORKS/Frameworks/Security.framework/Headers/oids.h:35:10: error: 'libDER/DERItem.h' file not found
error: the following command failed with 2 compilation errors:
...
/usr/local/bin/zig build-exe
...
-iframework /home/runner/.cache/zig/p/$XCODE_FRAMEWORKS/Frameworks
-isystem /home/runner/.cache/zig/p/$XCODE_FRAMEWORKS/include
-iframework /home/runner/.cache/zig/p/$XCODE_FRAMEWORKS/Frameworks
-isystem /home/runner/.cache/zig/p/$XCODE_FRAMEWORKS/include
-iframework /home/runner/.cache/zig/p/$XCODE_FRAMEWORKS/Frameworks
-isystem /home/runner/.cache/zig/p/$XCODE_FRAMEWORKS/include
-iframework /home/runner/.cache/zig/p/$XCODE_FRAMEWORKS/Frameworks
-isystem /home/runner/.cache/zig/p/$XCODE_FRAMEWORKS/include
-L /home/runner/.cache/zig/p/$XCODE_FRAMEWORKS/lib
-L /home/runner/.cache/zig/p/$XCODE_FRAMEWORKS/lib
-L /home/runner/.cache/zig/p/$XCODE_FRAMEWORKS/lib
-L /home/runner/.cache/zig/p/$XCODE_FRAMEWORKS/lib
```

The fact that `/home/runner/.cache/zig/p/$XCODE_FRAMEWORKS/Frameworks/Security.framework` was used in the first place tells us that `-iframework` had the intended effect. But it is unable to locate `libDER/DERItem.h` which exists exactly in the `-isystem` include path:

```
/home/runner/.cache/zig/p/$XCODE_FRAMEWORKS/include/libDER/DERItem.h
```

**Comment by slimsag** [comment]
It may not be possible to bisect this in a straightforward way; because there are only two Zig versions Mach was compatible with here, once from August and one from this month. It might be possible by creating a smaller minimal repro with the `xcode-frameworks` package, but even then the build APIs have changed so you'd need to fork xcode-frameworks and alter that code while bisecting.

The only related change I was able to find recently was https://github.com/ziglang/zig/commit/8944dea23fb554290a4b54ca40b0594f6e3f77a9#diff-d924ca21d81d7d5a59eb9e10d3e2689c4c58a7e28e6ecce6a064701666f5a730L2789 - I have a hunch it could be related, but zero evidence. Just wild speculation.

**Comment by Cloudef** [comment]
Seems to fail even with `--sysroot` 
https://github.com/Cloudef/mach-flake/actions/runs/7537072329/job/20515438436
```
--sysroot /nix/store/0z0y87bspb360348hx6svr74crhnn6ib-MacOSX-SDK-11.0.0
~ ❱ ls /nix/store/0z0y87bspb360348hx6svr74crhnn6ib-MacOSX-SDK-11.0.0/usr/include/libDER/DERItem.h
-r--r--r-- 6 root nixbld 1.4K Jan  1  1970 /nix/store/0z0y87bspb360348hx6svr74crhnn6ib-MacOSX-SDK-11.0.0/usr/include/libDER/DERItem.h
```

**Comment by slimsag** [comment]
@Cloudef we don't want to / cannot use sysroot anyway, it prevents using external frameworks from the host.

**Comment by Cloudef** [comment]
@slimsag in nix sandbox that is not allowed, but that's not related to mach anyways.

**Comment by Cloudef** [comment]
I think it happens whenever you try to link to any framework that isn't CoreFoundation. I may be able to cook something later.

**Comment by kubkon** [comment]
I would very much appreciate a reduction :pray:

**Comment by slimsag** [comment]
I have a hunch that this will reproduce it, but I am not able to check currently as I don't have quick acess to a linux machine:

```
git clone https://github.com/slimsag/tmp-nixos-bug-junk
cd tmp-nixos-bug-junk/
zig build -Dtarget=x86_64-macos
```

This should fail if ran on a linux host, with similar errors as the original issue description

**Comment by kubkon** [comment]
Excellent, thanks! I'll check it right away!

**Comment by kubkon** [comment]
Hmm it doesn't do it. I'll try including more headers from other frameworks and see if that does it as suggested by @Cloudef.

**Comment by Cloudef** [comment]
```
From 5876ebfc8f61250c0a10600f0de288b3a77cdc4b Mon Sep 17 00:00:00 2001
From: Jari Vetoniemi <jari.vetoniemi@cloudef.pw>
Date: Sat, 27 Jan 2024 10:50:19 +0900
Subject: [PATCH] Macos fail

---
 build.zig    | 2 ++
 src/main.zig | 3 ++-
 2 files changed, 4 insertions(+), 1 deletion(-)

diff --git a/build.zig b/build.zig
index d47ee15..0075f16 100644
--- a/build.zig
+++ b/build.zig
@@ -15,5 +15,7 @@ pub fn build(b: *std.Build) void {
     // Use xcode-frameworks package, this adds -iframework flags
     @import("xcode_frameworks").addPaths(exe);
 
+    exe.linkSystemLibrary("objc");
     exe.linkFramework("CoreFoundation");
+    exe.linkFramework("Cocoa");
 }
diff --git a/src/main.zig b/src/main.zig
index 5693410..99e44df 100644
--- a/src/main.zig
+++ b/src/main.zig
@@ -1,7 +1,7 @@
 const std = @import("std");
 
 const c = @cImport({
-    @cInclude("CoreFoundation/CFString.h");
+    @cInclude("CoreFoundation/CoreFoundation.h");
     @cInclude("CoreFoundation/CFCGTypes.h");
 });
 
@@ -9,6 +9,7 @@ pub fn main() !void {
     // Use CoreFoundation
     const name = c.CFStringCreateWithCString(null, "hi", c.kCFStringEncodingUnicode);
     defer c.CFRelease(name);
+    std.mem.doNotOptimizeAway(name);
 
     std.debug.print("it builds and runs\n", .{});
 }
-- 
2.43.0
```
These modifications cause @slimsag 's repo to fail

```
error: missing dynamic library dependency: '/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit'
    note: tried /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit.tbd
    note: tried /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit.dylib
    note: tried /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
error: missing dynamic library dependency: '/System/Library/Frameworks/CoreData.framework/Versions/A/CoreData'
    note: tried /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData.tbd
    note: tried /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData.dylib
    note: tried /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
```

Yet there is on the zig build-exe command line:
`-iframework /home/nix/.cache/zig/p/12207bc2707695102c636c26b60343e634127ee4d6e23210b1ae1664b2b2fea6076f/Frameworks` 

```
ls /home/nix/.cache/zig/p/12207bc2707695102c636c26b60343e634127ee4d6e23210b1ae1664b2b2fea6076f/Frameworks
total 0
drwxr-xr-x 1 nix users  50 Jan 15 10:57 AppKit.framework
drwxr-xr-x 1 nix users  96 Jan 15 10:57 ApplicationServices.framework
drwxr-xr-x 1 nix users 110 Jan 15 10:57 AudioToolbox.framework
drwxr-xr-x 1 nix users  56 Jan 15 10:57 AudioUnit.framework
drwxr-xr-x 1 nix users  70 Jan 15 10:57 Carbon.framework
drwxr-xr-x 1 nix users  56 Jan 15 10:57 CFNetwork.framework
drwxr-xr-x 1 nix users  30 Jan 15 10:57 CloudKit.framework
drwxr-xr-x 1 nix users  48 Jan 15 10:57 Cocoa.framework
drwxr-xr-x 1 nix users  56 Jan 15 10:57 ColorSync.framework
drwxr-xr-x 1 nix users  56 Jan 15 10:57 CoreAudio.framework
drwxr-xr-x 1 nix users  30 Jan 15 10:57 CoreAudioTypes.framework
drwxr-xr-x 1 nix users  68 Jan 15 10:57 CoreData.framework
drwxr-xr-x 1 nix users  66 Jan 15 10:57 CoreFoundation.framework
drwxr-xr-x 1 nix users  62 Jan 15 10:57 CoreGraphics.framework
drwxr-xr-x 1 nix users  92 Jan 15 10:57 CoreImage.framework
drwxr-xr-x 1 nix users  62 Jan 15 10:57 CoreLocation.framework
drwxr-xr-x 1 nix users  82 Jan 15 10:57 CoreServices.framework
drwxr-xr-x 1 nix users  54 Jan 15 10:57 CoreText.framework
drwxr-xr-x 1 nix users  56 Jan 15 10:57 CoreVideo.framework
drwxr-xr-x 1 nix users  68 Jan 15 10:57 DiskArbitration.framework
drwxr-xr-x 1 nix users  58 Jan 15 10:57 Foundation.framework
drwxr-xr-x 1 nix users  66 Jan 15 10:57 GameController.framework
drwxr-xr-x 1 nix users  52 Jan 15 10:57 ImageIO.framework
drwxr-xr-x 1 nix users  48 Jan 15 10:57 IOKit.framework
drwxr-xr-x 1 nix users  56 Jan 15 10:57 IOSurface.framework
drwxr-xr-x 1 nix users  30 Jan 15 10:57 Kernel.framework
drwxr-xr-x 1 nix users  48 Jan 15 10:57 Metal.framework
drwxr-xr-x 1 nix users  50 Jan 15 10:57 OpenGL.framework
drwxr-xr-x 1 nix users  58 Jan 15 10:57 QuartzCore.framework
drwxr-xr-x 1 nix users  54 Jan 15 10:57 Security.framework
drwxr-xr-x 1 nix users  52 Jan 15 10:57 Symbols.framework
```

**Comment by Cloudef** [comment]
It seems the issue is when resolving the dependencies of a framework. Perhaps the iframework is not being delegated to linker?

**Comment by kubkon** [comment]
This should be fixed by https://github.com/ziglang/zig/pull/18677 but it's still not the original issue since what you reproed was a linker bug, while the original issue is a frontend bug.

**Comment by Cloudef** [comment]
@slimsag looking at the build logs again, this error comes while compiling a mach_dawn.cpp (C++) file. Why is it even trying to process zig code?

```
/usr/local/bin/zig build-exe -ldawn -lobjc -cflags -std=c++17 -- /home/runner/.cache/zig/p/122044bcebd28b7d54fb40cbebc04ef6bab0a385952e3193bcf90b37e062ce382495/src/mach_dawn.cpp /home/runner/work/mach-editor/mach-editor/zig-cache/o/d116785f7fcc722e31c59d76c78e9bab/libspirv-cross.a /home/runner/work/mach-editor/mach-editor/zig-cache/o/2ae2c28c85f480816ecc9bd1237147fa/libspirv-opt.a -ODebug -target aarch64-macos -mcpu baseline -iframework /home/runner/.cache/zig/p/12207bc2707695102c636c26b60343e634127ee4d6e23210b1ae1664b2b2fea6076f/Frameworks -isystem /home/runner/.cache/zig/p/12207bc2707695102c636c26b60343e634127ee4d6e23210b1ae1664b2b2fea6076f/include -I /home/runner/work/mach-editor/mach-editor/zig-cache/mach/gpu-dawn/release-f331c1c/include -I /home/runner/.cache/zig/p/12203efcd97b1186ccc73cd86e91f6d8e14e8146930645fcff5412abf2aad27edbb7/src/dawn -iframework /home/runner/.cache/zig/p/12207bc2707695102c636c26b60343e634127ee4d6e23210b1ae1664b2b2fea6076f/Frameworks -isystem /home/runner/.cache/zig/p/12207bc2707695102c636c26b60343e634127ee4d6e23210b1ae1664b2b2fea6076f/include -iframework /home/runner/.cache/zig/p/12207bc2707695102c636c26b60343e634127ee4d6e23210b1ae1664b2b2fea6076f/Frameworks -isystem /home/runner/.cache/zig/p/12207bc2707695102c636c26b60343e634127ee4d6e23210b1ae1664b2b2fea6076f/include -iframework /home/runner/.cache/zig/p/12207bc2707695102c636c26b60343e634127ee4d6e23210b1ae1664b2b2fea6076f/Frameworks -isystem /home/runner/.cache/zig/p/12207bc2707695102c636c26b60343e634127ee4d6e23210b1ae1664b2b2fea6076f/include -I /home/runner/.cache/zig/p/122044bcebd28b7d54fb40cbebc04ef6bab0a385952e3193bcf90b37e062ce382495/src -I /home/runner/work/mach-editor/mach-editor/zig-cache/i/c76c9aeb480ca9233f7c29846cf30f8c/include -I /home/runner/work/mach-editor/mach-editor/zig-cache/i/c0a6ba6657137f3f36faf920b53c8890/include -L /home/runner/.cache/zig/p/12207bc2707695102c636c26b60343e634127ee4d6e23210b1ae1664b2b2fea6076f/lib -L /home/runner/work/mach-editor/mach-editor/zig-cache/mach/gpu-dawn/release-f331c1c/aarch64-macos-none/release-fast -L /home/runner/.cache/zig/p/12207bc2707695102c636c26b60343e634127ee4d6e23210b1ae1664b2b2fea6076f/lib -L /home/runner/.cache/zig/p/12207bc2707695102c636c26b60343e634127ee4d6e23210b1ae1664b2b2fea6076f/lib -L /home/runner/.cache/zig/p/12207bc2707695102c636c26b60343e634127ee4d6e23210b1ae1664b2b2fea6076f/lib --dep mach-core --dep app --mod root /home/runner/work/mach-editor/mach-editor/src/main.zig --dep mach-gpu --dep mach-glfw --dep mach-gamemode --mod mach-core /home/runner/.cache/zig/p/12205da1ecba58ba8c9ca65dbf75e32f42fde0490d34a98596ae72d4d3db81659dc5/src/main.zig --dep mach-core --dep mach --dep mach-sysaudio --mod app /home/runner/work/mach-editor/mach-editor/src/app.zig -I /home/runner/work/mach-editor/mach-editor/zig-cache/mach/gpu-dawn/release-f331c1c/include -I /home/runner/.cache/zig/p/12203efcd97b1186ccc73cd86e91f6d8e14e8146930645fcff5412abf2aad27edbb7/src/dawn -I /home/runner/.cache/zig/p/122044bcebd28b7d54fb40cbebc04ef6bab0a385952e3193bcf90b37e062ce382495/src --mod mach-gpu /home/runner/.cache/zig/p/122044bcebd28b7d54fb40cbebc04ef6bab0a385952e3193bcf90b37e062ce382495/src/main.zig /home/runner/work/mach-editor/mach-editor/zig-cache/o/cd4bc97670a4ce2f5a386671694dd599/libglfw.a -I /home/runner/work/mach-editor/mach-editor/zig-cache/i/4cdd73579f470868b9b32c39128a7690/include --mod mach-glfw /home/runner/.cache/zig/p/1220e0d40d19f6b61d6b1290401504e8052aeb980395a500ffb2bc351f749b42ec47/src/main.zig --mod mach-gamemode /home/runner/.cache/zig/p/12203aaefcb85324476a6d3d277451ea1feaac3549641d717c631a3cffd38eecfbda/src/main.zig --dep mach-core --dep mach-ecs --dep mach-sysaudio --dep mach-basisu --dep mach-freetype --dep mach-harfbuzz --dep mach-sysjs=sysjs --dep font-assets --mod mach /home/runner/.cache/zig/p/1220082e849c856f05d13ce935ff2957be9ab27a8316226cd6c9585a0a1dfbbe515f/src/main.zig -ODebug -target aarch64-macos -mcpu baseline --dep sysjs --dep objc --mod mach-sysaudio /home/runner/.cache/zig/p/12206c2ca0378bbc54721553e8167c037325e95e2791379fbe0e245a34334679dc90/src/main.zig --mod mach-ecs /home/runner/.cache/zig/p/1220a5785894922edb70e84f5e00917defbffc64ee16e88cc8fdb3ccf68c9b244a5d/src/main.zig /home/runner/work/mach-editor/mach-editor/zig-cache/o/59cf7be930e3dc090a754e18070815f6/libmach-basisu.a --mod mach-basisu /home/runner/.cache/zig/p/12204098c8d8d15a687068a3c0b15fe95d20f8fe074531e34e78f9dfe518cf86a67c/src/main.zig /home/runner/work/mach-editor/mach-editor/zig-cache/o/456c41d295e8958a5db932bc3f50e098/libfreetype.a -I /home/runner/work/mach-editor/mach-editor/zig-cache/i/609ca7687bbcd3221945b245a5e5ddfb/include --mod mach-freetype /home/runner/.cache/zig/p/12205faaaaf547019f0763ac620af77fff2728b8eb4222b62120ee224ce53392cf31/src/freetype.zig /home/runner/work/mach-editor/mach-editor/zig-cache/o/456c41d295e8958a5db932bc3f50e098/libfreetype.a /home/runner/work/mach-editor/mach-editor/zig-cache/o/008d4a2c52e76a475fe74c5e967c0b93/libharfbuzz.a -I /home/runner/work/mach-editor/mach-editor/zig-cache/i/609ca7687bbcd3221945b245a5e5ddfb/include -I /home/runner/work/mach-editor/mach-editor/zig-cache/i/df3b247d41f1932d5e5f2986d461512d/include --dep freetype=mach-freetype --mod mach-harfbuzz /home/runner/.cache/zig/p/12205faaaaf547019f0763ac620af77fff2728b8eb4222b62120ee224ce53392cf31/src/harfbuzz.zig --mod sysjs /home/runner/.cache/zig/p/1220db6845ce34743ae2a1ab0222efc942496adde2736c20e3443d4fde4ef64b11b9/src/main.zig --mod font-assets /home/runner/.cache/zig/p/12202039304f0603a9706105788e450fd4f901c3e20eca28a52a2173879b14c606c7/main.zig --mod objc /home/runner/.cache/zig/p/12204073b48a4f3cf7e4dcc3502690eee77fa1805b4aa5cb5e2ed67eed184b8a8371/src/main.zig /home/runner/work/mach-editor/mach-editor/zig-cache/o/03b0909db745549fd9e13cd785540c93/libbasisu.a /home/runner/work/mach-editor/mach-editor/zig-cache/o/bb7cf009de36c0a922285c2204ea5b55/libbrotli.a /home/runner/work/mach-editor/mach-editor/zig-cache/o/456c41d295e8958a5db932bc3f50e098/libfreetype.a -framework Foundation -framework Metal -framework CoreGraphics -framework IOKit -framework IOSurface -framework QuartzCore -framework CoreFoundation -framework CoreImage -framework CoreVideo -framework AudioToolbox -framework CoreAudio -framework CFNetwork -framework ApplicationServices -framework ColorSync -framework CoreText -framework ImageIO -framework AppKit -framework CoreServices -lc++ -lc --cache-dir /home/runner/work/mach-editor/mach-editor/zig-cache --global-cache-dir /home/runner/.cache/zig --name mach -fno-lto 
```

**Comment by slimsag** [comment]
@kubkon thanks for your help and patience, here's a minimal reproduction: https://github.com/slimsag/tmp-zig-cc-bug

on an aarch64-macos host, builds as expected:

```
% git clone https://github.com/slimsag/tmp-zig-cc-bug
% cd tmp-zig-cc-bug/
% zig build
```

on an aarch64-macos host, cross-compilation fails:

```
% git clone https://github.com/slimsag/tmp-zig-cc-bug
% cd tmp-zig-cc-bug/
% zig build -Dtarget=aarch64-macos
install
└─ install tmp-zig-cc-bug
   └─ zig build-exe tmp-zig-cc-bug Debug aarch64-macos 2 errors
mach-glfw/src/main.zig:4:20: error: C import failed
    const native = @cImport({
                   ^~~~~~~~
src/main.zig:5:34: note: called from here
    const ns_window = glfw.Native(.{}).getCocoaWindow();
                      ~~~~~~~~~~~^~~~~
referenced by:
    callMain: /Users/slimsag/zig/0.12.0-dev.2063+804cee3b9/files/lib/std/start.zig:585:32
    initEventLoopAndCallMain: /Users/slimsag/zig/0.12.0-dev.2063+804cee3b9/files/lib/std/start.zig:519:34
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
/Volumes/data/hexops/tmp-zig-cc-bug/xcode-frameworks/Frameworks/Security.framework/Headers/oids.h:35:10: error: 'libDER/DERItem.h' file not found
#include <libDER/DERItem.h>
         ^
error: the following command failed with 2 compilation errors:
/Users/slimsag/zig/0.12.0-dev.2063+804cee3b9/files/zig build-exe -ODebug -target aarch64-macos -mcpu baseline -iframework /Volumes/data/hexops/tmp-zig-cc-bug/xcode-frameworks/Frameworks -isystem /Volumes/data/hexops/tmp-zig-cc-bug/xcode-frameworks/include -L /Volumes/data/hexops/tmp-zig-cc-bug/xcode-frameworks/lib --dep mach-glfw --mod root /Volumes/data/hexops/tmp-zig-cc-bug/src/main.zig /Volumes/data/hexops/tmp-zig-cc-bug/zig-cache/o/9fa8cdc6201d47666ae99e9641032241/libglfw.a -I /Volumes/data/hexops/tmp-zig-cc-bug/zig-cache/i/575ceedf2b545b4b7c8e5edb5e37b4ae/include --mod mach-glfw /Volumes/data/hexops/tmp-zig-cc-bug/mach-glfw/src/main.zig -lobjc -framework CFNetwork -framework ApplicationServices -framework ColorSync -framework CoreText -framework ImageIO -framework IOKit -framework CoreFoundation -framework AppKit -framework CoreServices -framework CoreGraphics -framework Foundation -framework Metal -lc --cache-dir /Volumes/data/hexops/tmp-zig-cc-bug/zig-cache --global-cache-dir /Users/slimsag/.cache/zig --name tmp-zig-cc-bug --listen=-
Build Summary: 6/9 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install tmp-zig-cc-bug transitive failure
   └─ zig build-exe tmp-zig-cc-bug Debug aarch64-macos 2 errors
error: the following build command failed with exit code 1:
/Volumes/data/hexops/tmp-zig-cc-bug/zig-cache/o/d5e965677b551da2e476f45c69c7ffdc/build /Users/slimsag/zig/0.12.0-dev.2063+804cee3b9/files/zig /Volumes/data/hexops/tmp-zig-cc-bug /Volumes/data/hexops/tmp-zig-cc-bug/zig-cache /Users/slimsag/.cache/zig --seed 0xc35427f9 -Dtarget=aarch64-macos
```

Note how it failed to locate the header included by Security.framework's own header:

```
/Volumes/data/hexops/tmp-zig-cc-bug/xcode-frameworks/Frameworks/Security.framework/Headers/oids.h:35:10: error: 'libDER/DERItem.h' file not found
#include <libDER/DERItem.h>
         ^
```

And note how the failing command has `-isystem /Volumes/data/hexops/tmp-zig-cc-bug/xcode-frameworks/include`, and note that header exists there:

```
file /Volumes/data/hexops/tmp-zig-cc-bug/xcode-frameworks/include/libDER/DERItem.h
/Volumes/data/hexops/tmp-zig-cc-bug/xcode-frameworks/include/libDER/DERItem.h: c program text, ASCII text
```

on a aarch64-linux host, `zig build -Dtarget=aarch64-macos` fails identically.

**Comment by kubkon** [comment]
With the minimal repro that @slimsag provided, I see that we are failing to correctly route `cc_argv` to `clang`. What we get are `-isystem /Users/jakubkonka/dev/zig/build/stage4/lib/zig/include -isystem /Users/jakubkonka/dev/zig/build/stage4/lib/zig/libc/include/any-macos-any` for system headers and for user passed headers `-I /Users/jakubkonka/dev/examples/tmp-zig-cc-bug/zig-cache/i/<hash value>/include`, while for frameworks we get `-F /Users/jakubkonka/dev/examples/tmp-zig-cc-bugs/xcode-frameworks/Frameworks`. In the former, we are missing one include namely `-isystem /Users/jakubkonka/dev/examples/tmp-zig-cc-bugs/xcode-frameworks/include`, while in the latter case (for frameworks) we have substituted `-iframework` for `-F.

If we apply this patch, it works, but I will admit I do not fully understand what an actual fix would be:

```diff
diff --git a/src/main.zig b/src/main.zig
index 8eef42698d..ea08e32852 100644
--- a/src/main.zig
+++ b/src/main.zig
@@ -7834,7 +7834,8 @@ fn handleModArg(
                 .root_src_path = "",
             };
         },
-        .cc_argv = try cc_argv.toOwnedSlice(arena),
+        // .cc_argv = try cc_argv.toOwnedSlice(arena),
+        .cc_argv = try arena.dupe([]const u8, cc_argv.items),
         .inherited = mod_opts.*,
         .target_arch_os_abi = target_arch_os_abi.*,
         .target_mcpu = target_mcpu.*,
@@ -7845,7 +7846,8 @@ fn handleModArg(
         .rc_source_files_start = rc_source_files_owner_index.*,
         .rc_source_files_end = create_module.rc_source_files.items.len,
     };
-    cssan.reset();
+    _ = cssan;
+    // cssan.reset();
     mod_opts.* = .{};
     target_arch_os_abi.* = null;
     target_mcpu.* = null;
```

cc @andrewrk

**Comment by andrewrk** [comment]
breaking down that command, let me explain how the new per-module settings work:

```
/Users/slimsag/zig/0.12.0-dev.2063+804cee3b9/files/zig build-exe
-ODebug
-target aarch64-macos
-mcpu baseline
-iframework /Volumes/data/hexops/tmp-zig-cc-bug/xcode-frameworks/Frameworks
-isystem /Volumes/data/hexops/tmp-zig-cc-bug/xcode-frameworks/include
-L /Volumes/data/hexops/tmp-zig-cc-bug/xcode-frameworks/lib
--dep mach-glfw
--mod root /Volumes/data/hexops/tmp-zig-cc-bug/src/main.zig /Volumes/data/hexops/tmp-zig-cc-bug/zig-cache/o/9fa8cdc6201d47666ae99e9641032241/libglfw.a
```

We have created a root module with the settings above it. The optimization mode, target, `-iframework`, and `-isystem` arguments are all specific to the root module. Optimization mode and target are inherited by the other modules that follow, however, `-iframework` and `-isystem` arguments are not inherited.

```
-I /Volumes/data/hexops/tmp-zig-cc-bug/zig-cache/i/575ceedf2b545b4b7c8e5edb5e37b4ae/include
--mod mach-glfw /Volumes/data/hexops/tmp-zig-cc-bug/mach-glfw/src/main.zig
```

The `mach-glfw` module has this one include path and no others.

```
-lobjc
-framework CFNetwork
-framework ApplicationServices
-framework ColorSync
-framework CoreText
-framework ImageIO
-framework IOKit
-framework CoreFoundation
-framework AppKit
-framework CoreServices
-framework CoreGraphics
-framework Foundation
-framework Metal
-lc
--cache-dir /Volumes/data/hexops/tmp-zig-cc-bug/zig-cache
--global-cache-dir /Users/slimsag/.cache/zig
--name tmp-zig-cc-bug
--listen=-
```

These remaining arguments are global settings.

So it looks like this is actually working as designed. The module that does `@cImport` is the module that needs the include directory added to it. Looking at the repro (thanks for putting that together), I see that the glfw package is basically trying to declare a "native include path dependency" on xcode_frameworks. It looks to me like it should be reasonable to move that dependency over to mach-glfw, where the module that does `@cImport` is created.

**Comment by slimsag** [comment]
Thank you @andrewrk and @kubkon ! I very much appreciate your help - you're totally correct, I see the issue now.

@Cloudef I was able to verify/fix the issue according to andrew's comment above (https://github.com/slimsag/tmp-zig-cc-bug/commit/8d7461ea3fe0ebdbbd2d4498b5f97c092d2086a0) next up will be to translate this to our actual Mach projects.

I think this can be closed now. Thank you for your help again!

**Comment by andrewrk** [comment]
Great, glad to be of service.
