### ISSUE TITLE
Native build fails on Ubuntu/riscv64

### ISSUE THREAD

**Issue by pushkarnk** [ziglang/zig#24239]
### Zig Version

0.15.0-dev.767+201c0f54a

### Steps to Reproduce and Observed Behavior

A Debian [package build](https://launchpadlibrarian.net/799904268/buildlog_ubuntu-questing-riscv64.zig0.14_0.14.1+dfsg-0ubuntu2_BUILDING.txt.gz) of zig consistently fails on Ubuntu/riscv64. 

I also ran a native cmake build on a Ubuntu 25.04, on a StarFive VisionFive 2 board, and consistently see this failure:

```
[100%] Building stage3
install
└─ install zig
   └─ compile exe zig Debug native-native 1 errors
lib/std/debug.zig:443:28: error: expected optional type, found 'void'
            it.unwind_state.?.dwarf_context.pc;
            ~~~~~~~~~~~~~~~^~
referenced by:
    dumpStackTrace: src/crash_report.zig:271:45
    reportStack: src/crash_report.zig:420:39
    14 reference(s) hidden; use '-freference-trace=16' to see all references
```
The full build log is [here](https://gist.github.com/pushkarnk/346d6a4b953e719c2d036c9af51c1df4).

### Expected Behavior

Native builds should ideally pass on Linux/Ubuntu riscv64.

**Comment by alexrp** [comment]
I'm currently in the process of obtaining RISC-V hardware for CI, so I'll be taking a look at this soon.
