### ISSUE TITLE
`comptime try` no longer seems to work

### ISSUE THREAD

**Issue by squeek502** [ziglang/zig#16176]
### Zig Version

0.11.0-dev.3786+8dcb4a3dc

### Steps to Reproduce and Observed Behavior

This code compiles with Zig 0.10.1:

```zig
test {
    comptime try doTheTest();
}

fn doTheTest() !void {
    return error.Blah;
}
```

but now fails to compile with:

```
comptime-try.zig:4:9: error: function called at runtime cannot return value at comptime
        try doTheTest();
        ^~~~~~~~~~~~~~~
```

This workaround fixes it:

```zig
test {
    try comptime doTheTest();
}

fn doTheTest() !void {
    return error.Blah;
}
```

This workaround was applied globally in https://github.com/ziglang/zig/commit/d884d7050e061c620324aaaabfba507e08cb40f4 for https://github.com/ziglang/zig/pull/15957 but it seems more likely to me that this is a bug than intentional behavior.

This version which also hits the compile error seems to me like it should work, or at least it makes it more obvious that the 'function called at runtime' part of the compile error doesn't make much sense:

```
test {
    comptime {
        try doTheTest();
    }
}

fn doTheTest() !void {
    return error.Blah;
}
```

In https://github.com/ziglang/zig/pull/16100 I ran into this same thing, but somehow created a situation where the compile error would only show up when compiling for a big endian target:

https://github.com/ziglang/zig/pull/16100/commits/260539d2005039d9801d5a10a837b13d34aa479d

### Expected Behavior

The test to compile

**Comment by mlugg** [comment]
This is intentional, but the reasoning is a bit subtle. Let's first look at something else that used to work:
`comptime return x`
This expression, in a runtime function, doesn't actually make sense. You can't `return` from the function at comptime - it's not a comptime call, so that'd be runtime control flow at comptime! When you write that, what you really want is `return comptime x`. This change came as a result of my work on making function-scope `comptime` blocks work correctly.

Now, let's desugar `comptime try f()`:
```zig
comptime if (f()) |x| x else |e| return e;
```
This has the same problem - we're `return`ing from a `comptime` scope!

Note that this problem only actually comes up in the error case. Since Zig only analyzes the taken branch of comptime-known conditionals, we don't compile error if the function doesn't return an error, which is admittedly somewhat confusing.

The fix you want here is to just use `try comptime` rather than `comptime try`. That way, the control flow itself happens at runtime, but the function evaluation at comptime.

**Comment by rohlem** [comment]
> Since Zig only analyzes the taken branch of comptime-known conditionals, we don't compile error if the function doesn't return an error

Would it maybe make sense to change this specifically for `try` / the `if` generated from a `try`?
Or can we come up with an example of where this is actually helpful, and doesn't just hide invalid code (like `comptime try`, which iiuc should always be `try comptime`).

**Comment by squeek502** [comment]
@mlugg thanks, that makes perfect sense.

Am I wrong in thinking the error could be changed to just `cannot return value at comptime` or maybe something like `cannot return in comptime scope`? In other words, can the `function called at runtime` part of the error ever be relevant? To me, it obfuscates the real problem and is especially confusing in the `test` block case since the 'function called at runtime' is actually the generated test function unless I'm misunderstanding.

**Comment by mlugg** [comment]
It's absolutely not true that you `cannot return value at comptime` in general: the fact that the function is run at runtime is important. For instance, this is fine:
```zig
fn f() u32 {
    comptime return 10;
}
const x = f(); // global scope so comptime call
```
A bit silly, sure, but `return` from a `comptime` scope is totally valid if the function is called at comptime. It's actually also valid for `inline` functions, regardless: which may seem a little funny, but makes some sense, since "returning" from a comptime function is really more like breaking from a block.

However, there's definitely potential to improve the error here. Perhaps something like this would be better:
```
[on the bad return]: error: cannot return from comptime scope here
[on the function def]: note: function called at runtime must return at runtime
```
It also might be good to look into making `try` do this all the time, since currently the issue only manifests itself in error cases, which is a little confusing.
