### ISSUE TITLE
non `callconv(.C)` function pointers no longer allowed in extern contexts

### ISSUE THREAD

**Issue by xdBronch** [ziglang/zig#19921]
### Zig Version

0.12

### Steps to Reproduce and Observed Behavior

```zig
const T = extern struct {
    f: *const fn () void,
};

export fn f(_: *const fn () void) void {}

comptime {
    _ = @as(T, undefined);
}
```
```
d.zig:5:13: error: parameter of type '*const fn () void' not allowed in function with calling convention 'C'
export fn f(_: *const fn () void) void {}
            ^~~~~~~~~~~~~~~~~~~~
d.zig:5:13: note: extern function must specify calling convention
d.zig:2:8: error: extern structs cannot contain fields of type '*const fn () void'
    f: *const fn () void,
       ^~~~~~~~~~~~~~~~~
d.zig:2:8: note: extern function must specify calling convention
```
this worked in 0.11, caused by #17509 see https://github.com/ziglang/zig/issues/17468#issuecomment-2037278370

### Expected Behavior

no error

**Comment by Pyrolistical** [comment]
but without a callconv for extern fn you run into https://github.com/ziglang/zig/issues/19841

**Comment by xdBronch** [comment]
its not an unspecified callconv for extern fns, its a pointer to an unspecified callconv fn being passed to a `callconv(.C)` function. it would be seen as an opaque pointer on the C side

**Comment by Pyrolistical** [comment]
On the line `export fn f(_: *const fn () void) void {}`, `fn f` does not have a callconv, so it is unspecified. The function pointer param is not the issue.

For
```

**Comment by xdBronch** [comment]
> On the line export fn f(_: *const fn () void) void {}, fn f does not have a callconv, so it is unspecified. The function pointer param is not the issue.

the `export` implies the C calling convention, it is not unspecified. you arent allowed to export unspecified functions like that
```zig
comptime {
    @compileLog(@typeInfo(@TypeOf(exported)).Fn.calling_convention);
    @compileLog(@typeInfo(@TypeOf(not_exported)).Fn.calling_convention);
}

export fn exported() void {}
fn not_exported() void {}
```
```
Compile Log Output:
@as(builtin.CallingConvention, .C)
@as(builtin.CallingConvention, .Unspecified)
```
> The function pointer needs a callconv or else how would zig know what to do when you write:

no callconv means zigs callconv, the point is to be callable on the zig side but opaque on the C side

**Comment by xdBronch** [comment]
thats exactly what im saying, there isnt
