### ISSUE TITLE
Inline assembly compilation error on linux

### ISSUE THREAD

**Issue by eddineimad0** [ziglang/zig#25391]
### Zig Version

0.15.1

### Steps to Reproduce and Observed Behavior

The following code compiles on *x86 windows* os but doesn't compile on *x86 linux*.

```zig
const std = @import("std");
const builtin = @import("builtin");
const start = @import("start");

pub fn main() !void {
    if (x86CPUIdCapable()) {
        // Prints to stderr, ignoring potential errors.
        std.debug.print("All your {s} are belong to us.\n", .{"codebase"});
        try start.bufferedPrint();
    }
}

fn x86CPUIdCapable() bool {
    switch (builtin.cpu.arch) {
        .x86 => {
            return asm volatile (
                \\ pushfl
                \\ popl %eax
                \\ movl %eax, %ecx
                \\ xorl $0x200000, %eax    # flip bit 21
                \\ pushl %eax
                \\ popfl
                \\ pushfl
                \\ popl %eax
                \\ xorl %ecx, %eax
                \\ jnz set_true
                \\ xorl %eax, %eax
                \\ jmp exit
                \\set_true:
                \\ movl $1, %eax
                \\exit:
                : [ret] "={eax}" (-> bool),
                :
                : .{ .eax = true, .ecx = true });
        },
        .x86_64 => {
            return asm volatile (
                \\ pushfq
                \\ popq %rax
                \\ movq %rax, %rcx
                \\ xorl $0x200000, %eax    # flip bit 21
                \\ pushq %rax
                \\ popfq
                \\ pushfq
                \\ popq %rax
                \\ xorl %ecx, %eax
                \\ jnz set_true
                \\ xorq %rax, %rax
                \\ jmp exit
                \\set_true:
                \\ movq $1, %rax
                \\exit:
                : [ret] "={rax}" (-> bool),
                :
                : .{ .rax = true, .rcx = true });
        },
        else => false,
    }
}

```

the compiler return the following error `src/main.zig:13:1: error: invalid operand: '%rax'

fn x86CPUIdCapable() bool {`

### Expected Behavior

The function should compile with no error on linux.

**Comment by alexrp** [comment]
You need to use double `%`, i.e. `%%rax` etc.

See the syntax breakdown: https://ziglang.org/documentation/master/#Assembly

**Comment by eddineimad0** [comment]
thank you that does fix it, however the same code (using single % for registers) still compiles and works on windows using zig 0.15.1 compiler, which i assume to be a bug.
