### ISSUE TITLE
sendto is declared as coming from libc on Windows instead of ws2_32

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#9971]
### Steps to Reproduce

bug.zig:
```zig
const std = @import("std");

pub fn main() !void {
    const msg = &[_]u8 { 0 };
    const send_addr = std.net.Address.parseIp4("255.255.255.255", 1234) catch unreachable;    
    _ = try std.os.sendto(std.os.windows.ws2_32.INVALID_SOCKET, msg, 0, &send_addr.any, send_addr.getOsSockLen());
}
```
```batch
> zig build-exe bug.zig
D:\tools\zig\0.9.0-dev.1387+6f30c8c09\files\lib\std\os.zig:5260:26: error: dependency on libc must be explicitly specified in the build command
        const rc = system.sendto(sockfd, buf.ptr, buf.len, flags, dest_addr, addrlen);
                         ^
D:\tools\zig\0.9.0-dev.1387+6f30c8c09\files\lib\std\os.zig:5262:37: note: referenced here
            if (rc == windows.ws2_32.SOCKET_ERROR) {
                                    ^
D:\tools\zig\0.9.0-dev.1387+6f30c8c09\files\lib\std\os\windows\ws2_32.zig:1845:51: note: referenced here
pub extern "ws2_32" fn WSAGetLastError() callconv(WINAPI) WinsockError;
                                                  ^
D:\tools\zig\0.9.0-dev.1387+6f30c8c09\files\lib\std\os\windows\ws2_32.zig:1845:59: note: referenced here
pub extern "ws2_32" fn WSAGetLastError() callconv(WINAPI) WinsockError;
                                                          ^
D:\tools\zig\0.9.0-dev.1387+6f30c8c09\files\lib\std\os.zig:5263:39: note: referenced here
                switch (windows.ws2_32.WSAGetLastError()) {
                                      ^
D:\tools\zig\0.9.0-dev.1387+6f30c8c09\files\lib\std\os.zig:5283:49: note: referenced here
                    else => |err| return windows.unexpectedWSAError(err),
                                                ^
D:\tools\zig\0.9.0-dev.1387+6f30c8c09\files\lib\std\os.zig:5258:21: note: referenced here
) SendToError!usize {
```

### Expected Behavior

The example should compile.  This example works on zig version 0.8.1.  I believe this was broken by this commit: 7884d84315f4080bfe429d3e29f7ebedf9f3f6  in the file `lib/std/os.zig` with the following change:

```patch
/// When not linking libc, it is the OS-specific system interface.
 pub const system = if (@hasDecl(root, "os") and root.os != @This())
     root.os.system
-else if (builtin.link_libc)
+else if (builtin.link_libc or is_windows)
    std.c
 else switch (builtin.os.tag) {
```

`std.os.sendto` calls `system.sendto` and this change routed `system.sendto` to `std.c` instead of `std.os.windows` where the correct declaration exists on windows.  So this is probably a problem for alot more functions, but this is the first one I found and noticed.  I don't quite understand why this change was made so I don't know whether the fix is to undo this particular line of the commit or if there's more to what's going on here.

### Actual Behavior

Zig thinks `sendto` is defined in `libc` on Windows instead of `ws2_32` where it actually lives.

**Comment by Sirius902** [comment]
I would like to add that due to this bug linking libc and using the `std.os` socket functions will cause them to return `4294967295` instead of `-1` since `std.os.windows.recvfrom` returns an `i32` but `std.c.recvfrom` returns an `isize`. It seems that `std.c.recvfrom` somehow calls `std.os.windows.recvfrom` with an incorrect function prototype and widens the `i32` to an `isize` without a proper sign extension.

**Comment by andrewrk** [comment]
The fix is extremely straightforward: #15225

**Comment by mzet-** [comment]
Similar fix should be also applied to `recvfrom` (https://github.com/ziglang/zig/blob/5af89b3dccf7ee375f68e9cd3ee4980fef89e38f/lib/std/os.zig#L6612).
