### ISSUE TITLE
io.FixedBufferStream doesn't error.EndOfStream at comptime

### ISSUE THREAD

**Issue by travisstaloch** [ziglang/zig#17926]
### Zig Version

0.12.0-dev.1381+61861ef39

### Steps to Reproduce and Observed Behavior

As noted in comments when given an empty string the test passes.  But any non-empty string causes the while loop to loop 248 times and then `error: evaluation exceeded 1000 backwards branches`.  So it seems like the fbs is never advancing.

```zig
// /tmp/tmp.zig
const std = @import("std");

test {
    comptime {
        // const buf = ""; // empty string allows the test to run and pass
        const buf = "a"; // non-empty causes the test to fail with:
        //                  error: evaluation exceeded 1000 backwards branches
        var fbs = std.io.fixedBufferStream(buf);
        const reader = fbs.reader();
        var i: usize = 0;
        while (true) : (i += 1) {
            // inline while (true) : (i += 1) { // same result with inline while
            const byte = reader.readByte() catch |e| switch (e) {
                error.EndOfStream => break,
                else => return e,
            };
            _ = byte;
            // @compileLog(byte, i); // if uncommented, this logs
            //                          '@as(u8, 97), i' 248 times showing i=0..247
        }
        try std.testing.expectEqual(buf.len, i);
    }
}
```

```console
$ zig test /tmp/tmp.zig
/home/travis/dev/zig/zig/download/0.12.0-dev.1381+61861ef39/files/lib/std/io.zig:243:39: error: evaluation exceeded 1000 backwards branches
            return @errorCast(self.any().readByte());
                              ~~~~~~~~^~
/home/travis/dev/zig/zig/download/0.12.0-dev.1381+61861ef39/files/lib/std/io.zig:243:39: note: use @setEvalBranchQuota() to raise the branch limit from 1000
/tmp/tmp.zig:13:41: note: called from here
            const byte = reader.readByte() catch |e| switch (e) {

```

I discovered this while trying to fix ci errors in [this project](https://github.com/travisstaloch/case/).  This first started failing [around 2 weeks ago](https://github.com/travisstaloch/case/actions) with no real changes to the project since [sept 17](https://github.com/travisstaloch/case/commits/main).

### Expected Behavior

It should be possible to catch the error.EndOfStream error at comptime and the test should pass.

**Comment by ianprime0509** [comment]
This is almost certainly caused by #17761. As you suspected, the `FixedBufferStream` is not being advanced past the first read, since all subsequent `readByte` calls are being incorrectly memoized. Adjusted example showing applicability to `readByte`:

```zig
const std = @import("std");

fn t() !void {
    const buf = [_]u8{ 1, 2 };
    var buf_stream = std.io.fixedBufferStream(&buf);
    const reader = buf_stream.reader();
    const v1 = try reader.readByte();
    const v2 = try reader.readByte();
    @compileLog(v1);
    @compileLog(v2);
    try std.testing.expect(v1 == 1);
    try std.testing.expect(v2 == 2);
}

test {
    try comptime t();
}
```

Compile log output:

```
@as(u8, 1)
@as(u8, 1)
```

**Comment by travisstaloch** [comment]
Thanks for the reduction and pointing out the issue.  It does seem like the same problem - readByte() being memoized.  Closing as duplicate of #17761.
