### ISSUE TITLE
@enumFromInt not working on comptime negative 0

### ISSUE THREAD

**Issue by AndrewKraevskii** [ziglang/zig#25221]
### Zig Version

0.16.0-dev.229+bfda12efc

### Steps to Reproduce and Observed Behavior

```zig
const Sign = enum(i2) {
    @"-1" = -1,
    @"0" = 0,
    @"1" = 1,
};

test {
    _ = comptime @as(Sign, @enumFromInt(@as(i2, -1) * @as(i2, 0)));
}
```
Run `zig test main.zig` results in following compile error:
```sh
main.zig:8:28: error: enum 'reducible.Sign' has no tag with value '0'
    _ = comptime @as(Sign, @enumFromInt(@as(i2, -1) * @as(i2, 0)));
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.zig:1:14: note: enum declared here
const Sign = enum(i2) {
             ^~~~

```

### Expected Behavior

I expect it to compile successfully. It works on 0.14.1
