### ISSUE TITLE
std.math.min broken for floats

### ISSUE THREAD

**Issue by dbandstra** [ziglang/zig#3044]
Broken by commit 0bf6796b7.

```zig
const std = @import("std");

pub fn main() void {
    _ = std.math.min(0.0, 1.0);
}
```
Output:
```
/home/dbandstra/zig/build/lib/zig/std/math.zig:261:22: error: integer value 0 cannot be implicitly casted to type 'comptime_float'
    return @typeOf(A(0) + B(0));
                     ^
/home/dbandstra/zig/build/lib/zig/std/math.zig:266:31: note: called from here
pub fn min(x: var, y: var) Min(@typeOf(x), @typeOf(y)) {
                              ^
/home/dbandstra/zig/build/lib/zig/std/math.zig:266:31: note: called from here
pub fn min(x: var, y: var) Min(@typeOf(x), @typeOf(y)) {
                              ^
```

This would be fixed by adding the following three lines to the `Min` function in std `math.zig`

```zig
/// Given two types, returns the smallest one which is capable of holding the
/// full range of the minimum value.
pub fn Min(comptime A: type, comptime B: type) type {
    switch (@typeInfo(A)) {
        .Int => |a_info| switch (@typeInfo(B)) {
            .Int => |b_info| if (!a_info.is_signed and !b_info.is_signed) {
                if (a_info.bits < b_info.bits) {
                    return A;
                } else {
                    return B;
                }
            },
            else => {},
        },
        .Float, .ComptimeFloat => {          // <---- ADDED
            return @typeOf(A(0.0) + B(0.0)); // <---- ADDED
        },                                   // <---- ADDED
        else => {},
    }
    return @typeOf(A(0) + B(0));
}
```

The weird thing is this manifested as a compiler assertion in one of my larger projects. Check out https://github.com/dbandstra/zang/tree/ba1a07b6daa4096c2da95115ce9d8d18da0bea24 and run `zig build play` and you get this:

```
unreachable: /home/dbandstra/zig/src/analyze.cpp:handle_is_ptr:4096
```

It's caused by the `std.math.min` calls in https://github.com/dbandstra/zang/blob/ba1a07b6daa4096c2da95115ce9d8d18da0bea24/src/zang/mod_filter.zig

edit: I'd like to take the opportunity to ask why these functions can't just take a type argument?

**Comment by andrewrk** [comment]
sorry about that :grimacing: 
> edit: I'd like to take the opportunity to ask why these functions can't just take a type argument?

The idea is to improve this use case: https://github.com/ziglang/zig/blob/4bd4c5e06d13c35a70d0207b730fb67b83ff6363/std/os/windows.zig#L146

Here there is no `@intCast` needed.

**Comment by andrewrk** [comment]
I pushed 1b83ee78a48a64bef28f12b7b2e263074f88b6b6, allowing `comptime_int` to implicit cast to `comptime_float`. This is an independent improvement, which also fixes this regression.

As for the assertion, feel free to make a new issue if you're interested in prioritizing that getting fixed.

**Comment by dbandstra** [comment]
Thanks, that makes sense.

The assertion goes away with this fix. It seemed to be caused by the same thing, interacting with something else in my codebase I guess. I'll try to replicate it by copy pasting the old min implementation into my project.
