### PR TITLE
do not enforce function parameters to be marked comptime if only called at comptime

### LINKED ISSUE #1383: Allow comptime only types to be passed to none comptime parameters in comptime blocks
Currently, we can't really use generic data types with comptime types such as `comptime_int`, `type` and others:

```
fn IntPair(comptime T: type) type {
    return struct {
        const Self = this;

        a: T,
        b: T,

        fn add(a: Self, b: Self) Self {
            return Self{
                .a = a.a + b.a,
                .b = a.b + b.b,
            };
        }
    };
}

comptime {
    const comptime_pair = IntPair(comptime_int){
        .a = 123,
        .b = 11111,
    };

    const times_two = comptime_pair.add(comptime_pair);
}
```

```
test.zig:8:19: error: parameter of type 'IntPair(comptime_int)' must be declared comptime
        fn add(a: Self, b: Self) Self {
```

### LINKED ISSUE #16454: Regression: `must be declared comptime` error happens in comptime scope
### Zig Version

0.11.0-dev.4006+bf827d0b5

### Steps to Reproduce and Observed Behavior

Code

```zig
const std = @import("std");
pub fn getExternList(comptime Type: type) []const []const u8 {
    return comptime &brk: {
        const Sorder = struct {
            abc: type,
            pub fn lessThan(comptime _: @This(), lhs: []const u8, rhs: []const u8) bool {
                return std.ascii.orderIgnoreCase(lhs, rhs) == std.math.Order.lt;
            }
        };
        var extern_list = Type.Extern;
        std.sort.block([]const u8, &extern_list, Sorder{
            .abc = Type,
        }, Sorder.lessThan);
        break :brk extern_list;
    };
}
test {
    _ = getExternList(struct {
        pub const Extern = [_][]const u8{ "hey", "hi", "yooo" };
    })[0];
}
```

Run

```bash
zig test repro.zig
```

Error:

```zig
/Users/jarred/zig/0.11.0-dev.4006+bf827d0b5/files/lib/std/sort/block.zig:107:21: error: parameter of type 'repro.getExternList__anon_965__struct_1749' must be declared comptime
        fn lessThan(ctx: @TypeOf(context), lhs: T, rhs: T) bool {
                    ^~~~~~~~~~~~~~~~~~~~~
/Users/jarred/Desktop/repro.zig:5:18: note: struct requires comptime because of this field
            abc: type,
                 ^~~~
/Users/jarred/Desktop/repro.zig:5:18: note: types are not available at runtime
            abc: type,
                 ^~~~
/Users/jarred/Desktop/repro.zig:4:24: note: struct declared here
        const Sorder = struct {
                       ^~~~~~
referenced by:
    block: /Users/jarred/zig/0.11.0-dev.4006+bf827d0b5/files/lib/std/sort/block.zig:113:6
    block: /Users/jarred/zig/0.11.0-dev.4006+bf827d0b5/files/lib/std/sort.zig:7:44
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

### Expected Behavior

The test should pass as it is only called at comptime 

This worked in `0.11.0-dev.3771+128fd7dd0`:
> All 1 tests passed.

### LINKED ISSUE #18321: ComptimeStringMap fails with comptime-only value type
### Zig Version

0.12.0-dev.1802+56deb5b05

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

const extensions = std.ComptimeStringMap(type, .{
    .{ "bmp", struct {
        pub const foo = 1;
    } },
    .{ "qoi", struct {
        pub const foo = 2;
    } },
    .{ "png", struct {
        pub const foo = 3;
    } },
    .{ "jpg", struct {
        pub const foo = 4;
    } },
    .{ "gif", struct {
        pub const foo = 5;
    } },
});

test {
    const T = comptime extensions.get("png").?;
    try std.testing.expect(T.foo == 3);
}
```

```
/home/meghan/src/zig/lib/std/comptime_string_map.zig:64:29: error: parameter of type 'comptime_string_map.ComptimeStringMapWithEql__struct_965' must be declared comptime
            pub fn lessThan(ctx: @This(), a: usize, b: usize) bool {
                            ^~~~~~~~~~~~
/home/meghan/src/zig/lib/std/comptime_string_map.zig:62:18: note: struct requires comptime because of this field
            kvs: []KV,
                 ^~~~
/home/meghan/src/zig/lib/std/comptime_string_map.zig:50:20: note: struct requires comptime because of this field
            value: V,
                   ^
/home/meghan/src/zig/lib/std/comptime_string_map.zig:50:20: note: types are not available at runtime
            value: V,
                   ^
/home/meghan/src/zig/lib/std/comptime_string_map.zig:61:29: note: struct declared here
        const SortContext = struct {
                            ^~~~~~
referenced by:
    insertionContext: /home/meghan/src/zig/lib/std/sort.zig:48:33
    pdqContext: /home/meghan/src/zig/lib/std/sort/pdq.zig:65:27
    pdqContext: /home/meghan/src/zig/lib/std/sort.zig:11:47
    sortUnstableContext: /home/meghan/src/zig/lib/std/mem.zig:586:13
    ComptimeStringMapWithEql: /home/meghan/src/zig/lib/std/comptime_string_map.zig:72:12
    ComptimeStringMap: /home/meghan/src/zig/lib/std/comptime_string_map.zig:14:12
    ComptimeStringMap: /home/meghan/src/zig/lib/std/std.zig:19:50
    extensions: test2.zig:3:23
    test_0: test2.zig:22:24
```

### Expected Behavior

all test passed

### PR DESCRIPTION
**Pull request by nektro**
Fixes #18321
Fixes #16454
Fixes #1383

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
nice

**Comment by whfuyn** [comment]
Provide an example here in case it helps:
```zig
const std = @import("std");
const EnumMap = std.EnumMap;

const Ty = enum(u8) {
    a,
    b,
};

const HANDLERS_MAP = EnumMap(Ty, fn () callconv(.Inline) void).init(.{
    .a = fa,
    .b = fb,
});

inline fn fa() void {
    std.debug.print("fa\n", .{});
}
inline fn fb() void {
    std.debug.print("fb\n", .{});
}

pub fn main() !void {
    const ty = Ty.b;
    HANDLERS_MAP.get(ty).?();
}
```
After adding each `comptime` as told by compiler:
```
lib/std/enums.zig:277:29: error: parameter of type 'enums.EnumFieldStruct(test.Ty,?fn () callconv(.Inline) void,null)' must be declared comptime
                pub fn init(init_values: EnumFieldStruct(E, ?V, @as(?V, null))) Self {
```
```
lib/std/enums.zig:1054:20: error: parameter of type 'enums.IndexedMap(enums.EnumIndexer(test.Ty),fn () callconv(.Inline) void,(function 'EnumMapExt'))' must be declared comptime
        pub fn get(self: Self, key: Key) ?Value {
```
```
lib/std/enums.zig:1054:51: error: function with comptime-only return type '?fn () callconv(.Inline) void' requires all parameters to be comptime
        pub fn get(comptime self: Self, key: Key) ?Value {
                                                  ^~~~~~
```
Successfully compiled.

**Comment by nektro** [comment]
yes, without this change using many structures with comptime-only types is impossible while making it so they can continue to work with runtime types as well

**Review by andrewrk — CHANGES_REQUESTED** [review]
Lacks a behavior test.

**Comment by nektro** [comment]
outside the one `lib/std/comptime_string_map.zig`, I should add one in `test/behavior/` as well?

**Comment by andrewrk** [comment]
Yes, the goal is for all behavior to be covered by behavior tests. Standard library tests are intended only to provide coverage for the standard library functionality; they are not double-purposed as coverage for the language itself.
