### ISSUE TITLE
`local variable is never mutated` regression for field and array accesses

### ISSUE THREAD

**Issue by squeek502** [ziglang/zig#25540]
### Zig Version

0.16.0-dev.699+529aa9f27

### Steps to Reproduce and Observed Behavior

I've [run into this](https://github.com/squeek502/implibinator/commit/fdedc06dc52d04a6f962b95faf519e8790934766) a few [times now](https://github.com/ziglang/zig/actions/runs/18425655647/job/52506472634) and thought I was going crazy. Locally, everything would be fine but CI would fail immediately with `local variable is never mutated`. One reproduction:

```zig
fn foo() void {
    var target_path_w: []const u8 = "foo";
    _ = target_path_w.len;
}
```

With `zig1`, it hits this error:
```
> zig1.exe ..\lib build-obj -ofmt=c -Mroot=test.zig
test.zig:2:9: error: local variable is never mutated
    var target_path_w: []const u8 = "foo";
        ^~~~~~~~~~~~~
test.zig:2:9: note: consider using 'const'
```

With a stage3 compiler, it does not:
```
> zig build-obj -ofmt=c -Mroot=test.zig
```

Note that it's not related to the function being unused or something like that. If you add a test block:

```zig
test "foo" {
    foo();
}
```
it passes:
```
> zig test test.zig
All 1 tests passed.
```

Somewhat surprisingly, `zig1` seems to have the more correct behavior, as in each case I've hit, the error seems applicable.

### Expected Behavior

`zig1` and the stage3 compiler to agree on when things are never mutated.

**Comment by squeek502** [comment]
This is actually https://github.com/ziglang/zig/pull/25154#pullrequestreview-3192048262, so it regressed in https://github.com/ziglang/zig/pull/25154 and zig1.wasm hasn't been updated since.

If there was a follow-up issue made, then this should be closed as a duplicate of that. If not, then I guess this can serve as that follow-up issue.

cc @mlugg

**Comment by mlugg** [comment]
Ah yes, thank you @squeek502; indeed I forgot to make that issue, so this can serve as it.

**Comment by mlugg** [comment]
Migrated to https://codeberg.org/ziglang/zig/issues/31049
