### ISSUE TITLE
Function pointer function arguments can't reference previous comptime arguments

### ISSUE THREAD

**Issue by ifreund** [ziglang/zig#12616]
### Zig Version

0.10.0-dev.3714+5696cc8ab

### Steps to Reproduce

```zig
fn foo(comptime T: type, callback: *const fn (user_data: T) void, data: T) void {
    callback(data);
}
test {
    _ = foo;
}
```

### Expected Behavior

I expect this code to compile, it is a pattern I use in [zig-wayland](https://github.com/ifreund/zig-wayland) and works with the stage1 compiler.

### Actual Behavior

```
/tmp/foo.zig:1:26: error: parameter of type '*const fn(anytype) void' must be declared comptime
fn foo(comptime T: type, callback: *const fn (user_data: T) void, data: T) void {
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Vexu** [comment]
I broke this in b55a5007faad1de054e86e00bfdc9a58e5fc4ff8, the problem is that stage2 has no way of distinguishing between
```zig
comptime T: type, callback: *const fn (user_data: T) void
```
and
```zig
comptime T: type, callback: *const fn (user_data: anytype) void
```
where the first one is OK and the second one should be a comptime only type.
