### ISSUE TITLE
Compilation error on stage2 with `@cImport` and SDL2

### ISSUE THREAD

**Issue by sagehane** [ziglang/zig#12737]
### Zig Version

0.10.0-dev.3871+b7d5582de

### Steps to Reproduce

Build/run a file using SDL2 without `-fstage1`.

Sample `test.zig` file with SDL2:
```zig
const c = @cImport(
    @cInclude("SDL2/SDL.h"),
);

comptime {
    _ = c;
}

pub fn main() void {}
```

### Notes
Reproduced on NixOS and Guix.
The Guix user who helped me test this bug couldn't reproduce it on `0.10.0-dev.3838+77f31ebbb`, which suggests its a regression.

I also couldn't reproduce this bug with Raylib, meaning the extent of this breakage isn't to all imported C libraries.

### Expected Behavior

It should behave the same as with stage1:
```sh-session
$ zig run test.zig -lc -lSDL2 -fstage1 && echo hi
hi
```

### Actual Behavior

```sh-session
$ zig run test.zig -lc -lSDL2
/home/<user>/.cache/zig/o/8e09ae690747d858ba9b2bca9e76ec36/cimport.zig:2271:5: error: redeclaration of '__mm_storeh_pi_struct'
pub const __mm_storeh_pi_struct = @compileError("cannot translate packed record union"); // /nix/store/ciigv5x04k16fyvqlwbwanknmngz6sly-zig-0.10.0-dev.3871+b7d5582de/lib/zig/include/xmmintrin.h:1948:10
~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/<user>/.cache/zig/o/8e09ae690747d858ba9b2bca9e76ec36/cimport.zig:2260:5: note: other declaration here
pub const __mm_storeh_pi_struct = @compileError("cannot translate packed record union"); // /nix/store/ciigv5x04k16fyvqlwbwanknmngz6sly-zig-0.10.0-dev.3871+b7d5582de/lib/zig/include/xmmintrin.h:1927:10
~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<omitted>
/home/<user>/.cache/zig/o/8e09ae690747d858ba9b2bca9e76ec36/cimport.zig:17994:18: error: use of undeclared identifier 'struct___storeu_i64'
    @ptrCast([*c]struct___storeu_i64, @alignCast(@import("std").meta.alignment([*c]struct___storeu_i64), __P_1)).*.__v = @bitCast(c_longlong, @as(c_ulonglong, __builtin_bswap64(@bitCast(c_ulong, @truncate(c_long, __D)))));
                 ^~~~~~~~~~~~~~~~~~~
test.zig:1:11: error: C import failed: AnalysisFail
const c = @cImport(
          ^~~~~~~~
```

**Comment by Vexu** [comment]
See #12733

**Comment by nektro** [comment]
that's different. the issue here is `error: redeclaration of '__mm_storeh_pi_struct'` and `error: use of undeclared identifier 'struct___storeu_i64'`

**Comment by michal-z** [comment]
I'm getting the same problem. This is a regression introduced by #12723

**Comment by igaryhe** [comment]
a workaround might be manually comment `#include "SDL_cpuinfo.h"` in `SDL.h`, only if you are not using these SIMD extension checking functions

**Comment by slimsag** [comment]
We also hit this in `mach/freetype`:

```
/Users/slimsag/Desktop/hexops/mach/libs/freetype/zig-cache/o/bb72da8deab15f11b164ed8d77d537bf/cimport.zig:766:39: error: use of undeclared identifier 'struct__OSUnalignedU16'
    return _OSSwapInt16(@intToPtr([*c]struct__OSUnalignedU16, @intCast(usize, @ptrToInt(_base)) +% _offset).*.__val);
                                      ^~~~~~~~~~~~~~~~~~~~~~
/Users/slimsag/Desktop/hexops/mach/libs/freetype/zig-cache/o/bb72da8deab15f11b164ed8d77d537bf/cimport.zig:771:39: error: use of undeclared identifier 'struct__OSUnalignedU32'
    return _OSSwapInt32(@intToPtr([*c]struct__OSUnalignedU32, @intCast(usize, @ptrToInt(_base)) +% _offset).*.__val);
                                      ^~~~~~~~~~~~~~~~~~~~~~
/Users/slimsag/Desktop/hexops/mach/libs/freetype/zig-cache/o/bb72da8deab15f11b164ed8d77d537bf/cimport.zig:776:39: error: use of undeclared identifier 'struct__OSUnalignedU64'
    return _OSSwapInt64(@intToPtr([*c]struct__OSUnalignedU64, @intCast(usize, @ptrToInt(_base)) +% _offset).*.__val);
                                      ^~~~~~~~~~~~~~~~~~~~~~
/Users/slimsag/Desktop/hexops/mach/libs/freetype/zig-cache/o/bb72da8deab15f11b164ed8d77d537bf/cimport.zig:782:19: error: use of undeclared identifier 'struct__OSUnalignedU16'
    @intToPtr([*c]struct__OSUnalignedU16, @intCast(usize, @ptrToInt(_base)) +% _offset).*.__val = _OSSwapInt16(_data);
                  ^~~~~~~~~~~~~~~~~~~~~~
/Users/slimsag/Desktop/hexops/mach/libs/freetype/zig-cache/o/bb72da8deab15f11b164ed8d77d537bf/cimport.zig:788:19: error: use of undeclared identifier 'struct__OSUnalignedU32'
    @intToPtr([*c]struct__OSUnalignedU32, @intCast(usize, @ptrToInt(_base)) +% _offset).*.__val = _OSSwapInt32(_data);
                  ^~~~~~~~~~~~~~~~~~~~~~
/Users/slimsag/Desktop/hexops/mach/libs/freetype/zig-cache/o/bb72da8deab15f11b164ed8d77d537bf/cimport.zig:794:19: error: use of undeclared identifier 'struct__OSUnalignedU64'
    @intToPtr([*c]struct__OSUnalignedU64, @intCast(usize, @ptrToInt(_base)) +% _offset).*.__val = _OSSwapInt64(_data);
                  ^~~~~~~~~~~~~~~~~~~~~~
/Users/slimsag/Desktop/hexops/mach/libs/freetype/src/c.zig:1:20: error: C import failed: AnalysisFail
pub usingnamespace @cImport({
                   ^~~~~~~~
```
