### ISSUE TITLE
Unexpected comptime type coercion error [Regression]

### ISSUE THREAD

**Issue by brianferri** [ziglang/zig#22597]
### Zig Version

0.14.0-dev.2922+f77e1b862

### Steps to Reproduce and Observed Behavior

[0.13.0 Godbolt Working](https://godbolt.org/z/obMesMWhn)
[0.14.0 Godbolt Erroring](https://godbolt.org/z/Gbn9fMxaa)

- Set up a Zig project and compile the following minimal repro using the specified version:

```zig
const std = @import("std");

const L = struct { a: u1 };

const S = struct {
    items: []const L = &.{},

    pub fn a(comptime self: *S) *S {
        self.items = self.items ++ .{.{ .a = 0 }};
        return self;
    }
};

pub fn main() !void {
    comptime {
        var s = S{};
        _ = s.a();
    }
}
```

- Notice the error:

```log
run
└─ run ZigUnexpectedTypeCoercionError
   └─ zig build-exe ZigUnexpectedTypeCoercionError Debug native 1 errors
src/main.zig:9:39: error: expected type 'main.L', found 'main.S.a__struct_2486'
        self.items = self.items ++ .{.{ .a = 0 }};
                                     ~^~~~~~~~~~
src/main.zig:9:39: note: struct declared here
src/main.zig:3:11: note: struct declared here
const L = struct { a: u1 };
          ^~~~~~~~~~~~~~~~
src/main.zig:17:16: note: called from here
        _ = s.a();
            ~~~^~
```

### Expected Behavior

As it was a feature that worked in 0.13.0 I'd expect this to work the same way in 0.14.0

**Comment by MatthiasPortzel** [comment]
This is an intentional change; see the following proposal and PR. 

https://github.com/ziglang/zig/issues/16865
https://github.com/ziglang/zig/pull/21817

> As it was a feature that worked in 0.13.0 I'd expect this to work the same way in 0.14.0

There are breaking changes between pre-1.0 Zig versions.

**Comment by brianferri** [comment]
I see how the Proposal/PR is related, regarding mostly [this comment](https://github.com/ziglang/zig/issues/16865#issuecomment-1698604037)
However I fail to understand how or why it should be considered an anonymous struct when the type is effectively known (`self.items: []const L`), in which case it wouldn't be so much a regression but rather a bug in the removal of anonymous struct types

**Comment by mlugg** [comment]
The type isn't known through RLS because `++` is quite loose on types (the LHS and RHS can both be slices, or arrays, or tuples, and you can even mix and match). So, unfortunately, you do currently need to specify the inner type to make this work.
