### ISSUE TITLE
usingnamespace not working on 0.9.x?

### ISSUE THREAD

**Issue by manast** [ziglang/zig#13273]
### Zig Version

0.9.1

### Steps to Reproduce

In zig versions 0.7 and below the following would mixing the redismodule exports into the global namespace:
```
usingnamespace @import("redismodule.zig");
```
However, after upgrading to 0.9.1 this is not true anymore, so I get compiler errors like this:
```
error: use of undeclared identifier 'RedisModuleCtx'
export fn RedisModule_OnLoad(ctx: *RedisModuleCtx) c_int {
```

If I import it as a module, then it works:
```
const mod = @import("redismodule.zig");

export fn RedisModule_OnLoad(ctx: *mod.RedisModuleCtx) c_int {
...
```
I could not find any changelog where this was mentioned as a breaking change...

### Expected Behavior

It should compile without errors...

### Actual Behavior

Gives compiler errors as explained above.

**Comment by Luukdegram** [comment]
This was changed in the 0.9.0 release. I highly recommend reading the release notes: https://ziglang.org/download/0.9.0/release-notes.html#usingnamespace-No-Longer-Affects-Identifier-Lookup

**Comment by manast** [comment]
Ok. But what is the solution? 
This:
```
pub usingnamespace @cImport("redismodule.h");
````

nor this works anymore:
```
pub usingnamespace @import("redismodule.<ip");
```

**Comment by manast** [comment]
Nor this:
```
pub usingnamespace @cImport({
    @cInclude("redismodule.h");
});
```

**Comment by nektro** [comment]
there is no a workaround at present
