### PR TITLE
Translate-c support initializer lists in macros

### LINKED ISSUE #4946: const sized array of extern structs causes std.mem.zeroes to error: out of bounds pointer access.
Regression, I believe, in https://github.com/ziglang/zig/commit/ef419dd72d3fc9ec1454099367bd8d43f1b5037b.

0.5.0+cd20e0cc6

```zig
const zeros = @import("std").mem.zeroes;

pub export fn main() u8 {
    const some_struct = extern struct {
        someField: u8,
    };

    var hello = zeros([1]some_struct);

    return 1;
}
```

```zig build-exe test2.zig```

```
C:\dev\Zig\lib\zig\std\mem.zig:320:52: error: out of bounds pointer access
                @memset(@ptrCast([*]u8, &item), 0, @sizeOf(T));
                                                   ^
C:\dev\Zig\lib\zig\std\mem.zig:344:40: note: called from here
            return [_]info.child{zeroes(info.child)} ** info.len;
                                       ^
.\test2.zig:10:22: note: called from here
    var hello = zeros([1]some_struct);
                     ^
.\test2.zig:3:25: note: called from here
pub export fn main() u8 {
                        ^
C:\dev\Zig\lib\zig\std\mem.zig:320:17: note: referenced here
                @memset(@ptrCast([*]u8, &item), 0, @sizeOf(T));
                ^
C:\dev\Zig\lib\zig\std\mem.zig:344:40: note: referenced here
            return [_]info.child{zeroes(info.child)} ** info.len;
```

Remove either extern, or the array size specifier and the compiler succeeds.

### LINKED ISSUE #5141: mem.zeroes: out-of-bounds pointer access on extern struct at global scope
The following yields an out-of-bounds error [here](https://github.com/ziglang/zig/blob/master/lib/std/mem.zig#L345) at compiletime:
```zig
const b = @import("std").mem.zeroes(extern struct{a: i32});

export fn c() void {
    _ = b;
}
```
This does not:
```zig
export fn c() void {
    _ = @import("std").mem.zeroes(extern struct{a: i32});
}
```

### LINKED ISSUE #5887: Issue translating raylib.h, unexecpted token Id{ .LBrace = void }
Full file in question: https://github.com/raysan5/raylib/blob/7ef114d1da2c34a70bba5442497103441647d8f3/src/raylib.h

Isolated snippet that reproduces the error ( from line 118 to 128 ):
```C
// NOTE: MSC C++ compiler does not support compound literals (C99 feature)
// Plain structures in C++ (without constructors) can be initialized from { } initializers.
#if defined(__cplusplus)
    #define CLITERAL(type)      type
#else
    #define CLITERAL(type)      (type)
#endif

// Some Basic Colors
// NOTE: Custom raylib color palette for amazing visuals on WHITE background
#define LIGHTGRAY  CLITERAL(Color){ 200, 200, 200, 255 }   // Light Gray
```
Translate error of interest:
`pub const LIGHTGRAY = @compileError("unable to translate C expr: unexpected token Id{ .LBrace = void }");`

### PR DESCRIPTION
**Pull request by Vexu**
Closes #5887
Closes #5141
Closes #4946

### CODE REVIEW

File: lib/std/mem.zig [hunk 1]
```diff
@@ -709,6 +709,14 @@ pub fn zeroInit(comptime T: type, init: anytype) T {
                 .Struct => |init_info| {
                     var value = std.mem.zeroes(T);
 
+                    // typeInfo won't tell us if this is a tuple
```
Comment (andrewrk) [inline lib/std/mem.zig:712]: I'm fine with leaving this for now, but I'm thinking we add this to type info in the language spec, yeah?

Comment (Vexu) [reply lib/std/mem.zig:712]: `is_tuple` was accepted as part of #4335, just hasn't been implemented yet.

Comment (andrewrk) [reply lib/std/mem.zig:712]: I may not have a great memory, but at least I am consistent :sweat_smile:
