### ISSUE TITLE
Package fetching has regressed on Windows

### ISSUE THREAD

**Issue by squeek502** [ziglang/zig#17477]
### Zig Version

0.12.0-dev.878+7abf9b3a83

### Steps to Reproduce and Observed Behavior

Regressed in https://github.com/ziglang/zig/pull/17392

Building `zls` on latest master:

```
> zig build -Doptimize=ReleaseSafe
C:\Users\Ryan\Programming\Zig\zls\zig-cache\o\8c6656817d7b9ba969d47a90c375e93f\dependencies.zig:3:70: error: invalid escape character: 'p'
        pub const build_root = "C:\\Users\\Ryan\\AppData\\Local\\zig\p\\1220363c7e27b2d3f39de6ff6e90f9537a0634199860fea237a55ddb1e1717f5d6a5";
                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\Ryan\Programming\Zig\zls\zig-cache\o\8c6656817d7b9ba969d47a90c375e93f\dependencies.zig:8:70: error: invalid escape character: 'p'
        pub const build_root = "C:\\Users\\Ryan\\AppData\\Local\\zig\p\\122089a8247a693cad53beb161bde6c30f71376cd4298798d45b32740c3581405864";
                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\Ryan\Programming\Zig\zls\zig-cache\o\8c6656817d7b9ba969d47a90c375e93f\dependencies.zig:13:70: error: invalid escape character: 'p'
        pub const build_root = "C:\\Users\\Ryan\\AppData\\Local\\zig\p\\1220bb12c9bfe291eed1afe6a2070c7c39918ab1979f24a281bba39dfb23f5bcd544";
                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

With `0.12.0-dev.819+75b48ef50` (one build before https://github.com/ziglang/zig/pull/17392 was merged):

```
> "C:\Users\Ryan\Programming\Zig\zig-downloaded\zig-windows-x86_64-0.12.0-dev.819+75b48ef50\zig" build -Doptimize=ReleaseSafe

```
(success)

### Expected Behavior

Successful fetching and compilation

**Comment by der-teufel-programming** [comment]
I'll take a look at this since I've also stared having problems with building zls

**Comment by squeek502** [comment]
@der-teufel-programming I've found the fix already: #17478

**Comment by squeek502** [comment]
By the way, this can also manifest as this error:

```
> zig build -Doptimize=ReleaseSafe
warning: FileNotFound: C:\Users\Ryan\AppData\Local\zig\p\1220363c7e27b2d3f39de6ff6e90f9537a0634199860fea237a55ddb1e1717f5d6a5\build.zig
error: FileNotFound
```

but I'm unsure exactly why I stopped hitting that error and started hitting the compile error in the generated `dependencies.zig`.

**Comment by nullptrdevs** [comment]
> By the way, this can also manifest as this error:
> 
> ```
> > zig build -Doptimize=ReleaseSafe
> warning: FileNotFound: C:\Users\Ryan\AppData\Local\zig\p\1220363c7e27b2d3f39de6ff6e90f9537a0634199860fea237a55ddb1e1717f5d6a5\build.zig
> error: FileNotFound
> ```
> 
> I'm unsure exactly why I stopped hitting that error and started hitting the compile error in the generated `dependencies.zig`. Something cache related I'm sure.

Greetings,

ZLS'[ CI](https://github.com/zigtools/zls/actions/runs/6487832340/job/17619197855)  just pulled latest zig, but is still failing with `FileNotFound`,
```
{
 "zig_exe": "C:\\hostedtoolcache\\windows\\zig\\master\\x64\\zig.exe",
 "lib_dir": "C:\\hostedtoolcache\\windows\\zig\\master\\x64\\lib",
 "std_dir": "C:\\hostedtoolcache\\windows\\zig\\master\\x64\\lib\\std",
 "global_cache_dir": "C:\\Users\\runneradmin\\AppData\\Local\\zig",
 "version": "0.12.0-dev.881+42998e637",
 "target": "x86_64-windows.win10_fe...win10_fe-gnu"
}
```
