### ISSUE TITLE
Compiler panics on incorrect code; returning tuples (anonymous structs) from functions fail on the latest master. 

### ISSUE THREAD

**Issue by hqhs** [ziglang/zig#15615]
### Zig Version

0.11.0-dev.2969+855493bb8

### Steps to Reproduce and Observed Behavior

Compiler panics on incorrect code; returning tuples (anonymous structs) from functions fail on latest master. 

I'm new to Zig, and I heavily rely on docs than writing code. I produced incorrect code while rewriting some rust tutorial in Zig (complete repro below) which panics the compiler. After some investigation, I found the correct version, which works on some versions but not the latest master. 

The surface search failed to prove if it's a duplicate or not. 

I would love to investigate it further, but it's 4 am local time. 

Platform: aarch64

Correct code which works on `0.11.0-dev.2969+855493bb8`:

```
fn return_anon_struct(i: usize) struct{usize, usize} {
    return .{@as(usize, i), @as(usize, i)};
}

test "return anon struct" {
    const i: usize = 7;
    const got = return_anon_struct(i);

    try std.testing.expectEqual(i, got[0]);
    try std.testing.expectEqual(i, got[1]);
}
```

Doesn't work on `0.10.1` with an error: 

```
correct_code.zig:3:40: error: struct field missing type
fn return_anon_struct(i: usize) struct{usize, usize} {
                                      ^~~~~
```

Incorrect code which fails both on `0.11.0-dev.2969+855493bb8` and (latest master) `0.11.0-dev.3006+ff59c4584`

```
fn return_anon_struct_incorectly(param: usize) struct{usize, usize} {
    return struct{ param, param };
}

test "return anon struct incorrectly" {
    const cursor = 6;
    const limit = 10;
    const expect = struct{ cursor, limit };
    const got = return_anon_struct_incorectly(0);

    try std.testing.expectEqual(expect[0], got[0]);
    try std.testing.expectEqual(expect[1], got[1]);
}
```

With trace from latest master `0.11.0-dev.3006+ff59c4584` (entire trace below as a file): 

```
thread 1619592 panic: attempt to unwrap error: NeededSourceLocation
Analyzing incorrect_code.zig: incorrect_code.zig:return_anon_struct_incorectly
      %10 = dbg_block_begin()
      %11 = dbg_stmt(2, 5)
      %12 = ret_type() 
    > %13 = extended(struct_decl(tuple, func, Auto, {}, {
        @"0": {%15, %16},
        @"1": {%17, %18},
      }) 
      %14 = closure_capture(%6) 
      %19 = as_node(%12, %13) 
      %20 = restore_err_ret_index(@Zir.Inst.Ref.none, @Zir.Inst.Ref.none)
      %21 = dbg_stmt(2, 5)
      %22 = ret_node(%19) 
      %23 = dbg_block_end()
      %24 = restore_err_ret_index(%9, @Zir.Inst.Ref.none)
      %25 = break(%9, @Zir.Inst.Ref.void_value)
    For full context, use the command
      zig ast-check -t incorrect_code.zig

  in incorrect_code.zig: incorrect_code.zig:return_anon_struct_incorectly
    > %9 = block({%10..%25}) 

/NothingToSeeHere/zig/src/Sema.zig:2230:13: 0x1003a8f8f in failWithOwnedErrorMsg (zig)
            return error.NeededSourceLocation;
            ^
/NothingToSeeHere/zig/src/Sema.zig:1990:5: 0x1005b4347 in failWithNeededComptime (zig)
    return sema.failWithOwnedErrorMsg(msg);
    ^
/NothingToSeeHere/zig/src/Sema.zig:1856:5: 0x100d6e083 in resolveConstMaybeUndefVal (zig)
    return sema.failWithNeededComptime(block, src, reason);
    ^
/NothingToSeeHere/zig/src/Sema.zig:2734:101: 0x100de069f in createAnonymousDeclTypeNamed (zig)
                    const arg_val = sema.resolveConstMaybeUndefVal(block, .unneeded, arg, "") catch unreachable;
                                                                                                    ^
```
    
Entire stack trace as a file:
[backtrace.txt](https://github.com/ziglang/zig/files/11416217/backtrace.txt)

### Expected Behavior

- incorrect code to fail with an error message

**Comment by schmee** [comment]
What command are you using to build your code? At least the first example is using the native ARM backend (instead of LLVM), which is incomplete and known not to work in most cases.

**Comment by hqhs** [comment]
Oh. 

I used the `zig test` for all examples. I knew about different backends, but I forget to ensure that debug build of the compiler (I built it to provide stack traces) uses LLVM. 

I just checked -- the correct version works with -fLLVM, but the incorrect still panics. I'm going to fix the issue right now and rebuild debug compiler later today.
