### ISSUE TITLE
Compilation of possibly error producing code at comptime crashes compiler

### ISSUE THREAD

**Issue by smokey42** [ziglang/zig#3512]
Testet against e98e5dda52d8bcaa2e59861bbbd500b81edfde2d

The code in question:

```zig
const std = @import("std");

pub fn main() !void {
    comptime {
        var address: u32 = try std.net.Address.parseIp4("127.0.0.1", 80);
    }
}
```
The error it produced:

```
Assertion failed at /home/christoph.rauch/src/zig/src/ir.cpp:17692 in ir_analyze_instruction_elem_ptr. This is a bug in the Zig compiler.
???:?:?: 0x5633ee1618ec in ??? (???)


???:?:?: 0x5633ee121d8d in ??? (???)


???:?:?: 0x5633ee07f32a in ??? (???)


???:?:?: 0x5633ee0c0275 in ??? (???)


???:?:?: 0x5633ee0e0055 in ??? (???)


???:?:?: 0x5633ee0e0f2c in ??? (???)


???:?:?: 0x5633ee0a79fb in ??? (???)


???:?:?: 0x5633ee0ba5bc in ??? (???)


???:?:?: 0x5633ee0bc67a in ??? (???)


???:?:?: 0x5633ee0e009d in ??? (???)


???:?:?: 0x5633ee0e0f2c in ??? (???)


???:?:?: 0x5633ee1312ea in ??? (???)


???:?:?: 0x5633ee131897 in ??? (???)


???:?:?: 0x5633ee13083e in ??? (???)


???:?:?: 0x5633ee0d7a42 in ??? (???)


???:?:?: 0x5633ee0e072d in ??? (???)


???:?:?: 0x5633ee0e0f2c in ??? (???)


???:?:?: 0x5633ee1312ea in ??? (???)


???:?:?: 0x5633ee131897 in ??? (???)


???:?:?: 0x5633ee132283 in ??? (???)


???:?:?: 0x5633ee06b286 in ??? (???)


???:?:?: 0x5633ee06ef00 in ??? (???)


???:?:?: 0x5633ee0424f9 in ??? (???)


???:?:?: 0x7fa8fd761b6a in ??? (???)


???:?:?: 0x41fd89415541f688 in ??? (???)



Command terminated

```

**Comment by Wolf480pl** [comment]
I have a similar problem but different error on 0.6.0.
When I try:
```zig
const std = @import("std");
const net = std.net;

const listenAddr = net.Address.parseIp("127.0.0.1", 3000);

pub fn main() !void {
    std.debug.warn("{}", .{listenAddr});
}
```
I get
```
/usr/lib/zig/std/mem.zig:1935:40: error: out of bounds slice
    return @ptrCast(cast_target, slice)[0 .. slice.len * @sizeOf(meta.Elem(Slice))];
                                       ^
/usr/lib/zig/std/net.zig:167:41: note: called from here
        const out_ptr = mem.sliceAsBytes(@as(*[1]u32, &result.in.addr)[0..]);
                                        ^
/usr/lib/zig/std/net.zig:25:21: note: called from here
        if (parseIp4(name, port)) |ip4| return ip4 else |err| switch (err) {
                    ^
./test.zig:4:39: note: called from here
const listenAddr = net.Address.parseIp("127.0.0.1", 3000);
                                      ^
./test.zig:4:39: note: called from here
const listenAddr = net.Address.parseIp("127.0.0.1", 3000);
                                      ^
/usr/lib/zig/std/net.zig:167:41: note: referenced here
        const out_ptr = mem.sliceAsBytes(@as(*[1]u32, &result.in.addr)[0..]);
                                        ^
/usr/lib/zig/std/net.zig:25:21: note: referenced here
        if (parseIp4(name, port)) |ip4| return ip4 else |err| switch (err) {
                    ^
./test.zig:4:39: note: referenced here
const listenAddr = net.Address.parseIp("127.0.0.1", 3000);
                                      ^
./test.zig:7:28: note: referenced here
    std.debug.warn("{}", .{listenAddr});
                           ^
/usr/lib/zig/std/start.zig:253:40: note: referenced here
            const result = root.main() catch |err| {
```

**Comment by daurnimator** [comment]
This works now.

**Comment by ducdetronquito** [comment]
Hi @daurnimator !

In which commit this issue has been fixed ?

I can confirm the example above does not compile with Zig 0.7.0:

```zig
const std = @import("std");

test "Parse IPv4 at compile time" {
    comptime {
        var address: u32 = try std.net.Address.parseIp4("127.0.0.1", 80);
    }
}
```

Output the following compilation error:

```
zig\std\mem.zig:2196:40: error: out of bounds slice
    return @ptrCast(cast_target, slice)[0 .. slice.len * @sizeOf(meta.Elem(Slice))];
                                       ^
zig\std\net.zig:199:41: note: called from here
        const out_ptr = mem.sliceAsBytes(@as(*[1]u32, &result.sa.addr)[0..]);
                                        ^
zig\std\net.zig:89:51: note: called from here
        return Address{ .in = try Ip4Address.parse(buf, port) };
                                                  ^
.\src\issue_3512.zig:341:56: note: called from here
        var address: u32 = try std.net.Address.parseIp4("127.0.0.1", 80);
                                                       ^
.\src\issue_3512.zig:339:16: note: called from here
test "Parse IPv4 at compile time" {
               ^
zig\std\net.zig:199:41: note: referenced here
        const out_ptr = mem.sliceAsBytes(@as(*[1]u32, &result.sa.addr)[0..]);
                                        ^
zig\std\net.zig:89:51: note: referenced here
        return Address{ .in = try Ip4Address.parse(buf, port) };
                                                  ^
.\src\issue_3512.zig:341:56: note: referenced here
        var address: u32 = try std.net.Address.parseIp4("127.0.0.1", 80);
                                                       ^
The following command exited with error code 1
```

**Comment by daurnimator** [comment]
> In which commit this issue has been fixed ?
> 
> I can confirm the example above does not compile with Zig 0.7.0:

@ducdetronquito the bug here was the compiler blowing up when it should have given you a compile error.
