### PR TITLE
wyhash: support comptime usage

### LINKED ISSUE #16070: std.hash.Wyhash no longer works at comptime
### Zig Version

v0.11.0-dev.3655+a2f54fce5

### Steps to Reproduce and Observed Behavior

Both of these worked in 0.11.0-dev.2777+b95cdf0ae:
```zig
const std = @import("std");
test {
    _ = comptime brk: {
        var hasher = std.hash.Wyhash.init(0);
        hasher.update("heyyyheyyyheyyyheyyy");
        break :brk hasher.final();
    };
}
```

```zig
const std = @import("std");
test {
    _ = comptime brk: {
        var hasher = std.hash.Wyhash.init(0);
        hasher.update("heyyyheyyyheyyyheyyy");
        break :brk hasher.final();
    };
}
```

Now, an error like this is produced:
```zig
❯ zig test /Users/dylan/Desktop/repro.zig
/Users/dylan/zig/0.11.0-dev.3655+a2f54fce5/files/lib/std/hash/wyhash.zig:159:49: error: TODO implement Sema comptime pointer subtraction
        self.a = read(8, (input.ptr + input.len - 16)[0..8]);
                          ~~~~^~
/Users/dylan/zig/0.11.0-dev.3655+a2f54fce5/files/lib/std/hash/wyhash.zig:183:24: note: called from here
            self.final1(input[i..]);
            ~~~^~~~
/Users/dylan/Desktop/repro.zig:25:38: note: called from here
    _ = comptime std.hash.Wyhash.hash(0, "heyyyheyyyheyyyheyyyheyyyheyyyheyyyheyyyheyyyheyyyheyyyheyyy");
                 ~~~~^~~~~~~~~~~~~~~
/Users/dylan/zig/0.11.0-dev.3655+a2f54fce5/files/lib/std/hash/wyhash.zig:159:49: error: TODO implement Sema comptime pointer subtraction
        self.a = read(8, (input.ptr + input.len - 16)[0..8]);
                          ~~~~^~
/Users/dylan/zig/0.11.0-dev.3655+a2f54fce5/files/lib/std/hash/wyhash.zig:183:24: note: called from here
            self.final1(input[i..]);
            ~~~^~~~
/Users/dylan/Desktop/repro.zig:25:38: note: called from here
    _ = comptime std.hash.Wyhash.hash(0, "heyyyheyyyheyyyheyyyheyyyheyyyheyyyheyyyheyyyheyyyheyyyheyyy");
```

```zig
/Users/dylan/zig/0.11.0-dev.3655+a2f54fce5/files/lib/std/hash/wyhash.zig:159:49: error: TODO implement Sema comptime pointer subtraction
        self.a = read(8, (input.ptr + input.len - 16)[0..8]);
                          ~~~~^~
/Users/dylan/zig/0.11.0-dev.3655+a2f54fce5/files/lib/std/hash/wyhash.zig:82:27: note: called from here
            newSelf.final1(input);
            ~~~~^~~
/Users/dylan/Desktop/repro.zig:19:32: note: called from here
        break :brk hasher.final();
                   ~~^~
```

### Expected Behavior

Tests should compile

### PR DESCRIPTION
**Pull request by tiehuis**
Closes #16070.

---

Performance has no change and SMHasher sanity checks continue to pass.

### CODE REVIEW

**Comment by andrewrk** [comment]
Thanks!
