### PR TITLE
std.atomic: make cache_line const a comptime_int

### PR DESCRIPTION
**Pull request by kiedtl**
This fixes potential issues and unintended coercions in other areas, such as std.ArrayList.

Previously:

```
const std = @import("std");
const Foo = struct { buf: [68536]u8 = undefined };

pub fn main() void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    var v = std.ArrayList(Foo).init(gpa.allocator());
    v.append(undefined) catch unreachable;
}
```

would yield

```
/home/kiedtl/zig14/lib/std/array_list.zig:1220:81: error: type 'u16' cannot represent integer value '68536'
        const init_capacity = @as(comptime_int, @max(1, std.atomic.cache_line / @sizeOf(T)));
                                                                                ^~~~~~~~~~
referenced by:
    growCapacity: /home/kiedtl/zig14/lib/std/array_list.zig:1227:35
    ensureTotalCapacity: /home/kiedtl/zig14/lib/std/array_list.zig:449:89
    8 reference(s) hidden; use '-freference-trace=10' to see all references
```

This change fixes this.

### CODE REVIEW

**Review by alexrp — APPROVED** [review]

**Comment by alexrp** [comment]
Looks like this regressed in #21956.
