### ISSUE TITLE
ConsoleApi.h not found when compiling Windows executable (0.8.0)

### ISSUE THREAD

**Issue by niklas-ourmachinery** [ziglang/zig#9240]
Compiling this file

~~~c
#include <Windows.h>
#include <ConsoleApi.h>
#include <stdio.h>

int main(int argc, char *argv[])
{
    printf("Hello world!");
}
~~~

with

~~~
zig build-exe test.c -lc
~~~

Used to work fine in `0.8.0-dev.2065+bc06e1982`, but in `0.8.0` I get an error:

~~~
>zig build-exe test.c -lc
error(compilation): clang failed with stderr: test.c:3:10: fatal error: 'ConsoleApi.h' file not found

test.c:1:1: error: unable to build C object: clang exited with code 1
~~~

**Comment by LemonBoy** [comment]
What happens if you add `-target native-windows-msvc`? The default ABI was recently switched to GNU from MSVC, I believe that's this also explains the other issue you are having wrt library names.

**Comment by niklas-ourmachinery** [comment]
Seems to have the same behavior:

~~~c
>zig build-exe test.c -lc -target native-native-msvc
error(compilation): clang failed with stderr: test.c:1:10: fatal error: 'ConsoleApi.h' file not found

test.c:1:1: error: unable to build C object: clang exited with code 1
~~~
