### PR TITLE
Sema: Don't ignore current declaration if it's not ambiguous

### LINKED ISSUE #17872: Function not visible inside itself through generic struct with usingnamespace
I apologize in advance for the title of this issue.
### Zig Version

0.12.0-dev.1396+f6de3ec96

### Steps to Reproduce and Observed Behavior

1. Create a file `bug.zig`:
```zig
const B = struct {
    pub fn func() void {
        @compileLog(@typeInfo(C).Struct.decls); // .{ .{ .name = "func" } }
        @compileLog(@hasDecl(C, "func")); // false
        _ = C.func; // ERROR: no member named func
    }
};

fn A(comptime T: type) type {
    return struct {
        pub usingnamespace T;
    };
}

const C = A(B);

pub fn main() !void {
    C.func();
}
```
2. `zig run bug.zig`
```
bug.zig:5:14: error: struct 'bug.A(bug.B)' has no member named 'func'
        _ = C.func; // ERROR: no member named func
            ~^~~~~
bug.zig:10:12: note: struct declared here
    return struct {
           ^~~~~~
referenced by:
    main: bug.zig:18:6
    callMain: /home/lordmzte/.local/share/zupper/installs/master/lib/std/start.zig:581:32
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

Compile Log Output:
@as([]const builtin.Type.Declaration, .{ .{.name = "func"} })
@as(bool, false)
```
According to `@typeInfo`, the declaration `func` is present within C, but according to `@hasDecl`, it is not. Schrödinger's declaration!

### Expected Behavior

The code compiles.

### PR DESCRIPTION
**Pull request by akarpovskii**
This fixes #17872.

Previous logic was introduced in https://github.com/ziglang/zig/commit/c17793b4875cc9e1ccb605431142ffecb0b6f3f2 by @Vexu to address issue #12429. For the following piece of code there's no ambiguity and no reason to ignore the only declaration.

```zig
pub const Example = struct {
    usingnamespace struct {}; // works without this line

    pub fn foo() void {
        _ = Example.foo;  // error: struct 'main.Example' has no member named 'foo'
    }
};

pub fn main() !void {
    Example.foo();
}
```

### CODE REVIEW

**Comment by andrewrk** [comment]
I'm sorry, this will need to be reworked after some recent changes to the way `usingnamespace` works (there are conflicts). Also note the existence of #20663, which is proposed but not yet accepted or rejected.
