### PR TITLE
Sema: fix incorrect element pointer type of c pointer array

### LINKED ISSUE #14905: C pointer to array `[*c][4]f32` causes compiler error when assigning to it using `cPointer.*[0] = …`
### Zig Version

0.11.0-dev.1913+95f6a5935

### Steps to Reproduce and Observed Behavior

I discovered this while investigating a compile error when trying to include `linmath.h` discovered by abcode89 on the zig discord.
I could reduce the issue to the following zig code which was (with some reductions) produced by translate_c:

```zig
pub fn main() void {
	var array2d: [42][4]f32 = undefined;
	var cPointer: [*c][4]f32 = &array2d;
	(cPointer + 5).*[0] = 0;
}
```

Behavior:
```
$ zig run test.zig
test.zig:4:24: error: expected type '[4]f32', found 'comptime_int'
 (cPointer + 5).*[0] = 0;
                       ^
referenced by:
    callMain: /home/mint/Downloads/zig/lib/std/start.zig:607:17
    initEventLoopAndCallMain: /home/mint/Downloads/zig/lib/std/start.zig:551:34
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

It works when printing the value of `(cPointer + 5).*[0]` works correctly and has the correct type.
It also works when doing `(cPointer + 5)[0][0] = 0;`

### Expected Behavior

There should be no compiler error.
`.*` and `[0]` should behave the same for C pointers.

### LINKED ISSUE #22045: zig translate-c Type Propagation Error for Nullable Pointer ([*c]) Dereferencing and Address Calculation in Zig
### Zig Version

0.14.0-dev.2064+b5cafe223

## Input C Code

```c
typedef int (*myarr)[2];

void main() {
    // Define an array and set `a` to point to it
    int array[2] = {10, 20};
    int (*a)[2] = &array;  // `a` points to `array`

    // Set `b` to point to the same array, casted to `myarr`
    myarr b = (myarr)a;

    // Modify array elements through `b`
    (*b)[0] = 30;
}
```

## Translated zig code
```zig
pub const myarr = [*c][2]c_int;
pub export fn main() void {
    var array: [2]c_int = [2]c_int{
        10,
        20,
    };
    _ = &array;
    var a: [*c][2]c_int = &array;
    _ = &a;
    var b: myarr = @as(myarr, @ptrCast(@alignCast(a)));
    _ = &b;
    b.*[@as(c_uint, @intCast(@as(c_int, 0)))] = 30;
}
```

## zig build failure

```
runner.zig:68:49: error: expected type '[2]c_int', found 'comptime_int'
    b.*[@as(c_uint, @intCast(@as(c_int, 0)))] = 30;
                                                ^~
```

The generated zig code incorrectly uses a cast that results in a `comptime_int` type mismatch, making it impossible to modify the array elements as intended.

### Expected Behavior

The `zig translate-c` tool should generate the correct zig code that allows accessing and modifying array elements through a pointer. For example, the output zig code should correctly handle the array pointer and allow the assignment.

### LINKED ISSUE #25546: C Pointer via ptrFromInt of extern struct with array field cannot be dereferenced and indexed
### Zig Version

0.16.0-dev.726+8efcfeaf1

### Steps to Reproduce and Observed Behavior

Hi, while testing the current master branch for an embedded project I noticed a regression versus 0.15.1 that I was previously using.
A C pointer created via `ptrFromInt` of an extern struct that has an array field cannot be dereferenced and indexed into anymore. It behaves differently than a C pointer created from a struct reference. Similar code is generated with translate-c from MMIO logic that compiles with 0.15.1 but not on master. Target independant.

```sh
zig build-exe main.zig
```

main.zig:
```zig
const ExternStruct = extern struct {
    fields: [2]u8,
};

pub fn main() void {
    // This works
    var my_struct = ExternStruct{ .fields = .{0} ** 2 };
    const my_struct_c_ptr1 = @as([*c]ExternStruct, &my_struct);
    my_struct_c_ptr1.*.fields[0] = 1;

    // error: expected type '[2]u8', found 'comptime_int'
    const my_struct_c_ptr2 = @as([*c]ExternStruct, @ptrFromInt(0x1000));
    my_struct_c_ptr2.*.fields[0] = 1;
}
```

These have the same type for some reason:
```zig
@compileLog(my_struct_c_ptr2.*.fields);
@compileLog(my_struct_c_ptr2.*.fields[0]);
```
```sh
Compile Log Output:
@as([2]u8, [runtime value])
@as([2]u8, [runtime value])
```

Help is appreciated, thank you

### Expected Behavior

Compiles

### PR DESCRIPTION
**Pull request by timholzhey**
Closes #25546
Closes #22045
Closes #23506
Closes #14905

This code now compiles correctly:
```zig
var arr: [1]u8 = .{0};
const arr_c_ptr = @as([*c][1]u8, &arr);
arr_c_ptr.*[0] = 1;
```

For pointer address calculation, [*c]arr[idx] can be treated a single-item pointer *arr[idx]

### CODE REVIEW

**Review by Vexu — APPROVED** [review]

**Comment by Justus2308** [comment]
Thank you for your efforts! This has since been solved differently
https://codeberg.org/ziglang/zig/commit/9ff926bb1e47ebad0f13835355841ef4654fbe60
