### ISSUE TITLE
Zig 0.14.0 tests failing with "failed to parse archive: FileNotFound" on libcompiler_rt.a cache

### ISSUE THREAD

**Issue by selfisekai** [ziglang/zig#23110]
### Zig Version

0.14.0

### Steps to Reproduce and Observed Behavior

```
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_PREFIX_PATH=/usr \
		-DCMAKE_VERBOSE_MAKEFILE=ON \
		-DZIG_VERSION="0.14.0" \
		-DZIG_SHARED_LLVM=ON \
		-DZIG_TARGET_MCPU=baseline \
		-DCLANG_INCLUDE_DIRS=/usr/lib/llvm19/include
```

```
[19/19] cd /home/lauren/aports/community/zig/src/zig-0.14.0 && /home/lauren/aports/community/zig/src/zig-0.14.0/build/zig2 build --prefix /home/lauren/aports/community/zig/src/zig-0.14.0/build/stage3 --zig-lib-dir /home/lauren/aports/community/zig/src/zig-0.14.0/lib -Dversion-string=0.14.0 -Dtarget=native -Dcpu=baseline -Denable-llvm -Dconfig_h=/home/lauren/aports/community/zig/src/zig-0.14.0/build/config.h -Dno-langref -Doptimize=ReleaseFast -Dstrip

error: failed to parse archive: FileNotFound
    note: while parsing /home/lauren/.cache/zig/o/834ba36fa2a7be0ec46c20af7e38c644/libcompiler_rt.a
```

Passes through after `rm -rf ~/.cache/zig`

### Expected Behavior

Succeeding build

**Comment by alexrp** [comment]
Was this just a transient cache problem, or is it persistent?

**Comment by selfisekai** [comment]
Persistent, I can reproduce it

**Comment by kj4tmp** [comment]
I had a transient cache error.


```
jeff@jeff-debian:~/repos/gatorcat$ zig build
install
└─ cli
   └─ install gatorcat
      └─ zig build-exe gatorcat Debug native 1 errors
error: failed to parse archive: FileNotFound
    note: while parsing /home/jeff/.cache/zig/o/e54c6dfc7b479994db443e5e4ceaed40/libcompiler_rt.a
error: the following command failed with 1 compilation errors:
/home/jeff/.config/Code/User/globalStorage/ziglang.vscode-zig/zig/linux-x86_64-0.14.0/zig build-exe -ODebug --dep gatorcat --dep flags -Mroot=/home/jeff/repos/gatorcat/src/cli/main.zig -Mgatorcat=/home/jeff/repos/gatorcat/src/lib/root.zig -ODebug -Mflags=/home/jeff/.cache/zig/p/flags-0.8.0-AAAAAJV0AACuGBBnpUnHqZzAhoGTp4ibFROBQQQZGRqx/src/parse.zig --cache-dir /home/jeff/repos/gatorcat/.zig-cache --global-cache-dir /home/jeff/.cache/zig --name gatorcat --zig-lib-dir /home/jeff/.config/Code/User/globalStorage/ziglang.vscode-zig/zig/linux-x86_64-0.14.0/lib/ --listen=- 
Build Summary: 0/4 steps succeeded; 1 failed
install transitive failure
└─ cli transitive failure
   └─ install gatorcat transitive failure
      └─ zig build-exe gatorcat Debug native 1 errors
error: the following build command failed with exit code 1:
/home/jeff/repos/gatorcat/.zig-cache/o/7cccad2677319ff1fb4d02d3bd3adbd9/build /home/jeff/.config/Code/User/globalStorage/ziglang.vscode-zig/zig/linux-x86_64-0.14.0/zig /home/jeff/.config/Code/User/globalStorage/ziglang.vscode-zig/zig/linux-x86_64-0.14.0/lib /home/jeff/repos/gatorcat /home/jeff/repos/gatorcat/.zig-cache /home/jeff/.cache/zig --seed 0xa8934fa8 -Z3386f2eaea52148d

```

It went away after I did `rm -rf ~/.cache/zig/`

**Comment by selfisekai** [comment]
git bisect done: "de8741271f3dee0062d1c9319791687e5228e593 is the first bad commit"

**Comment by meithecatte** [comment]
I cannot reproduce this.

I have tried the following:

- clone the zig repo
- check out the 0.14.0  (though behavior is the same on latest master)
- `cmake -B build -G Ninja              -DCMAKE_BUILD_TYPE=Release              -DCMAKE_INSTALL_PREFIX=/usr             -DCMAKE_PREFIX_PATH=/usr                -DCMAKE_VERBOSE_MAKEFILE=ON           -DZIG_SHARED_LLVM=ON            -DZIG_TARGET_MCPU=baseline              -DCLANG_INCLUDE_DIRS=/usr/lib/llvm19/include`
- `ninja -C build`
- build completes successfully

**Comment by gooncreeper** [comment]
Smaller Reproduction
```
echo "test {}" > tmp.zig
zig test tmp.zig
rm -r ~/.cache/zig/o
zig test tmp.zig
```

`rm -r ~/.cache/zig/o/*` replicates one of the directories with `libcompiler_rt.a` not being created for some reason (that is flaky and I have not found a consistent reproduction for that.) Nonetheless, I do not believe the compiler should fail if one of its cached files is not missing.

**Comment by selfisekai** [comment]
Yes, good point, this is actually about just `zig test`, the compiler is built successfully. I was struggling with both this and also #22119 when reporting

**Comment by selfisekai** [comment]
Re-done the bisect with `rm -r .zig-cache ~/.cache/zig` between build and test. I think the previous one was invalid because it failed due to simply new test targets appearing, without a cached compiler_rt. Now it ended up blaming 55a2e535fdb663793b84769cb6c3a261bda3fc66. I've reverted that on top of 0.14.0 and ported almost all zig codebases in aports with weird no issues, so I guess that's it.

**Comment by daurnimator** [comment]
I got a similar error (https://gist.github.com/daurnimator/cc1cc4caaf52cc5e4c18e898eff714c8).
Currently I'm holding back zig 0.14 in ArchLinux until we have a good solution here.

**Comment by ifreund** [comment]
@selfisekai Note that reverting that commit will cause alpine's zig package to have broken caching behavior for .zon files. That commit fixed https://github.com/ziglang/zig/issues/22746, though it seems that the fix itself has a flaw.

cc @mlugg

**Comment by selfisekai** [comment]
Broken cache that can be purged anytime sounds much preferable to this

**Comment by mlugg** [comment]
Hi there -- downstream package maintainers, it's your choice, but I'd strongly discourage you from providing a package with 55a2e53 reverted. I think it'd be preferable to be stuck on 0.13.0 for the moment than to have a 0.14.0 distribution with such a glaring bug (the bug which 55a2e53 fixed).

I'm going to take a look at this issue today; I can confirm that it successfully reproduces for me. I'm confident I'll have a fix up within a couple of days; downstream maintainers can then make the choice to apply it to their 0.14.0 distributions if this bug is severe enough.

The non-artificial trigger for it could do with further investigation; what would stop the `compiler_rt.a` cache being created? I've certainly never hit this locally. But regardless, yes, the compiler shouldn't fail with a damaged cache directory.

**Comment by meithecatte** [comment]
> The non-artificial trigger for it could do with further investigation; what would stop the `compiler_rt.a` cache being created? I've certainly never hit this locally. But regardless, yes, the compiler shouldn't fail with a damaged cache directory.

From what I've picked up in an IRL discussion about this, my guess would be some kind of race condition – the numbers being thrown around were ~80 failures when running the entire zig testsuite, on a 32 core machine.

**Comment by rmarquis** [comment]
> From what I've picked up in an IRL discussion about this, my guess would be some kind of race condition – the numbers being thrown around were ~80 failures when running the entire zig testsuite, on a 32 core machine.

I had many more (~400) on a 12 core machine, so it looks like the number is not even consistent. Could indeed be some race condition.

**Comment by selfisekai** [comment]
The numbers depend on global cache (`rm -r ~/.cache/zig` will increase failure rate), targets, I believe also any Zig code being in a compilation or not, and probably more factors.

**Comment by mlugg** [comment]
Okay, so!

Deleting a file in `o/` in the cache directory (local or global) is, right now, expected to cause compiler errors like this. We might change this long-term to be more resilient to corruption or user error, but at the minute it's helpful to make sure that we aren't silently redoing work due to cache bugs.

I don't believe de87412 or 55a2e53 to be related to the issue.

So, the real question here is why this file doesn't exist when the cache system clearly thinks it should. Unfortunately, I'm not able to reproduce the original issue locally.

Someone who can reproduce it, it would be incredibly helpful to get a copy of your global Zig cache directory once the issue is reproing. Specifically:
* Clear your cache directories, so you have a clean slate (i.e. `rm -rf ~/.cache/zig/ .zig-cache/`)
* Run whatever Zig commands you need to until the error occurs
  * Manually deleting files in `~/.cache/zig` or `.zig-cache/` is not allowed!
* Pack your global cache directory (`~/.cache/zig/`) into an archive (`.tar.gz` or whatever) and upload it somewhere for me!

Full disclosure: the cache directory could potentially allow anyone who can access it to recover the following information:
* The project you were compiling
* Some details of your native system:
  * OS
  * Project directory
  * Shared libraries
  * etc

Essentially, anything you could get from the project's source tree and some compiled objects/binaries for your host.

**Comment by andrewrk** [comment]
I want to add that I see fuzz testing as the long term solution to problems like this.

**Comment by selfisekai** [comment]
Building Zig 0.14.0 from stage1, no patches, running some of the tests:
```sh
rm -r ~/.cache/zig && abuild -r > out 2>&1; tar cf cache.tar ~/.cache/zig && zstd --ultra --long -22 cache.tar
```
`out`: https://s.lnl.gay/reUrCf4gAlVrIwXnqvB4MoG3ZgetyxPd.txt
`cache.tar.zst` (120M compressed, 1.6G decompressed): https://s.lnl.gay/5p0muloYQoGm8cwO7VLiXUly3gXW6sJs.tar.zst

**Comment by daurnimator** [comment]
Is there a fix for this yet? I'm still holding back zig in ArchLinux...

**Comment by kpcyrd** [comment]
I'm another Arch Linux maintainer who ended up in this thread, after testing if a zig update would be possible since it's currently holding back one of my packages.

The Rust project would usually issue a point release for bugs with that kind of severity, could you evaluate doing this same? The bug has been found and known for almost a month now.

**Comment by erikarvstedt** [comment]
I've found a repro. I'm AFK for 2 hours. but I'll share the details as soon as I'm back.

**Comment by erikarvstedt** [comment]
I've found a repro. :
On my system, the bug appears when using ZLS and running `zig build` while ZLS runs `zig build --build-runner ...` in the background.
Both `zig build` processes have different `--cache-dir` and `--zig-lib-dir` options.
`--cache-dir` differs because ZLS uses the default default local cache while I'm running `zig build` with a specific local cache when building my project.
`--zig-lib-dir` differs because I've defined `zig_lib_path` in `zls.json` so I can jump to `std` definitions in a local zig repo.

<details>
<summary><h3>Repro script</h1></summary>

```bash
#!/usr/bin/env bash
set -euo pipefail

# This script requires jq, curl, rsync, i.e. #!nix-shell -i bash -p jq curl rsync

trap 'echo "Error at ${BASH_SOURCE[0]}:$LINENO"' ERR

rm -rf /tmp/zig-cache-bug
mkdir -p /tmp/zig-cache-bug/src
cd /tmp/zig-cache-bug/src

# Create a copy of the zig lib at /tmp/zig-cache-bug/lib and modify a compiler_rt source file
# This somehow triggers the libcompiler_rt.a cache error.
{
    echo "creating lib dir"
    lib_dir=$(zig env | jq -r .lib_dir)
    if [[ $lib_dir == null ]]; then
        >&2 echo "error: couldn't find zig lib dir"
        exit 1
    fi
    rsync -a --delete --chmod=u+w --mkpath $lib_dir/ /tmp/zig-cache-bug/lib
    chmod +w /tmp/zig-cache-bug/lib/compiler_rt/absvdi2_test.zig
    echo 'test "absvdi2" {}' > /tmp/zig-cache-bug/lib/compiler_rt/absvdi2_test.zig
}

# Fetch ZLS 0.14.0 build runner
curl -fsS https://raw.githubusercontent.com/zigtools/zls/refs/tags/0.14.0/src/build_runner/0.14.0.zig > /tmp/zig-cache-bug/build_runner_zig
echo "fc10f75a531430daf71c3bc372c92143e378b34bc314cd7999da38406c911c9f /tmp/zig-cache-bug/build_runner_zig" | sha256sum -c

zig init

# Start a `zig build --build-runner` instance in the background
cmd=(zig build --global-cache-dir /tmp/zig-cache-bug/global-cache --cache-dir /tmp/zig-cache-bug/local-cache1
     --build-runner /tmp/zig-cache-bug/build_runner_zig
     --zig-lib-dir /tmp/zig-cache-bug/lib)
# Note that instead just starting a simple `zig build --help` with a different --zig-lib-dir doesn't trigger the bug
# cmd=(zig build --help --global-cache-dir /tmp/zig-cache-bug/global-cache --cache-dir /tmp/zig-cache-bug/local-cache1
#      --zig-lib-dir /tmp/zig-cache-bug/lib)
if [[ ! -t 1 ]]; then
    >&2 echo "error: stdout must be a tty, so that zig prints progress output"
    exit 1
fi
# Watch the output of the background instance through a pipe
pipe=/tmp/zig-cache-bug/pipe
mkfifo "$pipe"
script -q -c "${cmd[*]}" | tee "$pipe" &

echo 'Wait until the `zig build` background instance builds compiler_rt'
echo 'Without waiting here, the bug is not always triggered'
grep -m 1 "compiler_rt" "$pipe" > /dev/null
echo 'Start another `zig build` instance'
zig build --help --global-cache-dir /tmp/zig-cache-bug/global-cache --cache-dir /tmp/zig-cache-bug/local-cache1
echo 'Start another instance with a different local cache. This triggers the bug.'
zig build --help --global-cache-dir /tmp/zig-cache-bug/global-cache --cache-dir /tmp/zig-cache-bug/local-cache2 || true
#
# Result:
# error: failed to parse archive: FileNotFound
#   note: while parsing /tmp/zig-cache-bug/global-cache/o/dd536c688b4bf87fcfa9d90db12d0f47/libcompiler_rt.a
```
</details>

### Vagrant repro
```bash

vagrant init bento/ubuntu-24.04
vagrant up --provider libvirt
vagrant ssh -c 'sudo snap install zig --beta --classic'
# repro.sh is the repro script above
<repro.sh vagrant ssh -c 'cat > /tmp/repro.sh; chmod +x /tmp/repro.sh'
# Run a separate ssh cmd because the one above doesn't creaty a tty for stdout (even with `--tty`)
vagrant ssh -c '/tmp/repro.sh'
```

**Comment by kpcyrd** [comment]
It can also be reliably reproduced through the Arch Linux build system:

**PKGBUILD**
```sh
# Maintainer: Daurnimator <daurnimator@archlinux.org>
# Contributor: Marc Tiehuis <marctiehuis@gmail.com>

pkgname=zig
pkgver=0.14.0
pkgrel=1
pkgdesc='a general-purpose programming language and toolchain for maintaining robust, optimal, and reusable software'
arch=('x86_64')
url='https://ziglang.org/'
license=('MIT')
options=('!lto')
depends=('clang' 'lld' 'llvm-libs')
makedepends=('cmake' 'llvm')
checkdepends=('lib32-glibc')
source=("https://ziglang.org/download/$pkgver/zig-$pkgver.tar.xz"
        "skip-localhost-test.patch")
sha256sums=('c76638c03eb204c4432ae092f6fa07c208567e110fbd4d862d131a7332584046'
            'eeb5f0f72035c52bf558ffc77a171a3ddf93eac7d663ef0c82826007763717a8')

prepare() {
    cd "$pkgname-$pkgver"

    patch -p1 -i ../skip-localhost-test.patch
}

build() {
    cd "$pkgname-$pkgver"

    local cmake_vars=(
        CMAKE_INSTALL_PREFIX=/usr

        # The zig CMakeLists uses build type Debug if not set
        # override it back to None so makepkg env vars are respected
        CMAKE_BUILD_TYPE=None

        ZIG_PIE=ON
        ZIG_SHARED_LLVM=ON
        ZIG_USE_LLVM_CONFIG=ON

        ZIG_TARGET_TRIPLE=native-linux.6.1-gnu.2.38
        ZIG_TARGET_MCPU=baseline
    )
    cmake -B build "${cmake_vars[@]/#/-D}" .
    cmake --build build
}

check() {
    cd "$pkgname-$pkgver"
    # ugly workaround until test target is provided
    # https://github.com/ziglang/zig/issues/14240
    DESTDIR="./testinstall" cmake --install build
    ./testinstall/usr/bin/zig build test -Dconfig_h=build/config.h \
      -Dstatic-llvm=false \
      -Denable-llvm=true \
      -Dskip-non-native=true
}

package() {
    cd "$pkgname-$pkgver"

    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"

    DESTDIR="$pkgdir" cmake --install build
}
```

Patch file can be found here: https://gitlab.archlinux.org/archlinux/packaging/packages/zig/-/raw/efb9e024bdf402b837433cadd2d4acc984ce2e71/skip-localhost-test.patch

To build use:
```
pkgctl build
```

**Comment by mlugg** [comment]
Hey everyone; if you're affected by this, and are able to build a Zig compiler, give #23645 a shot. I'm fairly sure it solves this, but since this is a race condition, I'd like to get confirmation from a few people before saying that confidently.

**Comment by selfisekai** [comment]
Seems to work good from the PR branch, passes `zig build test -Dcpu=baseline -Dskip-non-native -Dskip-translate-c`. Triggers an assertion instantly if applied on top of 0.14.0 though:
```
thread 15059 panic: reached unreachable code
/tmp/src/zig-0.14.0/build/stage3/lib/zig/std/debug.zig:522:14: 0x15225ed in assert (build)
    if (!ok) unreachable; // assertion failure
             ^
/tmp/src/zig-0.14.0/build/stage3/lib/zig/std/Progress.zig:310:15: 0x15de50b in init (build)
        assert(parent_ptr.* == .unused);
              ^
/tmp/src/zig-0.14.0/build/stage3/lib/zig/std/Progress.zig:194:28: 0x15c13e9 in start (build)
                return init(free_index, parent, name, estimated_total_items);
                           ^
/tmp/src/zig-0.14.0/build/stage3/lib/zig/compiler/build_runner.zig:1102:42: 0x1605f8d in workerMakeOneStep (build)
    const sub_prog_node = prog_node.start(s.name, 0);
                                         ^
/tmp/src/zig-0.14.0/build/stage3/lib/zig/std/Thread/Pool.zig:119:39: 0x1606935 in runFn (build)
            @call(.auto, func, closure.arguments);
                                      ^
/tmp/src/zig-0.14.0/build/stage3/lib/zig/std/Thread/Pool.zig:295:32: 0x16c49c4 in worker (build)
            run_node.data.runFn(&run_node.data, id);
                               ^
/tmp/src/zig-0.14.0/build/stage3/lib/zig/std/Thread.zig:488:13: 0x164362d in callFn__anon_102175 (build)
            @call(.auto, f, args);
            ^
/tmp/src/zig-0.14.0/build/stage3/lib/zig/std/Thread.zig:1378:30: 0x1605941 in entryFn (build)
                return callFn(f, self.fn_args);
                             ^
/tmp/src/zig-0.14.0/build/stage3/lib/zig/std/os/linux/x86_64.zig:126:5: 0x16436b1 in clone (build)
    asm volatile (
    ^
???:?:?: 0x0 in ??? (???)
error: the following build command crashed:
/tmp/src/zig-0.14.0/.zig-cache/o/62475d67e1bfa4d5ebbb1321ecbeb09b/build /tmp/src/zig-0.14.0/build/stage3/bin/zig build/stage3/lib/zig /tmp/src/zig-0.14.0 /tmp/src/zig-0.14.0/.zig-cache /home/lauren/.cache/zig --seed 0x563790a -Z95687f54df6c0288 test -Dcpu=baseline -Dskip-debug -Dskip-release-safe -Dskip-release-small -Dskip-non-native -Dskip-translate-c
>>> ERROR: zig: check failed
```

**Comment by erikarvstedt** [comment]
Thanks, with #23645 the bug has been fixed for me.
The repro script above now succeeds, and the correct number of `libcompiler_rt.a` instances (2 instead of 3) are created in the
global cache.

But I noticed that with #23645 a (probably unneded) `compiler_rt` step appears in `Compile build script` while ZLS runs.
Repro:
1. Run `zig init` to create a new Zig project
2. Run `zig build --help`
3. Open `build.zig` with a ZLS-enabled editor and make a trivial edit like adding some whitespace.
   Now ZLS automatically starts a `zig build --build-runner ...` process.
5. Right after the build runner process started, run `zig build --help`.
    You will notice a `compiler_rt` compile step appear in the progress output:
   ```
   [3] Compile Build Script
   ├─ Semantic Analysis
   ├─ [4] compiler_rt
   │  └─ LLVM Emit Object
   └─ Code Generation
   ```
This `compiler_rt`compile step only appears when the ZLS build runner process is running in parallel.
It doesn't appear with the latest zig master (`0.15.0-dev.384+c06fecd46`).
It appears even after non-functional edits to `build.zig` which should never affect `compiler_rt`.
I can create a repro script if it helps.

**Comment by gooncreeper** [comment]
It has fixed it for me

**Comment by achan1989** [comment]
I can reproduce the failure 100% on main using erikarvstedt's script above. After applying #23645 there was no failure in 5 runs.

**Comment by andrewrk** [comment]
#21663

**Comment by erikarvstedt** [comment]
Short correction: The unneeded `compiler_rt` compile step mentioned above also happens with Zig master.
I forgot to provide Zig master to ZLS while testing, so the  `compiler_rt` step wasn't triggered.
So #23645 is strictly an improvement over Zig master, adding no potentially faulty behavior.

I've now created a repro script.
Summary:
1. `zig init`
2. Run `zig build --help`
3. Add a non-functional change (i.e. a trailing newline) to `build.zig`
4. Run `zig build --help` with custom lib dir
5. Re-run `zig build --help`
    In this step, `compiler_rt` is rebuilt. This probably should  not happen because the `compiler_rt` source was not changed.

<details>
<summary>Repro script</summary>

```bash
#!/usr/bin/env bash
set -euo pipefail

# This script requires jq, rsync and script from util-linux, i.e. #!nix-shell -i bash -p jq rsync

trap 'echo "Error at ${BASH_SOURCE[0]}:$LINENO"' ERR

if [[ ! -t 1 ]]; then
    # We could work around this, but it would complicate this script.
    >&2 echo 'error: stdout must be a TTY'
    exit 1
fi

rm -rf /tmp/zig-cache-bug
mkdir -p /tmp/zig-cache-bug/src

# Create a copy of the zig lib at /tmp/zig-cache-bug/lib and modify a compiler_rt source file
# This is required to trigger the libcompiler_rt.a cache error.
{
    echo "creating lib dir"
    lib_dir=$(zig env | jq -r .lib_dir)
    if [[ $lib_dir == null ]]; then
        >&2 echo "error: couldn't find zig lib dir"
        exit 1
    fi
    rsync -a --delete --chmod=u+w --mkpath $lib_dir/ /tmp/zig-cache-bug/lib
    echo 'test "absvdi2" {}' > /tmp/zig-cache-bug/lib/compiler_rt/absvdi2_test.zig
}

cd /tmp/zig-cache-bug/src
zig init

cache_args=(--global-cache-dir /tmp/zig-cache-bug/global-cache --cache-dir /tmp/zig-cache-bug/local-cache)

echo 'Run initial `zig build`'
zig build --help "${cache_args[@]}"

echo "" >> build.zig
echo 'Run `zig build --zig-lib-dir ...`'
zig build --help --zig-lib-dir /tmp/zig-cache-bug/lib "${cache_args[@]}"

echo 'Re-run `zig build`'
cmd=(zig build --help "${cache_args[@]}")
script -q -c "${cmd[*]}" | tee /tmp/zig-cache-bug/build-output
wc -c /tmp/zig-cache-bug/build-output

if grep -q -F '] compiler_rt' /tmp/zig-cache-bug/build-output; then
    echo 'Progress output of the second `zig build` run contains a `compiler_rt` compile step'
else
    echo 'Success! compiler_rt is not rebuilt'
fi

```
</details>

**Comment by erikarvstedt** [comment]
@mlugg, is this [`compiler_rt` rebuild](https://github.com/ziglang/zig/issues/23110#issuecomment-2831423946) a (performance) bug? I'll create a new issue then.

**Comment by mlugg** [comment]
@erikarvstedt, I think your repro is expected behavior. Since the same cache directory is used regardless of `--zig-lib-dir`, changing your lib dir to one with different contents *should* invalidate the `compiler_rt` cache, and the rebuild essentially replaces the old cache, giving the behavior you observe. I still believe there could be a cache bug somewhere which causes over-eager rebuilds of `compiler_rt`, but I don't think your repro is it!
