### ISSUE TITLE
Ptrcast to C struct fails (related to #12957)

### ISSUE THREAD

**Issue by ryoppippi** [ziglang/zig#12967]
### Zig Version

0.10.0-dev.4166+cae76d829

### Steps to Reproduce

Run this repo
https://github.com/ryoppippi/zig-cast-with-c-bug

```point.c
typedef struct Point {
  int x;
  int y;
} Point;

typedef struct Points {
  Point *points;
  int length;
} Points;

```

``` main.zig
const std = @import("std");
const C = @cImport({
    @cInclude("point.c");
});
pub fn main() !void {
    const p = C.Point{ .x = 1, .y = 2 };
    const p_array = [_]C.Point{ p, p, p };

    const points = C.Points{
        .points = @ptrCast([*c]C.Point, &p_array),
        .length = p_array.len,
    };
    std.debug.print("{any}", .{points.points[2].x});
}
```

### Expected Behavior

```sh 
1
```
https://github.com/ryoppippi/zig-cast-with-c-bug/actions/runs/3123882732/jobs/5066825133

### Actual Behavior

```sh
/home/runner/work/zig-cast-with-c-bug/zig-cast-with-c-bug/src/main.zig:10:19: error: cast discards const qualifier
```
https://github.com/ryoppippi/zig-cast-with-c-bug/actions/runs/3123882732/jobs/5066825162

**Comment by ryoppippi** [comment]
If my code is wrong. Tell me how to fix it.
It worked on 0.10.0-dev.4060+61aaef0b0 before

**Comment by jacobly0** [comment]
Not being allowed to remove `const` with `@ptrCast` sounds correct to me.  In any case, you can either change `const p_array` to `var p_array`, or you can change `Point *points;` to `const Point *points;` and `[*c]C.Point` to `[*c]const C.Point` to avoid the `const` mismatch.

**Comment by ryoppippi** [comment]
@jacobly0 Thank you for your sugggestion
I tested your advice, and both suggestion worked.
However, I am confused as to why it worked so well before. Was it a bug?

**Comment by ryoppippi** [comment]
I also have a question.
```zig
const std = @import("std");
const C = @cImport({
    @cInclude("point.c");
});
pub fn main() !void {
    const p = C.Point{ .x = 1, .y = 2 };
    var p_array = [_]C.Point{ p, p, p };

    example(p_array[0..]);
}

pub fn example(p: []const C.Point) void {
    const points = C.Points{
        .points = @ptrCast([*c]C.Point, &p),
        .length = p.len,
    };
    std.debug.print("{any}", .{points[0].x});
}
```
This code raises error
`error: cast discards const qualifier`
and I know this is because the arguments of functions are constant.
But is there any good way to solve this error?

**Comment by jacobly0** [comment]
> However, I am confused as to why it worked so well before. Was it a bug?

The behavior changed with #12904.

> But is there any good way to solve this error?

That's not a result of arguments being constant (whether you can change a slice to point to something else is different than whether you can change the things it points to), instead it's because you specified that the function takes a slice of constant points, so you can't store them in a struct containing non-constant points.  The fix is to just change `p: []const C.Point` to `p: []C.Point`.

**Comment by ryoppippi** [comment]
> The behavior changed with https://github.com/ziglang/zig/pull/12904.
Ok I got it.

> The fix is to just change p: []const C.Point to p: []C.Point.
Thanks! it worked!!

Also I tried another examples. This also works when I use `var` instead of `const`
```c
#include "stdio.h"
typedef struct Point {
  int x;
  int y;
} Point;

typedef struct Points {
  Point *points;
  int length;
} Points;

void printPoint(Point *point) {
  printf("Point: (%d, %d) ", point->x, point->y);
}

void printPoints(Points *points) {
  for (int i = 0; i < points->length; i++) {
    printPoint(&points->points[i]);
  }
}
```
```zig
const std = @import("std");
const C = @cImport({
    @cInclude("point.c");
});
pub fn main() !void {
    const p = C.Point{ .x = 1, .y = 2 };
    var p_array = [_]C.Point{ p, p, p };

    example(&p_array);
}

pub fn example(p: []C.Point) void {
    for (p) |point| std.debug.print("x: {}, y: {}\n", .{ point.x, point.y });
    var points = C.Points{
        .points = @ptrCast([*c]C.Point, p),
        .length = @intCast(i32, p.len),
    };

    // std.debug.print("{any}", .{points.points[0]});
    C.printPoints(@ptrCast([*c]C.Points, &points));
}
```
