### ISSUE TITLE
Failed to build zig on Linux PPC64LE architecture

### ISSUE THREAD

**Issue by runlevel5** [ziglang/zig#25209]
### Zig Version

0.16.0-dev.229+bfda12efc

### Info

Host: Fedora 43 (ppc64le)
Compilers: clang version 21.1.0 (Fedora 21.1.0-1.fc43), gcc 15.2.1 20250808 (Red Hat 15.2.1-1), ldd (GNU libc) 2.42

### Steps to reproduce:

* `mkdir build && cd ./build && cmake .. && make -j32`

#### Expected:

* No errors

#### Actual:

* Errors

### Logs:

```
$ cmake ..
-- The C compiler identification is GNU 15.2.1
-- The CXX compiler identification is GNU 15.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring zig version 0.16.0-dev.229+bfda12efc
-- Found llvm: -lLLVM-21;-lrt;-ldl;-lm;-lz;-lzstd;-lxml2 (Required is at least version "21")
-- Found clang: /usr/lib64/llvm21/lib64/libclang-cpp.so.21.1 (Required is at least version "21")
-- Found lld: /usr/lib64/llvm21/lib64/liblldMinGW.so;/usr/lib64/llvm21/lib64/liblldELF.so;/usr/lib64/llvm21/lib64/liblldCOFF.so;/usr/lib64/llvm21/lib64/liblldWasm.so;/usr/lib64/llvm21/lib64/liblldMachO.so;/usr/lib64/llvm21/lib64/liblldCommon.so (Required is at least version "21")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Configuring done (1.0s)
-- Generating done (0.0s)
-- Build files have been written to: /home/tle/Work/zig-git/build

$ make -j32

# ...
/home/tle/Work/zig-git/build/zig2.c: In function ‘os_linux_powerpc64_syscall5__9058’:
/home/tle/Work/zig-git/build/zig2.c:601961:2: error: ‘asm’ specifier for variable ‘t3’ conflicts with ‘asm’ clobber list
601961 |  __asm volatile(" sc\n bns+ 1f\n neg 3, 3\n 1:": [ret]"=r"(t2): [number]"r"(t3), [arg1]"r"(t4), [arg2]"r"(t5), [arg3]"r"(t6), [arg4]"r"(t7), [arg5]"r"(t8): "memory", "cr0", "xer", "ctr", "r0", "r4", "r5", "r6", "r7", "r8", "r9", "r10", "r11", "r12");
       |  ^~~~~
/home/tle/Work/zig-git/build/zig2.c:601961:2: error: ‘asm’ specifier for variable ‘t5’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-git/build/zig2.c:601961:2: error: ‘asm’ specifier for variable ‘t6’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-git/build/zig2.c:601961:2: error: ‘asm’ specifier for variable ‘t7’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-git/build/zig2.c:601961:2: error: ‘asm’ specifier for variable ‘t8’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-git/build/zig2.c: In function ‘os_linux_powerpc64_syscall0__9053’:
/home/tle/Work/zig-git/build/zig2.c:909018:2: error: ‘asm’ specifier for variable ‘t3’ conflicts with ‘asm’ clobber list
909018 |  __asm volatile(" sc\n bns+ 1f\n neg 3, 3\n 1:": [ret]"=r"(t2): [number]"r"(t3): "memory", "cr0", "xer", "ctr", "r0", "r4", "r5", "r6", "r7", "r8", "r9", "r10", "r11", "r12");
       |  ^~~~~
/home/tle/Work/zig-git/build/zig2.c: In function ‘os_linux_powerpc64_syscall3__9056’:
/home/tle/Work/zig-git/build/zig2.c:1162308:2: error: ‘asm’ specifier for variable ‘t3’ conflicts with ‘asm’ clobber list
1162308 |  __asm volatile(" sc\n bns+ 1f\n neg 3, 3\n 1:": [ret]"=r"(t2): [number]"r"(t3), [arg1]"r"(t4), [arg2]"r"(t5), [arg3]"r"(t6): "memory", "cr0", "xer", "ctr", "r0", "r4", "r5", "r6", "r7", "r8", "r9", "r10", "r11", "r12");
        |  ^~~~~
/home/tle/Work/zig-git/build/zig2.c:1162308:2: error: ‘asm’ specifier for variable ‘t5’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-git/build/zig2.c:1162308:2: error: ‘asm’ specifier for variable ‘t6’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-git/build/zig2.c: In function ‘os_linux_powerpc64_syscall4__9057’:
/home/tle/Work/zig-git/build/zig2.c:1525360:2: error: ‘asm’ specifier for variable ‘t3’ conflicts with ‘asm’ clobber list
1525360 |  __asm volatile(" sc\n bns+ 1f\n neg 3, 3\n 1:": [ret]"=r"(t2): [number]"r"(t3), [arg1]"r"(t4), [arg2]"r"(t5), [arg3]"r"(t6), [arg4]"r"(t7): "memory", "cr0", "xer", "ctr", "r0", "r4", "r5", "r6", "r7", "r8", "r9", "r10", "r11", "r12");
        |  ^~~~~
/home/tle/Work/zig-git/build/zig2.c:1525360:2: error: ‘asm’ specifier for variable ‘t5’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-git/build/zig2.c:1525360:2: error: ‘asm’ specifier for variable ‘t6’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-git/build/zig2.c:1525360:2: error: ‘asm’ specifier for variable ‘t7’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-git/build/zig2.c: In function ‘os_linux_powerpc64_syscall6__9059’:
/home/tle/Work/zig-git/build/zig2.c:2955242:2: error: ‘asm’ specifier for variable ‘t3’ conflicts with ‘asm’ clobber list
2955242 |  __asm volatile(" sc\n bns+ 1f\n neg 3, 3\n 1:": [ret]"=r"(t2): [number]"r"(t3), [arg1]"r"(t4), [arg2]"r"(t5), [arg3]"r"(t6), [arg4]"r"(t7), [arg5]"r"(t8), [arg6]"r"(t9): "memory", "cr0", "xer", "ctr", "r0", "r4", "r5", "r6", "r7", "r8", "r9", "r10", "r11", "r12");
        |  ^~~~~
/home/tle/Work/zig-git/build/zig2.c:2955242:2: error: ‘asm’ specifier for variable ‘t5’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-git/build/zig2.c:2955242:2: error: ‘asm’ specifier for variable ‘t6’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-git/build/zig2.c:2955242:2: error: ‘asm’ specifier for variable ‘t7’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-git/build/zig2.c:2955242:2: error: ‘asm’ specifier for variable ‘t8’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-git/build/zig2.c:2955242:2: error: ‘asm’ specifier for variable ‘t9’ conflicts with ‘asm’ clobber list
make[2]: *** [CMakeFiles/zig2.dir/build.make:961: CMakeFiles/zig2.dir/zig2.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:196: CMakeFiles/zig2.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

## Additional information

This issue also impact the `0.15.1` version:

```
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c: In function ‘os_linux_powerpc64_syscall5__10009’:
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c:597421:2: error: ‘asm’ specifier for variable ‘t3’ conflicts with ‘asm’ clobber list
597421 |  __asm volatile(" sc\n bns+ 1f\n neg 3, 3\n 1:": [ret]"=r"(t2): [number]"r"(t3), [arg1]"r"(t4), [arg2]"r"(t5), [arg3]"r"(t6), [arg4]"r"(t7), [arg5]"r"(t8): "memory", "cr0", "r0", "r4", "r5", "r6", "r7", "r8", "r9", "r10", "r11", "r12");
       |  ^~~~~
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c:597421:2: error: ‘asm’ specifier for variable ‘t5’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c:597421:2: error: ‘asm’ specifier for variable ‘t6’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c:597421:2: error: ‘asm’ specifier for variable ‘t7’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c:597421:2: error: ‘asm’ specifier for variable ‘t8’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c: In function ‘os_linux_powerpc64_syscall0__10004’:
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c:909495:2: error: ‘asm’ specifier for variable ‘t3’ conflicts with ‘asm’ clobber list
909495 |  __asm volatile(" sc\n bns+ 1f\n neg 3, 3\n 1:": [ret]"=r"(t2): [number]"r"(t3): "memory", "cr0", "r0", "r4", "r5", "r6", "r7", "r8", "r9", "r10", "r11", "r12");
       |  ^~~~~
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c: In function ‘os_linux_powerpc64_syscall3__10007’:
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c:1163789:2: error: ‘asm’ specifier for variable ‘t3’ conflicts with ‘asm’ clobber list
1163789 |  __asm volatile(" sc\n bns+ 1f\n neg 3, 3\n 1:": [ret]"=r"(t2): [number]"r"(t3), [arg1]"r"(t4), [arg2]"r"(t5), [arg3]"r"(t6): "memory", "cr0", "r0", "r4", "r5", "r6", "r7", "r8", "r9", "r10", "r11", "r12");
        |  ^~~~~
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c:1163789:2: error: ‘asm’ specifier for variable ‘t5’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c:1163789:2: error: ‘asm’ specifier for variable ‘t6’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c: In function ‘os_linux_powerpc64_syscall4__10008’:
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c:1529749:2: error: ‘asm’ specifier for variable ‘t3’ conflicts with ‘asm’ clobber list
1529749 |  __asm volatile(" sc\n bns+ 1f\n neg 3, 3\n 1:": [ret]"=r"(t2): [number]"r"(t3), [arg1]"r"(t4), [arg2]"r"(t5), [arg3]"r"(t6), [arg4]"r"(t7): "memory", "cr0", "r0", "r4", "r5", "r6", "r7", "r8", "r9", "r10", "r11", "r12");
        |  ^~~~~
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c:1529749:2: error: ‘asm’ specifier for variable ‘t5’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c:1529749:2: error: ‘asm’ specifier for variable ‘t6’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c:1529749:2: error: ‘asm’ specifier for variable ‘t7’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c: In function ‘os_linux_powerpc64_syscall6__10010’:
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c:2966728:2: error: ‘asm’ specifier for variable ‘t3’ conflicts with ‘asm’ clobber list
2966728 |  __asm volatile(" sc\n bns+ 1f\n neg 3, 3\n 1:": [ret]"=r"(t2): [number]"r"(t3), [arg1]"r"(t4), [arg2]"r"(t5), [arg3]"r"(t6), [arg4]"r"(t7), [arg5]"r"(t8), [arg6]"r"(t9): "memory", "cr0", "r0", "r4", "r5", "r6", "r7", "r8", "r9", "r10", "r11", "r12");
        |  ^~~~~
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c:2966728:2: error: ‘asm’ specifier for variable ‘t5’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c:2966728:2: error: ‘asm’ specifier for variable ‘t6’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c:2966728:2: error: ‘asm’ specifier for variable ‘t7’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c:2966728:2: error: ‘asm’ specifier for variable ‘t8’ conflicts with ‘asm’ clobber list
/home/tle/Work/zig-bootstrap-0.15.1/zig/build/zig2.c:2966728:2: error: ‘asm’ specifier for variable ‘t9’ conflicts with ‘asm’ clobber list
make[2]: *** [CMakeFiles/zig2.dir/build.make:961: CMakeFiles/zig2.dir/zig2.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:196: CMakeFiles/zig2.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by alexrp** [comment]
Looks like a CBE bug to me; it clearly shouldn't be outputting just `r` for every input when the Zig source uses `r0`, `r1`, etc.

**Comment by jacobly0** [comment]
> Looks like a CBE bug to me; it clearly shouldn't be outputting just `r` for every input when the Zig source uses `r0`, `r1`, etc.

You must be thinking of llvm asm syntax, C asm syntax just looks like that for specific registers which are specified out of line.

**Comment by alexrp** [comment]
Looks like a regression introduced in #24238, cc @taylordotfish.

**Comment by taylordotfish** [comment]
The list of input registers looks correct to me; in the error message I can see that `syscall0` has only one `"r"` input, whereas `syscall5` has 6, as expected.

The issue appears to be that `r0` is specified as both an output and a clobber. This is indeed one of the changes made in #24238; previously `r0` was specified only as an input. The reason for this change is that syscalls on PowerPC can modify `r0`, so we need to inform the compiler that it can't rely on `r0` having a stable value (I could see this being an issue if the same syscall is executed twice, and the compiler assumes `r0` still contains the syscall number after the first call).

[musl](https://git.musl-libc.org/cgit/musl/tree/arch/powerpc64/syscall_arch.h?id=f6944eb3c4ce1c97dc39dc36d32390dc9f70b67b#n9) and [glibc](https://github.com/bminor/glibc/blob/glibc-2.41/sysdeps/unix/sysv/linux/powerpc/sysdep.h#L113-L115) both use a `+` constraint to indicate the register is read-write, but that doesn't seem to be supported in Zig, at least for the C backend:

```
/opt/zig/lib/std/os/linux/powerpc64.zig:17:5: error: CBE: constraint not supported: '+{r0}'
pub fn syscall0(number: SYS) usize {
~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

We also can't add `r0` as an output, since `r3` is already an output and multiple outputs aren't supported. I'm not sure what the best solution is. Removing `r0` as a clobber would fix the compilation errors, but I think that would be unsound for the reason described above.

Maybe we need to add a separate `asm volatile` that clobbers `r0`?

```zig
pub fn syscall0(number: SYS) usize {
    const result = asm volatile (
        \\ sc
        \\ bns+ 1f
        \\ neg 3, 3
        \\ 1:
        : [ret] "={r3}" (-> usize),
        : [number] "{r0}" (@intFromEnum(number)),
        : .{ .memory = true, .cr0 = true, .r4 = true, .r5 = true, .r6 = true, .r7 = true, .r8 = true, .r9 = true, .r10 = true, .r11 = true, .r12 = true, .ctr = true, .xer = true });
    asm volatile ("" ::: .{ .r0 = true });
    return result;
}
```

If that's an acceptable solution, I can make a PR.

**Comment by jacobly0** [comment]
Multiple outputs are supported, only the `->` syntax is restricted to one occurrence.
Multiple `asm` blocks are never valid because the compiler could decide to assume `r0` is not clobbered between the two blocks and only save it for the final block.

**Comment by taylordotfish** [comment]
Got it, something like this, then?

```zig
pub fn syscall0(number: SYS) usize {
    var r0_out: usize = undefined;
    return asm volatile (
        \\ sc
        \\ bns+ 1f
        \\ neg 3, 3
        \\ 1:
        : [ret] "={r3}" (-> usize), [r0_out] "={r0}" (r0_out),
        : [number] "{r0}" (@intFromEnum(number)),
        : .{ .memory = true, .cr0 = true, r4 = true, .r5 = true, .r6 = true, .r7 = true, .r8 = true, .r9 = true, .r10 = true, .r11 = true, .r12 = true, .ctr = true, .xer = true });
}
```

Or alternatively:

```zig
pub fn syscall0(number: SYS) usize {
    var r0 = @intFromEnum(number);
    return asm volatile (
        \\ sc
        \\ bns+ 1f
        \\ neg 3, 3
        \\ 1:
        : [ret] "={r3}" (-> usize), [r0_out] "={r0}" (r0),
        : [number] "{r0}" (r0),
        : .{ .memory = true, .cr0 = true, .r4 = true, .r5 = true, .r6 = true, .r7 = true, .r8 = true, .r9 = true, .r10 = true, .r11 = true, .r12 = true, .ctr = true, .xer = true });
}
```

Both look like they do the right thing when compiled to C:

<details>
<summary>First implementation</summary>
<pre lang="c"><code>static uintptr_t os_linux_powerpc64_syscall0__3117(uintptr_t const a0) {
 uintptr_t t1;
 uintptr_t t2;
 uintptr_t t0;
 /* file:2:5 */
 /* dbg_var_ptr:r0_out */
 /* file:3:5 */
 t1 = a0;
 register uintptr_t t3 __asm("r3");
 register uintptr_t t4 __asm("r0");
 register uintptr_t const t5 __asm("r0") = t1;
 __asm volatile(" sc\n bns+ 1f\n neg 3, 3\n 1:": [ret]"=r"(t3), [r0_out]"=r"(t4): [number]"r"(t5): "memory", "cr0", "xer", "ctr", "r4", "r5", "r6", "r7", "r8", "r9", "r10", "r11", "r12");
 t2 = t3;
 t0 = t4;
 /* file:3:5 */
 return t2;
}
</code></pre>
</details>

<details>
<summary>Second implementation</summary>
<pre lang="c"><code>static uintptr_t os_linux_powerpc64_syscall0__3117(uintptr_t const a0) {
 uintptr_t t1;
 uintptr_t t2;
 uintptr_t t0;
 /* file:2:5 */
 t1 = a0;
 t0 = t1;
 /* dbg_var_ptr:r0 */
 /* file:3:5 */
 t1 = t0;
 register uintptr_t t3 __asm("r3");
 register uintptr_t t4 __asm("r0");
 register uintptr_t const t5 __asm("r0") = t1;
 __asm volatile(" sc\n bns+ 1f\n neg 3, 3\n 1:": [ret]"=r"(t3), [r0_out]"=r"(t4): [number]"r"(t5): "memory", "cr0", "xer", "ctr", "r4", "r5", "r6", "r7", "r8", "r9", "r10", "r11", "r12");
 t2 = t3;
 t0 = t4;
 /* file:3:5 */
 return t2;
}
</code></pre>
</details>

**Comment by runlevel5** [comment]
@taylordotfish great thanks for looking into this issue. I would like to ask if it is possible to backport the fix to the `0.15.x` branch. The reason behind is that Fedora 43 could ship the backport patch downstream if 0.15.2 is not out by the Fedora 43 release date. Many thanks

**Comment by taylordotfish** [comment]
@runlevel5 Sure, the commits from #25229 and #25231 apply cleanly to 0.15.x without any conflicts. I just pushed a [0.15.x+ppc](https://github.com/taylordotfish/zig/commits/0.15.x%2Bppc/) branch to my fork with these changes applied.

**Comment by runlevel5** [comment]
@taylordotfish I've just tried to compile your `0.15.x+ppc` branch. The build get further but failed with lots of messages:

```sh
[ 68%] Built target zigcpp
[ 73%] Building C object CMakeFiles/zig2.dir/zig2.c.o

#... stripped out like hundreds of Error: operand out of range
/tmp/ccWCvB3M.s:17455599: Error: operand out of range (0xfffffffffd3e9718 is not between 0xfffffffffe000000 and 0x1fffffc)
/tmp/ccWCvB3M.s:17455835: Error: operand out of range (0xfffffffffd3e94ac is not between 0xfffffffffe000000 and 0x1fffffc)
/tmp/ccWCvB3M.s:17456511: Error: operand out of range (0xfffffffffd3a95c0 is not between 0xfffffffffe000000 and 0x1fffffc)
/tmp/ccWCvB3M.s:17456516: Error: operand out of range (0xfffffffffd3a94bc is not between 0xfffffffffe000000 and 0x1fffffc)
/tmp/ccWCvB3M.s:17456548: Error: operand out of range (0xfffffffffd3a9560 is not between 0xfffffffffe000000 and 0x1fffffc)
/tmp/ccWCvB3M.s:17456553: Error: operand out of range (0xfffffffffd3a945c is not between 0xfffffffffe000000 and 0x1fffffc)
/tmp/ccWCvB3M.s:17456596: Error: operand out of range (0xfffffffffd3a94dc is not between 0xfffffffffe000000 and 0x1fffffc)
/tmp/ccWCvB3M.s:17456601: Error: operand out of range (0xfffffffffd3a93d8 is not between 0xfffffffffe000000 and 0x1fffffc)
/tmp/ccWCvB3M.s:17456633: Error: operand out of range (0xfffffffffd3a947c is not between 0xfffffffffe000000 and 0x1fffffc)
/tmp/ccWCvB3M.s:17456638: Error: operand out of range (0xfffffffffd3a9378 is not between 0xfffffffffe000000 and 0x1fffffc)
/tmp/ccWCvB3M.s:17456728: Error: operand out of range (0xfffffffffd3a9380 is not between 0xfffffffffe000000 and 0x1fffffc)
/tmp/ccWCvB3M.s:17456733: Error: operand out of range (0xfffffffffd3a927c is not between 0xfffffffffe000000 and 0x1fffffc)
/tmp/ccWCvB3M.s:17456765: Error: operand out of range (0xfffffffffd3a9320 is not between 0xfffffffffe000000 and 0x1fffffc)
/tmp/ccWCvB3M.s:17456770: Error: operand out of range (0xfffffffffd3a921c is not between 0xfffffffffe000000 and 0x1fffffc)
/tmp/ccWCvB3M.s:17456817: Error: operand out of range (0xfffffffffd3a9298 is not between 0xfffffffffe000000 and 0x1fffffc)
/tmp/ccWCvB3M.s:17456822: Error: operand out of range (0xfffffffffd3a9194 is not between 0xfffffffffe000000 and 0x1fffffc)
/tmp/ccWCvB3M.s:17456854: Error: operand out of range (0xfffffffffd3a9238 is not between 0xfffffffffe000000 and 0x1fffffc)
/tmp/ccWCvB3M.s:17456859: Error: operand out of range (0xfffffffffd3a9134 is not between 0xfffffffffe000000 and 0x1fffffc)
/tmp/ccWCvB3M.s:17457149: Error: operand out of range (0xfffffffffd4da294 is not between 0xfffffffffe000000 and 0x1fffffc)
/tmp/ccWCvB3M.s:17457280: Error: operand out of range (0xfffffffffd6f03d0 is not between 0xfffffffffe000000 and 0x1fffffc)
make[2]: *** [CMakeFiles/zig2.dir/build.make:961: CMakeFiles/zig2.dir/zig2.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:196: CMakeFiles/zig2.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by alexrp** [comment]
#24568

**Comment by runlevel5** [comment]
@alexrp 

Your suggested changes work for me:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index ebdce53228..2ef97ec9b7 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -821,7 +821,7 @@ if(MSVC)
 else()
   set(ZIG_WASM2C_COMPILE_FLAGS "-std=c99 -O2")
   set(ZIG1_COMPILE_FLAGS "-std=c99 -Os")
-  set(ZIG2_COMPILE_FLAGS "-std=c99 -O0 -fno-stack-protector")
+  set(ZIG2_COMPILE_FLAGS "-std=c99 -Os -fno-stack-protector")
   if(APPLE)
     set(ZIG2_LINK_FLAGS "-Wl,-stack_size,0x10000000")
   elseif(MINGW)
```


Perhaps we should have a condition check ppc64le and use `Os`? Ideally we should get try to understand _exactly_ which flag in the `-O0` set that caused the issue but that could be hard
