### ISSUE TITLE
Some cimports have regressed and are now failing with `use of unknown builtin`

### ISSUE THREAD

**Issue by IntegratedQuantum** [ziglang/zig#25590]
### Zig Version

0.16.0-dev.731+958faa703

### Steps to Reproduce and Observed Behavior

Try importing the following windows header:
```zig
const std = @import("std");

const c = @cImport({
	@cInclude("fileapi.h");
});

pub fn main() void {
	_ = c;
}
```
Now cross compile it for windows and observe a bunch of errors:
```
$ zig build-exe test.zig -target x86_64-windows-gnu -lc
test.zig:3:11: error: C import failed
const c = @cImport({
          ^~~~~~~~
referenced by:
    main: test.zig:8:6
    callMain [inlined]: /home/mint/Cubyz/compiler/zig/lib/std/start.zig:618:22
    callMainWithArgs [inlined]: /home/mint/Cubyz/compiler/zig/lib/std/start.zig:587:20
    main: /home/mint/Cubyz/compiler/zig/lib/std/start.zig:602:28
    1 reference(s) hidden; use '-freference-trace=5' to see all references
error: translation failure
/home/mint/Cubyz/compiler/zig/lib/include/xmmintrin.h:3197:27: error: function-like macro '__building_module' is not defined
#if defined(__SSE2__) && !__building_module(_Builtin_intrinsics)
                          ^
/home/mint/Cubyz/compiler/zig/lib/libc/include/any-windows-any/psdk_inc/intrin-impl.h:679:5: error: use of unknown builtin '__builtin_ia32_sfence'
    __builtin_ia32_sfence();
    ^
/home/mint/Cubyz/compiler/zig/lib/libc/include/any-windows-any/psdk_inc/intrin-impl.h:752:1: error: returning 'void' from a function with incompatible result type 'long long'
__buildlogicali(_InterlockedAnd64, __int64, and)
... (5000 more errors like this)
```

Note that this is not the only header that fails for me, there are also some headers where it works in debug mode, but fails in release.

### Expected Behavior

It worked in 0.15.2:
```
$ ~/Downloads/zig-x86_64-linux-0.15.2/zig build-exe test.zig -target x86_64-windows-gnu -lc
$
```
