### ISSUE TITLE
const sized array of extern structs causes std.mem.zeroes to error: out of bounds pointer access.

### ISSUE THREAD

**Issue by JesseRMeyer** [ziglang/zig#4946]
Regression, I believe, in https://github.com/ziglang/zig/commit/ef419dd72d3fc9ec1454099367bd8d43f1b5037b.

0.5.0+cd20e0cc6

```zig
const zeros = @import("std").mem.zeroes;

pub export fn main() u8 {
    const some_struct = extern struct {
        someField: u8,
    };

    var hello = zeros([1]some_struct);

    return 1;
}
```

```zig build-exe test2.zig```

```
C:\dev\Zig\lib\zig\std\mem.zig:320:52: error: out of bounds pointer access
                @memset(@ptrCast([*]u8, &item), 0, @sizeOf(T));
                                                   ^
C:\dev\Zig\lib\zig\std\mem.zig:344:40: note: called from here
            return [_]info.child{zeroes(info.child)} ** info.len;
                                       ^
.\test2.zig:10:22: note: called from here
    var hello = zeros([1]some_struct);
                     ^
.\test2.zig:3:25: note: called from here
pub export fn main() u8 {
                        ^
C:\dev\Zig\lib\zig\std\mem.zig:320:17: note: referenced here
                @memset(@ptrCast([*]u8, &item), 0, @sizeOf(T));
                ^
C:\dev\Zig\lib\zig\std\mem.zig:344:40: note: referenced here
            return [_]info.child{zeroes(info.child)} ** info.len;
```

Remove either extern, or the array size specifier and the compiler succeeds.
