### PR TITLE
linuxWaitFd: make NetworkSubsystemFailed error unreachable

### LINKED ISSUE #6794: Compile error "NetworkSubsystemFailed not handled in switch" in reading file in `io_mode = .evented`
The code below compiles fine with Zig 0.6.0, but fails to compile with error "NetworkSubsystemFailed not handled in switch" in std/event/loop.zig, with latest master (0.6.0+91a1c20e7).  (This is on Linux.)

build.zig:
```zig
const Builder = @import("std").build.Builder;
pub fn build(b: *Builder) void {
    var exe = b.addExecutable("x", "x.zig");
    b.default_step.dependOn(&exe.step);
}
```
x.zig:
```zig
pub const io_mode = .evented;
const std = @import("std");
pub fn main() !void {
    const f = try std.fs.cwd().openFile("smallfile.txt", .{});
    var buffer: [100]u8 = undefined;
    _ = try f.readAll(&buffer);
}
```

The compile error is
```
$ zig build
/home/marnix/bin/zig-linux-x86_64-0.6.0+91a1c20e7/lib/zig/std/event/loop.zig:468:60: error: error.NetworkSubsystemFailed not handled in switch
                    _ = os.poll(&pfd, -1) catch |poll_err| switch (poll_err) {
                                                           ^
/home/marnix/bin/zig-linux-x86_64-0.6.0+91a1c20e7/lib/zig/std/event/loop.zig:474:37: note: referenced here
                            std.time.sleep(1 * std.time.ns_per_ms);
                                    ^
/home/marnix/bin/zig-linux-x86_64-0.6.0+91a1c20e7/lib/zig/std/event/loop.zig:443:39: note: referenced here
        defer if (need_to_delete) self.linuxRemoveFd(fd);
                                      ^
/home/marnix/bin/zig-linux-x86_64-0.6.0+91a1c20e7/lib/zig/std/event/loop.zig:432:63: note: referenced here
    pub fn linuxWaitFd(self: *Loop, fd: i32, flags: u32) void {
                                                              ^
/home/marnix/bin/zig-linux-x86_64-0.6.0+91a1c20e7/lib/zig/std/event/loop.zig:1009:49: note: when analyzing type '@Frame(std.event.loop.Loop.read)' here
                        self.waitUntilFdReadable(fd);
                                                ^
/home/marnix/bin/zig-linux-x86_64-0.6.0+91a1c20e7/lib/zig/std/fs/file.zig:422:50: note: while checking if 'std.fs.file.File.read' is async
            return std.event.Loop.instance.?.read(self.handle, buffer, self.capable_io_mode != self.intended_io_mode);
                                                 ^
/home/marnix/bin/zig-linux-x86_64-0.6.0+91a1c20e7/lib/zig/std/fs/file.zig:431:38: note: while checking if 'std.fs.file.File.readAll' is async
            const amt = try self.read(buffer[index..]);
                                     ^
./x.zig:6:22: note: when analyzing type '@Frame(main)' here
    _ = try f.readAll(&buffer);
                     ^
/home/marnix/bin/zig-linux-x86_64-0.6.0+91a1c20e7/lib/zig/std/start.zig:326:37: note: while checking if 'std.start.callMain' is async
            const result = root.main() catch |err| {
                                    ^
/home/marnix/bin/zig-linux-x86_64-0.6.0+91a1c20e7/lib/zig/std/start.zig:259:48: note: referenced here
            var frame: @Frame(callMainAsync) = undefined;
                                               ^
x...The following command exited with error code 1:
/home/marnix/bin/zig-linux-x86_64-0.6.0+91a1c20e7/zig build-exe /media/marnux3data/data/projects/zig-mm/tmp/x.zig --cache-dir /media/marnux3data/data/projects/zig-mm/tmp/zig-cache --name x --enable-cache
error: the following build command failed with exit code 1:
/media/marnux3data/data/projects/zig-mm/tmp/zig-cache/o/c661213d782e893ae2ae2b6dfdeabc0e/build /home/marnix/bin/zig-linux-x86_64-0.6.0+91a1c20e7/zig /media/marnux3data/data/projects/zig-mm/tmp /media/marnux3data/data/projects/zig-mm/tmp/zig-cache
```

### PR DESCRIPTION
**Pull request by heidezomp**
This error from os.poll is Windows-specific, so unreachable on Linux.

Closes #6794

### CODE REVIEW

**Comment by heidezomp** [comment]
Rebased PR on top of master to hopefully fix spurious CI failures.

**Comment by heidezomp** [comment]
The macOS build keeps failing in a test which seems to be comparing some translate-c output, but I'm not sure how to even read/diagnose the build output. Seems to be completely unrelated to this PR though.

**Comment by andrewrk** [comment]
It's the pinned issue: #6830

Been trying to figure it out all day, sorry about that.

**Comment by heidezomp** [comment]
> It's the pinned issue: #6830
> 
> Been trying to figure it out all day, sorry about that.

Note to self: Read the actual pinned issues when something fishy seems to be going on! :smile:

**Comment by heidezomp** [comment]
Rebased PR on top of master once more now that #6830 is fixed.

**Comment by heidezomp** [comment]
This was fixed concurrently by @ifreund in 1b34365ca1f7222a82054ece1901ffb87ffc8b21; rebased/updated my PR to make the error unreachable.

**Comment by ifreund** [comment]
> This was fixed concurrently by @ifreund in 1b34365; rebased/updated my PR to make the error unreachable.

IMO leaking the abstraction of `std.os` and making it unreachable isn't the way to go. perhaps the errorset could exclude that error when not using windows?

**Comment by heidezomp** [comment]
> IMO leaking the abstraction of `std.os` and making it unreachable isn't the way to go. perhaps the errorset could exclude that error when not using windows?

Since the #6600 proposal to get rid of/rework `std.os` has been accepted, perhaps we should defer this decision and decide this (how error sets deal with OS-specific errors) for the new high-level OS abstraction as a whole?

**Comment by andrewrk** [comment]
> Since the #6600 proposal to get rid of/rework `std.os` has been accepted, perhaps we should defer this decision and decide this (how error sets deal with OS-specific errors) for the new high-level OS abstraction as a whole?

I think your change is a nice improvement in the meantime :)
