### ISSUE TITLE
stage2 runs tests without ensuring compiled succesfully

### ISSUE THREAD

**Issue by alichraghi** [ziglang/zig#12391]
### Zig Version

0.10.0-dev.3475+b3d463c9e

### Steps to Reproduce

```zig
const std = @import("std");

test "simple" {
    std.testing.expectEqual(1, funk());
}

fn funk() u32 {
    return 1;
}
```
```
$ zig test my_zig_bug.zig -fno-stage1
```

### Expected Behavior

A compile error like stage1:
```
error: expected type 'comptime_int', found 'u32'
    std.testing.expectEqual(1, funk());
```

### Actual Behavior

```
LLD Link... ld.lld: error: undefined symbol: my_zig_bug.test.simple
>>> referenced by test
>>>               zig-cache/o/4cbd721d4f6fa40aa5e58ed50ffd442f/test.o:(builtin.test_functions__anon_8969)
error: the following command failed with 'FileNotFound':
zig-cache/o/4cbd721d4f6fa40aa5e58ed50ffd442f/test /home/ali/clone/zig/zig
```
here, stage2 doesn't print compilation error, and continues running test

**Comment by Vexu** [comment]
Seems to work correctly with `0.10.0-dev.3758+56e14a3a7`
