### ISSUE TITLE
Tagged Union variable initialised with void cannot be reused with other value

### ISSUE THREAD

**Issue by samhattangady** [ziglang/zig#10253]
### Zig Version

0.9.0-dev.1815+20e19e75f

### Steps to Reproduce

1. Create a `tagged union` where one of the values is void, and the other is not.
2. Initialise a variable of that type, with the void value selected.
3. Try to update the variable to the non-void type.

``` zig
const std = @import("std");

const ResponseType = enum {
    okay,
    err,
};

const Response = union(ResponseType) {
    err: usize,
    okay: void,
};

pub fn main() anyerror!void {
    // This will fail to compile - error: no member named 'err' in enum 'ResponseType'
    var resp = Response.okay;
    resp = Response{ .err = 1 };

    // // This variant will succeed
    // var resp = Response{ .err = 1 };
    // resp = Response.okay;
}
```

### Expected Behavior

The variable should be correctly updated with the value that we want to set.

### Actual Behavior

The code fails to compile, and gives an error.

``` zig
error: no member named 'err' in enum 'ResponseType'
```

It seems that there is an issue with the [type coercion](https://ziglang.org/documentation/master/#Type-Coercion-unions-and-enums). The compiler error tells us that the variable is an enum `ResponseType`, when it should be a union `Response`.

This may be related to the bug GH-9483.

**Comment by Daggerfall-is-the-best-TES-game** [comment]
This compiles on zig-0.14.0-dev.154+768b17755 so I think this issue has been fixed
