### ISSUE TITLE
Regression: `must be declared comptime` error happens in comptime scope

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#16454]
### Zig Version

0.11.0-dev.4006+bf827d0b5

### Steps to Reproduce and Observed Behavior

Code

```zig
const std = @import("std");
pub fn getExternList(comptime Type: type) []const []const u8 {
    return comptime &brk: {
        const Sorder = struct {
            abc: type,
            pub fn lessThan(comptime _: @This(), lhs: []const u8, rhs: []const u8) bool {
                return std.ascii.orderIgnoreCase(lhs, rhs) == std.math.Order.lt;
            }
        };
        var extern_list = Type.Extern;
        std.sort.block([]const u8, &extern_list, Sorder{
            .abc = Type,
        }, Sorder.lessThan);
        break :brk extern_list;
    };
}
test {
    _ = getExternList(struct {
        pub const Extern = [_][]const u8{ "hey", "hi", "yooo" };
    })[0];
}
```

Run

```bash
zig test repro.zig
```

Error:

```zig
/Users/jarred/zig/0.11.0-dev.4006+bf827d0b5/files/lib/std/sort/block.zig:107:21: error: parameter of type 'repro.getExternList__anon_965__struct_1749' must be declared comptime
        fn lessThan(ctx: @TypeOf(context), lhs: T, rhs: T) bool {
                    ^~~~~~~~~~~~~~~~~~~~~
/Users/jarred/Desktop/repro.zig:5:18: note: struct requires comptime because of this field
            abc: type,
                 ^~~~
/Users/jarred/Desktop/repro.zig:5:18: note: types are not available at runtime
            abc: type,
                 ^~~~
/Users/jarred/Desktop/repro.zig:4:24: note: struct declared here
        const Sorder = struct {
                       ^~~~~~
referenced by:
    block: /Users/jarred/zig/0.11.0-dev.4006+bf827d0b5/files/lib/std/sort/block.zig:113:6
    block: /Users/jarred/zig/0.11.0-dev.4006+bf827d0b5/files/lib/std/sort.zig:7:44
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

### Expected Behavior

The test should pass as it is only called at comptime 

This worked in `0.11.0-dev.3771+128fd7dd0`:
> All 1 tests passed.

**Comment by mlugg** [comment]
This'll be caused by @andrewrk's changes to generic functions. There used to be logic to prevent `parameter must be declared comptime` (etc) errors from being issues in generic code, to allow for generic code like this to be agnostic as to whether a type is comptime-only.

**Comment by rohlem** [comment]
Note that the [working commit specified](https://github.com/ziglang/zig/commit/128fd7dd0) is from `master` 06-21 (after the merge of `intern-pool-3` https://github.com/ziglang/zig/commit/529ef75101e21bd45402c516138343b4770238eb and `intern-pool-opt` https://github.com/ziglang/zig/commit/12813d5912c55d6b290690d821a782d6c756f11c).
The [commit this issue was created for](https://github.com/ziglang/zig/commit/bf827d0b5) is from `master` 07-17, which is still _before_ the recent merge of `rework-generics` https://github.com/ziglang/zig/commit/0aacb6369fdf3762b7ab6069955684abb63f1459. (I assume that's what @mlugg was referring to?)

I actually couldn't find a change obviously responsible for this between these two commits. But either way it may be worth retrying with a build after "rework generics" (aka a build number >= `dev.4057` I think).

**Comment by mlugg** [comment]
> The [commit this issue was created for](https://github.com/ziglang/zig/commit/bf827d0b5) is from `master` 07-17, which is still _before_ the recent merge of `rework-generics` [0aacb63](https://github.com/ziglang/zig/commit/0aacb6369fdf3762b7ab6069955684abb63f1459). (I assume that's what @mlugg was referring to?)

Whoops, you're totally right, my bad! No idea what exactly is causing this then.

**Comment by iacore** [comment]
Other than regression, this seems more like improper use of the standard library. The error message is not helping though.

```zig
const std = @import("std");

pub fn getExternList(comptime Type: type) []const []const u8 {
    const Sorter = struct {
        pub fn lessThan(_: void, lhs: []const u8, rhs: []const u8) bool {
            return std.ascii.orderIgnoreCase(lhs, rhs) == std.math.Order.lt;
        }
    };
    var extern_list = Type.Extern;
    std.sort.block([]const u8, &extern_list, void{}, Sorter.lessThan);
    return &extern_list;
}

const t0 = getExternList(struct {
    pub const Extern = [_][]const u8{ "z", "hey", "hi", "yooo" };
})[0];

test {
    try std.testing.expectEqual(@as([]const u8, "hey"), t0);
}
```

**Comment by iacore** [comment]
This feels like Rust's `&T` and `&mut T`. `comptime T` can only appear in function variable (afaik), but it is acting as a separate type from `T`.

**Comment by EspeuteClement** [comment]
Another minimal reproduction that I found on `0.12.0-dev.1139+4d106076c` :

```zig
const std = @import("std");

comptime {
    const S = struct {
        T: type,
        id: usize,
    };

    var buffer: [4096]u8 = undefined;
    var fba = std.heap.FixedBufferAllocator.init(&buffer);
    var alloc = fba.allocator();

    comptime var map = std.StringHashMap(S).init(alloc);
    map.put("foo", .{ .type = u8, .id = 42});

    @compileLog(map.get("foo"));
}
```

gives :
```
 error: parameter of type 'test2.comptime_0__struct_286' must be declared comptime
        pub fn put(self: *Self, key: K, value: V) Allocator.Error!void {
                                        ^~~~~~~~
test2.zig:5:12: note: struct requires comptime because of this field
        T: type,
           ^~~~
test2.zig:5:12: note: types are not available at runtime
        T: type,
           ^~~~
test2.zig:4:15: note: struct declared here
    const S = struct {
              ^~~~~~
referenced by:
    comptime_0: test2.zig:14:8
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
lib\std\hash_map.zig:1600:34: error: parameter of type '*hash_map.HashMapUnmanaged([]const u8,test2.comptime_0__struct_286,hash_map.StringContext,80).Header' must be declared comptime
        fn dbHelper(self: *Self, hdr: *Header, entry: *Entry) void {
                                 ^~~~~~~~~~~~
lib\std\hash_map.zig:751:22: note: struct requires comptime because of this field
            values: [*]V,
                    ~^~~
test2.zig:5:12: note: struct requires comptime because of this field
        T: type,
           ^~~~
test2.zig:5:12: note: types are not available at runtime
        T: type,
```
