### ISSUE TITLE
Non-string literal inline assembly is treated as noreturn

### ISSUE THREAD

**Issue by N00byEdge** [ziglang/zig#10259]
### Zig Version

8c362431

### Steps to Reproduce

`break.zig`:
```zig
fn rd(comptime kind: []const u8) u64 {
    return asm volatile ("rd" ++ kind ++ " %[reg]"
        : [reg] "=r" (-> u64)
    );
}

export fn rdrand() u64 {
    return rd("rand");
}
export fn rdseed() u64 {
    return rd("seed");
}
```
`zig build-lib break.zig`

### Expected Behavior

Library is built

### Actual Behavior

```
break.zig:2:5: error: unreachable code
    return asm volatile ("rd" ++ kind ++ " %[reg]"
    ^
break.zig:2:12: note: control flow is diverted here
    return asm volatile ("rd" ++ kind ++ " %[reg]"
           ^
```

**Comment by N00byEdge** [comment]
I assume this broke in dd62a6d where inline assembly with non-string literals in stage1 was allowed, but treated as `@compileError()` in stage2. Looks like the `@compileError()`s `noreturn` semantics is leaking through the analysis, even though stage1 is running?

**Comment by N00byEdge** [comment]
Fixed in 1912ec03
