### ISSUE TITLE
returning anonymous union from switch statement causes seg fault

### ISSUE THREAD

**Issue by travisstaloch** [ziglang/zig#3685]
When the anonymous struct doesn't match the return type of the function, I get this crash.  The crash does not happen if the signature of bar() is corrected to properly match the anonymous struct being returned, ala `fn bar(Foo) Foo`.  

I think I have narrowed this down to the combination of using a switch statement within a function and returning an anon union which doesn't match the function return type.  Otherwise, the compiler seems to show a proper error message or run correctly.  

```zig
const Foo = union(enum) {
    a: isize,
};

pub fn bar(b: Foo) usize {
    return switch (b) {
        // crashes compiler
        // returning an anonymous struct within the switch seems to cause the issue
        .a => .{ .a = 2 },

        // A proper compiler error: expected type 'usize', found 'Foo'
        // is shown when using named (non-anonymous) struct.
        // .a => Foo{.a = 2},
    };
}

test "ret anonymous union from switch" {
    var g = bar(Foo{ .a = 1 });

    // This also shows a proper error message: expected type 'usize', found 'struct:19:16'
    // var f: usize = switch(Foo{.a = 1}) {
    //     .a => .{.a = 2},
    // };
}
```

```bash
$ zig test src/tmp2.zig
when analyzing /mnt/data/Users/Travis/Documents/Code/zig/jsonparser/src/tmp2.zig:8:16: assertion failed. This is a bug in the Zig compiler.
???:?:?: 0x562aa63366ac in ??? (???)
...
...
...
Segmentation fault
$ zig version
0.5.0+0237e7a70
$ uname -a
Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
```

**Comment by travisstaloch** [comment]
This was fixed recently. Not sure what commit but its working in 0.5.0+b55bc5eb2 and now produces an error message which describes the problem.  

Fixed as of b55bc5eb2

```console
$ zig test temp.zig
Semantic Analysis [752/1007] ./temp.zig:114:18: error: type 'usize' does not support struct initialization syntax
        .a => .{ .a = 2 },
                 ^
```

```zig

const Foo = union(enum) {
    a: isize,
};

pub fn bar(b: Foo) usize {
    return switch (b) {
        .a => .{ .a = 2 },
    };
}

test "ret anonymous union from switch" {
    var g = bar(Foo{ .a = 1 });
}
```
