### PR TITLE
`zig2 build test-std` progress

### LINKED ISSUE #11162: Aggregate initializers should allow initializing comptime fields, verifying equality
### Zig Version

0.10.0-dev.1246+5fbae9cd6

### Steps to Reproduce

cc @ifreund and @mitchellh , who provided these test cases

```zig
test {
    const T = @TypeOf(.{ @as(i32, 0), @as(u8, 123) });
    var a: T = .{-1234, 0};
    try testing.expectEqual(@as(i32, 0), a[0]);
    try testing.expectEqual(@as(u8, 123), a[1]);
}

test {
    const T = struct {
        comptime x: i32 = 0,
        comptime y: u8 = 123,
    };
    var a: T = .{.x = -1234, .y = 0};
    try testing.expectEqual(@as(i32, 0), a.x);
    try testing.expectEqual(@as(u8, 123), a.y);
}
```

### Expected Behavior

Test should fail - the provided field does not match the value of the comptime field.

Equality should be checked for the init value of comptime fields, in both structs and arrays.

### Actual Behavior

The test passes on stage1.

It fails on stage2 due to #11159, but once that bug is fixed it will incorrectly pass.

### LINKED ISSUE #11788: AstGen doesn't pass type to switch prong
```zig
test {
    var a: u32 = 0;
    var b: [2]u32 = undefined;
    b[0] = @as(u32, switch (a) {
        1 => 1,
        else => 0,
    });
}
```
```
a.zig:29:21: error: value with comptime only type 'comptime_int' depends on runtime control flow
    b[0] = @as(u32, switch (a) {
                    ^
a.zig:29:29: note: runtime control flow here
    b[0] = @as(u32, switch (a) {
                            ^
```
Related #11135

### PR DESCRIPTION
**Pull request by Vexu**
This gets us to three unique errors:
```
std/io/reader.zig:206:26: error: unreachable else prong; all cases already handled           (#11798)
std/net.zig:1340:12: error: unable to resolve inferred error set
std/crypto/aes/aesni.zig:182:20: error: TODO implement Sema for asm with more than 1 output
```

Closes  #11788
Closes #11162

### CODE REVIEW

**Comment by andrewrk** [comment]
> stage2: use correct type (u29) for alignment

Ah, on this one I wanted to change the spec to make alignment `u16`. I can make a corresponding (and breaking) stage1 change along with this.

That said, since you did it in a separate commit that is easily revertable we could also move forward with this and make the change later.

**Comment by Vexu** [comment]
> That said, since you did it in a separate commit that is easily revertable we could also move forward with this and make the change later.

Either way works for me, `std.heap.testAllocatorAlignedShrink` currently depends on the `u29` alignment.

**Comment by andrewrk** [comment]
Your call. If you have the PR green I certainly would not want to block the merge on the alignment type issue which we can do later.

**Comment by andrewrk** [comment]
Made 2 tiny fixups upon merging:
 * added an extra assertion to one of new behavior tests
 * fixed typo in commit message

Great work!
