### ISSUE TITLE
'min < value < max' is not rejected by the parser

### ISSUE THREAD

**Issue by tankorsmash** [ziglang/zig#10241]
### Zig Version

0.9.0-dev.1737+c42763f8c

### Steps to Reproduce

```
mkdir repro
cd repro
zig init-exe
```

edit `src/Main.zig` to:

```
const std = @import("std");

pub fn main() anyerror!void {
    std.log.info("All your codebase are belong to us.", .{});
}

pub fn between_1000(value: i32) bool {
    return 1 < value < 1000;
}

test "basic test" {
    // try std.testing.expect(1 < value < 1000); //doesnt compile
    try std.testing.expect(between_1000(100));
    try std.testing.expect(!between_1000(100000));

}

```

### Expected Behavior

Because it compiled, I expected `1 < 100 < 1000` to be true and `1 < 100000 < 100` to be false, but they're both true.

### Actual Behavior

`1 < 100 < 1000` is truthy and `1 < 100000 < 100` is truthy.

I was happy to see that zig supported the [Python style operator chaining](https://docs.python.org/3/reference/expressions.html#comparisons) but after exploring this a bit, it seems like it's a bug, since `try std.testing.expect(1 < value < 1000); ` on its own doesn't compile.

**Comment by tankorsmash** [comment]
https://github.com/ziglang/zig/issues/370 confirms this is a bug then, because it's not intended to compile at all

**Comment by MasterQ32** [comment]
> #370 confirms this is a bug then, because it's not intended to compile at all

This proposal indeed confirms that this is not intended to work, as the proposal was not accepted. You have to write `1 < value and value < 1000` to work.

**Comment by tankorsmash** [comment]
Yeah, it's strange it compiles at all.

**Comment by andrewrk** [comment]
Congrats for finding a bug in the parser. It's actually being parsed like this: `    (return 1 < value) < 1000;`

**Comment by andrewrk** [comment]
Regressed in 01aa74a93fa7c18f8a2f27a4c5f76333935c3502.

**Comment by andrewrk** [comment]
Mitigated by d3426ce634a09ec289480510040b3decfbd38c39:

```
$ ./zig test test.zig 
test.zig:8:22: error: unreachable code
    return 1 < value < 1000;
                     ^
test.zig:8:5: note: control flow is diverted here
    return 1 < value < 1000;
    ^
```

Keeping the issue open for the parser fix, but it's no longer a miscompilation.

**Comment by andrewrk** [comment]
Fixed in c98b020ce29467e80217718e0a1856b7fccd6b53.

**Comment by tankorsmash** [comment]
Thank you for the fix!
