### PR TITLE
sema: add OOB safety check for by-length slice of array

### LINKED ISSUE #18382: no bounds checking when slicing `s[start..][0..len]` arrays and array pointers in certain cases
### Zig Version

0.12.0-dev.1843+fd98fc1c5

### Steps to Reproduce and Observed Behavior

```zig
test {
    var buf: [5]u8 = undefined;
    const slice = &buf;
    var a: u32 = 6;
    _ = &a;
    _ = buf[a..][0..10];
    _ = slice[a..][0..10];
}
```
this test passes even though `[a..][0..10]` is far out of bounds of `slice`/`buf`. if we instead annotate `slice` as a slice rather than array pointer
```zig
test {
    var buf: [5]u8 = undefined;
    const slice: []u8 = &buf;
    var a: u32 = 6;
    _ = &a;
    _ = buf[a..][0..10];
    _ = slice[a..][0..10];
}
```
the test now fails
if the secondary slicing is runtime known the test also fails
```zig
test {
    var buf: [5]u8 = undefined;
    const slice = &buf;
    var a: u32 = 6;
    _ = &a;
    _ = buf[a..][0..a];
    _ = slice[a..][0..a];
}
```

### Expected Behavior

safety checks should be emitted for all cases, test fail

### PR DESCRIPTION
**Pull request by dweiller**
Fixes #18382.

This adds a out-of-bounds safety check for by-length slices of arrays with a comptime-known length but runtime known start/end.

Before merging:

  - [ ] determine what should be done about the compile error discussed below

#### Pre-existing compile error
The original fix via a compile error  (#18410) was reverted due to false positive cases. There is a pre-existing compile error that has false-positive cases that are analogous to the compile error introduced in #18410 (examples below), though these cases are less likely to be triggered.

The pre-existing compile error that has false positives is this one:
```zig
test {
    var buf: [5]u8 = undefined;
    _ = buf[1..10];
}
```
```
t.zig:3:16: error: end index 10 out of bounds for array of length 5
    _ = buf[1..10];
               ^~
```
However this still triggers when it is guarded against by a runtime-known condition:
```zig
test {
    var buf: [5]u8 = undefined;
    var runtime_condition = false;
    _ = &runtime_condition;
    if (runtime_condition) {
        _ = buf[1..10];
    }
}
```
```
t.zig:6:20: error: end index 10 out of bounds for array of length 5
    _ = buf[1..10];
               ^~
```

I think it is less likely for real code that would otherwise work correctly to trigger this false-positive, since the start and end of the slice must be comptime-known (rather than just the length as with the false positive in #18410) but there may be some generic pattern working with arrays of different sizes that would trigger it.

Should I remove this compile error as well, and if not should I make an issue about it or do we just wait to see if anyone encounters it in the wild and makes an issue?

### CODE REVIEW

**Comment by rohlem** [comment]
> [`Compile errors are better than runtime crashes.`](https://ziglang.org/documentation/master/#Zen)

hence I don't see any reason to remove the valid compile-time check.
As long as the branch may be run-time-reachable, the compiler is told to generate invalid code, so the error is justified.

If the branch is `comptime`-unreachable, the code should declare it as such
(the if-condition should be `comptime` -known false),
which stops the analysis and blocks the compile error.

**Comment by andrewrk** [comment]
Your example is not analogous at all. You may as well replace it with 

```zig
const std = @import("std");

test {
    var runtime_condition = false;
    _ = &runtime_condition;
    if (runtime_condition) {
        @compileError("unreachable");
    }
}
```

which also, correctly, reports a compile error.

**Comment by dweiller** [comment]
> Your example is not analogous at all. You may as well replace it with

The thing I think is analogous is that what was happening in #18410 with the json parser was runtime checks that would prevent slicing with a (comptime-known) length greater than the array length, but as the condition was only runtime known the new compile error was hit. With #18410, you could have replaced the json parser code with the same snippet, it's just less clear, since it was in a generic function.

I don't think it's really correct to say either the case of #18410 or above are false-postives but rather compile errors that may be generated by code that would be correct (at runtime) and looks like a reasonable way to guard a slicing operation, but gets caught out by something being runtime known. E.g. the json check could have been rewritten as:
```diff
 .partial_string_escaped_1 => |arr| {
-    if (i + arr.len > r.len) return error.LengthMismatch; // this is the original check, runtime known because `i` is runtime known, but in theory it could be known statically known that arr.len <= r.len after this
+    if (arr.len > r.len) return error.LengthMismatch; // comptime known condition, should prevent analysis of the following
+    if (i > r.len - arr.len) return error.LengthMismatch;
     @memcpy(r[i..][0..arr.len], arr[0..]);
     i += arr.len;
},
```

**Comment by rohlem** [comment]
If I correctly understand the scenario in question (I didn't before), it can be simplified as
`if ((x + 1) < 1) {@compileError("provably unreachable");}`
having its body analyzed even though it is provably unreachable for any unsigned `x`'s value.

The question is then just whether we want to require code to complicate such a condition
`(x + a) < b` into `(a < b) and ((x + a) < b)`, for `comptime`-known `a` and `b`,
to make it easier for the compiler to analyze,
or whether we want to make `comptime`-resolution of arithmetic smarter.

Note that ranged integers https://github.com/ziglang/zig/issues/3806 are one such way of making `comptime`-analysis smarter
which would solve this particular case.
(We wouldn't need the full ranged integers for this use case,
 just a partial compiler-internal implementation that tracks the lower bound of expressions.)

**Comment by dweiller** [comment]
That's how I see it. My opinion is that we should have both compile errors

> The question is then just whether we want to:
> 
>     * require code to complicate a condition
>       `(x + a) < b` into `(a < b) and ((x + a) < b)`, for `comptime`-known `a` and `b`,
>       to make it easier for the compiler to analyze it to `comptime`-known `false`
> 
>     * make `comptime`-resolution of arithmetic smarter
>       to figure this out without a code change

That's how I see it, with a third option being decide the current length check compile error is fine, and one like #18410 is not due to ergonomic reasons (though I would rather have the extra compile error).

**Comment by dweiller** [comment]
Here is an example of a generic function that triggers the index out of bounds compile error in a similar fashion to what happened in std.json in #18410

```zig
fn sliceTo6(comptime N: comptime_int, data: [N]u8, index: usize) ![]const u8 {
    if (index > 6 or 6 - index > data.len) return error.Invalid;
    return data[index..6];
}

test {
    const data = [4]u8{ 1, 2, 3, 4 };
    try std.testing.expectError(error.Invalid, sliceTo6(4, data, 1));
}

const std = @import("std");
```

**Comment by andrewrk** [comment]
#19374
