### ISSUE TITLE
stage1: Failing "recursive async function" behavior test

### ISSUE THREAD

**Issue by topolarity** [ziglang/zig#13359]
### Zig Version

0.10.0-dev.4714+169643406

### Steps to Reproduce and Observed Behavior

stage1 appears to have regressed on a behavior test in `./test/behavior/async_fn.zig`:

```zig
$ ./build/zig2 test test/behavior.zig -fstage1 -I test -I .
./test/behavior/async_fn.zig:1020:9: error: '@Frame(behavior.async_fn.recursiveAsyncFunctionTest(true).fib)' depends on itself
        fn fib(allocator: std.mem.Allocator, x: u32) error{OutOfMemory}!u32 {
        ^
```

### Expected Behavior

Test should pass.

**Comment by topolarity** [comment]
Regression introduced in 5b79f42dc5220850b67ac461a326d5a6253da215
