### ISSUE TITLE
Zig Compiler Issue: Allocator Error with u256 HashMap Keys

### ISSUE THREAD

**Issue by ch4r10t33r** [ziglang/zig#25972]
# Zig Compiler Issue: Allocator Error with u256 HashMap Keys

## Summary

Using native `u256` types as `std.HashMap` keys causes an allocator internal error in Zig 0.14.x (and potentially 0.15.x). The error occurs during HashMap initialization when the allocator tries to determine type information for `u256` keys.

## Error Message

```
error: access of union field 'pointer' while field 'int' is active
at std/mem/Allocator.zig:425:45
```

## Environment

- **Zig Version**: 0.14.1 (also observed in 0.14.0)
- **Platform**: macOS (ARM64 and x86_64), Linux (x86_64)
- **Standard Library**: Built-in (no external dependencies)

## Steps to Reproduce

1. Create a HashMap with `u256` as the key type
2. Use `std.HashMapAutoContext(u256)` or let Zig infer the context
3. Initialize the HashMap

### Minimal Reproduction Code

```zig
const std = @import("std");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    // This fails with allocator error
    var map = std.HashMap(u256, u32, std.HashMapAutoContext(u256), std.HashMapAutoContext(u256).hash);
    try map.init(allocator);
    defer map.deinit();
}
```

### Alternative Reproduction (Wrapper Struct)

```zig
const std = @import("std");

const U256Wrapper = struct {
    value: u256,
    
    pub fn hash(self: U256Wrapper) u64 {
        return @as(u64, @truncate(self.value));
    }
    
    pub fn eql(self: U256Wrapper, other: U256Wrapper) bool {
        return self.value == other.value;
    }
};

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    // This also fails with allocator error
    var map = std.HashMap(U256Wrapper, u32, std.HashMapAutoContext(U256Wrapper), std.HashMapAutoContext(U256Wrapper).hash);
    try map.init(allocator);
    defer map.deinit();
}
```

## Expected Behavior

HashMap should initialize successfully with `u256` keys, similar to how it works with smaller integer types (`u64`, `u128`, etc.).

## Actual Behavior

The compiler/runtime fails with an allocator internal error during HashMap initialization. The error occurs in `std/mem/Allocator.zig` at line 425, where the allocator tries to access union fields incorrectly.

## Workaround

Use a custom struct with two `u128` fields instead of native `u256`:

```zig
const std = @import("std");

pub const U256 = struct {
    low: u128,
    high: u128,

    pub fn fromU256(value: u256) U256 {
        return .{
            .low = @truncate(value),
            .high = @truncate(value >> 128),
        };
    }

    pub fn toU256(self: U256) u256 {
        return (@as(u256, self.high) << 128) | self.low;
    }

    pub fn eql(self: U256, other: U256) bool {
        return self.low == other.low and self.high == other.high;
    }

    pub fn hash(self: U256) u64 {
        return @as(u64, @truncate(self.low)) ^ 
               @as(u64, @truncate(self.low >> 64)) ^ 
               @as(u64, @truncate(self.high)) ^ 
               @as(u64, @truncate(self.high >> 64));
    }
};

// Custom hash context to bypass AutoContext
const HashContext = struct {
    pub fn hash(_: @This(), key: U256) u64 {
        return key.hash();
    }
    pub fn eql(_: @This(), a: U256, b: U256) bool {
        return a.eql(b);
    }
};

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    // This works with custom context
    var map = std.HashMap(U256, u32, HashContext, HashContext.hash);
    try map.init(allocator);
    defer map.deinit();
}
```

## Root Cause Analysis

The issue appears to be in the standard library's type introspection code within `std.HashMapAutoContext`. When dealing with `u256` (a 256-bit integer), the allocator's type introspection incorrectly accesses union fields, causing the "access of union field 'pointer' while field 'int' is active" error.

## Impact

This bug affects any code that needs to use `u256` as HashMap keys, which is common in:
- Blockchain/cryptocurrency applications (Ethereum addresses, transaction hashes)
- Cryptographic applications (large integer keys)
- Financial applications (precise decimal calculations)

## Related Issues

This may be related to how Zig handles large integer types in generic contexts, particularly in the standard library's HashMap implementation.

## Additional Notes

- The workaround (custom struct with two `u128` fields) works reliably and has no performance penalty
- The issue persists across different allocators (GeneralPurposeAllocator, ArenaAllocator, etc.)
- Using custom hash contexts bypasses the problematic AutoContext code path

**Comment by AdamGoertz** [comment]
The provided repro doesn't compile in 0.14.1. I'm guessing this is an AI generated issue.

```
example.zig:9:41: error: root source file struct 'std' has no member named 'HashMapAutoContext'
    var map = std.HashMap(u256, u32, std.HashMapAutoContext(u256), std.HashMapAutoContext(u256).hash);
                                     ~~~^~~~~~~~~~~~~~~~~~~
/cefs/38/389c688f98ba10ac7e68ed40_consolidated/compilers_zig_new_naming_0.14.1/lib/std/std.zig:1:1: note: struct declared here
pub const ArrayHashMap = array_hash_map.ArrayHashMap;
^~~
referenced by:
    posixCallMainAndExit: /cefs/38/389c688f98ba10ac7e68ed40_consolidated/compilers_zig_new_naming_0.14.1/lib/std/start.zig:660:37
    _start: /cefs/38/389c688f98ba10ac7e68ed40_consolidated/compilers_zig_new_naming_0.14.1/lib/std/start.zig:468:40
    3 reference(s) hidden; use '-freference-trace=5' to see all references
Compiler returned: 1
```
