### ISSUE TITLE
Assertion failed at stage1/analyze.cpp (get_error_union_type)

### ISSUE THREAD

**Issue by YohananDiamond** [ziglang/zig#8045]
I was trying to integrate Xlib with a Zig program of mine and the code snippet below ("Assertion failure example") caused a compiler assertion failure. I did specify the wrong return type (`error{A}!c.Display` instead of `error{A}!*c.Display`) but the assertion failure still shouldn't happen, I believe. What should happen is probably what the second code snippet ("Proper compile error example") output.

Command used to compile both examples:
```
zig build-exe main.zig --library c --library X11
```

## Assertion failure example

```zig
const c = @cImport({
    @cInclude("X11/Xlib.h");
});

pub fn openDisplay() error{A}!c.Display {
    return c.XOpenDisplay(0) orelse error.A;
}

pub fn main() void {
    _ = openDisplay();
}
```

Compiler output:
```
Assertion failed at /home/andy/dev/bootstrap-zig/zig/src/stage1/analyze.cpp:749 in get_error_union_type. This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
```

## Proper compile error example

```zig
const c = @cImport({
    @cInclude("X11/Xlib.h");
});

pub fn openDisplay() c.Display {
    return c.XOpenDisplay(0);
}

pub fn main() !void {
    _ = try openDisplay();
}
```

Compiler output:
```
./main.zig:5:23: error: Opaque return type '.cimport:1:11.struct__XDisplay' not allowed
pub fn openDisplay() c.Display {
                      ^
./main.zig:10:13: note: referenced here
    _ = try openDisplay();
            ^
```

---

Some additional information:
* `zig version`: 0.7.0
* OS: Arch Linux `5.10.16-arch1-1`

**Comment by g-w1** [comment]
On master I get this: 
```zig
zig/build on  master via ↯ v0.8.0-dev.1142+153cd4da0 via ❄  impure 
❯ cat test.zig
const c = @cImport({
    @cInclude("X11/Xlib.h");
});

pub fn openDisplay() error{A}!c.Display {
    return c.XOpenDisplay(0) orelse error.A;
}

pub fn main() void {
    _ = openDisplay();
}
zig/build on  master via ↯ v0.8.0-dev.1142+153cd4da0 via ❄  impure 
❯ ./zig build-exe test.zig -lc -lx11
./test.zig:10:20: error: error is discarded. consider using `try`, `catch`, or `if`
    _ = openDisplay();
                   ^
./test.zig:6:30: error: expected type '.cimport:1:11.struct__XDisplay', found '*.cimport:1:11.struct__XDisplay'
    return c.XOpenDisplay(0) orelse error.A;
                             ^
zig/build on  master via ↯ v0.8.0-dev.1142+153cd4da0 via ❄  impure took 2s 
❯ 
```

**Comment by Vexu** [comment]
Duplicate of #5227.

**Comment by YohananDiamond** [comment]
@g-w1 Oh, sorry, I accidentally overlooked your comment ^^'
Yeah, I'm using an older version... I'm still trying to get 0.8.0 working on my machine so I can't test it there yet, but it might somehow have been fixed already (even though https://github.com/ziglang/zig/issues/5227 is still open).
