### ISSUE TITLE
NetBSD build failure - more bitrot to sort out? 

### ISSUE THREAD

**Issue by ci4ic4** [ziglang/zig#19234]
### Zig Version

0.12.0-dev.3161+377ecc6af

### Steps to Reproduce and Observed Behavior

On a fresh 'git clone' the usual:

```
mkdir build 
cd build 
cmake -DCMAKE_BUILD_TYPE=Release -GNinja ..
ninja install
```

I get:
...
```
[15/20] Running zig1.wasm to produce /home/xci/src/zig/build/zig2.c
FAILED: zig2.c /home/xci/src/zig/build/zig2.c
cd /home/xci/src/zig && /home/xci/src/zig/build/zig1 /home/xci/src/zig/lib build-exe -ofmt=c -lc -OReleaseSmall --name zig2 -femit-bin="/home/xci/src/zig/build/zig2.c" -target x86_64-netbsd --dep build_options -
-dep aro --mod root src/main.zig --mod build_options /home/xci/src/zig/build/config.zig --mod aro lib/compiler/aro/aro.zig
/lib/std/os.zig:6036:25: error: ambiguous reference
/lib/std/c.zig:1514:16: note: declared here
/lib/std/c/netbsd.zig:40:5: note: declared here
/lib/std/os.zig:5936:25: error: ambiguous reference
/lib/std/c.zig:1505:16: note: declared here
/lib/std/c/netbsd.zig:25:5: note: declared here
ninja: build stopped: subcommand failed.
```

### Expected Behavior

Build to complete. My last successful build on this platform was `0.12.0-dev.3008+b2374c4d7` (on amd64) and `0.12.0-dev.3161+377ecc6af` (on aarch64).

**Comment by ci4ic4** [comment]
Getting worse...


```
[15/20] Running zig1.wasm to produce /home/xci/src/zig.bad/build/zig2.c
FAILED: zig2.c /home/xci/src/zig.bad/build/zig2.c
cd /home/xci/src/zig.bad && /home/xci/src/zig.bad/build/zig1 /home/xci/src/zig.bad/lib build-exe -ofmt=c -lc -OReleaseSmall --name zig2 -femit-bin="/home/xci/src/zig.ba
d/build/zig2.c" -target x86_64-netbsd --dep build_options --dep aro --mod root src/main.zig --mod build_options /home/xci/src/zig.bad/build/config.zig --mod aro lib/com
piler/aro/aro.zig
/lib/std/os.zig:6036:25: error: ambiguous reference
/lib/std/c.zig:1514:16: note: declared here
/lib/std/c/netbsd.zig:40:5: note: declared here
/lib/std/Thread/Futex.zig:858:34: error: no field named 'Monotonic' in enum 'builtin.AtomicOrder'
/lib/std/builtin.zig:83:25: note: enum declared here
/lib/std/os.zig:5936:25: error: ambiguous reference
/lib/std/c.zig:1505:16: note: declared here
/lib/std/c/netbsd.zig:25:5: note: declared here
/lib/std/Thread/Futex.zig:804:35: error: no field named 'Monotonic' in enum 'builtin.AtomicOrder'
/lib/std/builtin.zig:83:25: note: enum declared here
ninja: build stopped: subcommand failed.

```

On today's attempt.

**Comment by ci4ic4** [comment]
All good now:

```
❯ ./stage3/bin/zig version
0.12.0-dev.3333+ce4245f87

░▒▓   …/zig.bad/build   master $   00:28 
❯ uname -a
NetBSD ymir.lorien.lan 10.99.10 NetBSD 10.99.10 (GENERIC) #31: Tue Mar 12 03:22:42 GMT 2024  sysbuild@ymir.lorien.lan:/dumps/sysbuild/amd64/obj/home/sysbuild/src/sys/arch/amd64/
compile/GENERIC amd64
```
