### ISSUE TITLE
regression 0.10.0-dev.3659+e5e6eb983 vs. 0.10.0-dev.3431+4a4f3c50c

### ISSUE THREAD

**Issue by mz0** [ziglang/zig#12555]
### Zig Version

0.10.0-dev.3659+e5e6eb983

### Steps to Reproduce

this fragment from `ziglings/exercises/063_labels.zig`
```
if (!for (wanted_ingredients) |want_it| {
    if (required_ingredient == want_it) break true;
} else false) continue :food_loop;
```
compiles fine with 0.10.0-dev.3431+4a4f3c50c and with a number of previous builds
but not in 0.10.0-dev.3659+e5e6eb983
The full file is https://github.com/mz0/ziglings/blob/done/exercises/063_labels.zig

### Expected Behavior

no errors

### Actual Behavior

```
Compiling 063_labels.zig...
/home/mz0/z/ziglings/exercises/063_labels.zig:118:53: error: expected type 'bool', found 'void'
            if (!for (wanted_ingredients) |want_it| {
                                                    ^
```

**Comment by Vexu** [comment]
Related #12551, #11816
