### PR TITLE
translate-c: fix function pointer casting + alignCast and constCast at the same time

### LINKED ISSUE #24513: translate-c: cast function pointer to void pointer
### Zig Version

0.14.1

### Steps to Reproduce and Observed Behavior

C code that casts a function pointer to a non const data pointer (`void*` for example) translates incorrectly.

This issue is specific to function pointers as casting `const T*` to `T*` correctly translates to `@as(?*anyopaque, @ptrCast(@volatileCast(@constCast(ptr))))`.

I know that [casting function pointers to data pointers can be undefined behavior](https://stackoverflow.com/questions/13696918/c-cast-void-pointer-to-function-pointer#13697654) but a lot of compilers (clang) allow it.

When trying to translate c code (which compiles fine with clang version 20.1.8):
```c
int fn(int a) {
  return 2*a;
}
void main() {
  int (*f)(int) = fn;
  void *g = (void*)f;
  int (*h)(int) = (int (*)(int))g;

  h(3);
}
```

`zig translate-c test.c` outputs:
```zig
// ...
pub export fn @"fn"(arg_a: c_int) c_int {
    var a = arg_a;
    _ = &a;
    return @as(c_int, 2) * a;
}
pub export fn main() void {
    var f: ?*const fn (c_int) callconv(.c) c_int = &@"fn";
    _ = &f;
    var g: ?*anyopaque = @as(?*anyopaque, @ptrCast(f));
    _ = &g;
    var h: ?*const fn (c_int) callconv(.c) c_int = @as(?*const fn (c_int) callconv(.c) c_int, @ptrCast(@alignCast(g)));
    _ = &h;
    _ = h.?(@as(c_int, 3));
}
// ...
```

And compiling that outputs error:
```
test.zig:65:43: error: @ptrCast discards const qualifier
    var g: ?*anyopaque = @as(?*anyopaque, @ptrCast(f));
                                          ^~~~~~~~~~~
```

### Expected Behavior

It should probably use `@constCast`

### PR DESCRIPTION
**Pull request by paokitore**
This fixes #24513 and another issue I noticed: casting `const void*` to `int*` did not work.

Both of those issues are fixed with [translate-c](https://github.com/ziglang/translate-c), so this PR might be useless though.

examples:
```c
void *g = (void*)f;
```
used to translate to:
```zig
var g: ?*anyopaque = @as(?*anyopaque, @ptrCast(f));
```
forgetting a `@constCast`.

and
```c
const void *c;
int *d = (int*)c;
}
```
the second line used to translate to:
```zig
var d: [*c]c_int = @as([*c]c_int, @ptrCast(@volatileCast(@constCast(c))));
```
forgetting a `@alignCast`.

### CODE REVIEW

**Comment by alexrp** [comment]
This would effectively be made obsolete by ziglang/zig#24497, so I think we'd only consider taking this PR if ziglang/zig#24497 for some reason fails to land in 0.15.0.

**Comment by paokitore** [comment]
The previous CI failed with 3 errors and the next one will still fail with 2 errors:

1. Formatting: I forgot and the last commit fixed it.

For the other two, I'd say that it's more of the tests' fault.

2.
expected:
```zig
var func_ptr: ?*anyopaque = @as(?*anyopaque, @ptrCast(&foo));
```
got:
```zig
var func_ptr: ?*anyopaque = @as(?*anyopaque, @ptrCast(@volatileCast(@constCast(&foo))));
```
This fail is quite weird because the code expected by the test actually does not compile :
```
test1.zig:3:50: error: @ptrCast discards const qualifier
    var func_ptr: ?*anyopaque = @as(?*anyopaque, @ptrCast(&foo));
                                                 ^~~~~~~~~~~~~~
test1.zig:3:50: note: use @constCast to discard const qualifier
```
So I would say that this is an issue with the test.

3.
expected:
```zig
@as([*c]c_int, @ptrCast(@volatileCast(@constCast(a))))
```
got:
```zig
@as([*c]c_int, @ptrCast(@volatileCast(@constCast(@alignCast(a)))))
```
I just have an extra `@alignCast` which still outputs valid zig code.
I don't think this in an issue, because there are many cases where an extra `@alignCast` is outputted:
```c
typedef struct {
  int a;
} A;
void main() {
  int a = 3;
  int *a_ptr = &a;
  A *aa_ptr = (A*)a_ptr;
}
```
gets translated to
```zig
pub const A = extern struct {
    a: c_int = @import("std").mem.zeroes(c_int),
};
pub export fn main() void {
    var a: c_int = 3;
    _ = &a;
    var a_ptr: [*c]c_int = &a;
    _ = &a_ptr;
    var aa_ptr: [*c]A = @as([*c]A, @ptrCast(@alignCast(a_ptr)));
    _ = &aa_ptr;
}
```
even though `c_int` and `A` have the same alignment.

**Comment by alexrp** [comment]
Closing since we've switched to Aro-based translate-c as of #24497. Contributions to translate-c should now be opened on https://github.com/ziglang/translate-c.
