### ISSUE TITLE
extern structs cannot contain function pointers

### ISSUE THREAD

**Issue by cajwebster** [ziglang/zig#17827]
### Zig Version

0.12.0-dev.1372+8457439a8

### Steps to Reproduce and Observed Behavior

```zig
pub fn main() void {
    const Foo = extern struct {
        fun: *const fn () void,
    };
    @import("std").debug.print("{}\n", .{@typeInfo(Foo)});
}
```
```
$ zig run test.zig
test.zig:3:14: error: extern structs cannot contain fields of type '*const fn () void'
        fun: *const fn () void,
             ^~~~~~~~~~~~~~~~~
test.zig:3:14: note: type has no guaranteed in-memory representation
test.zig:3:14: note: use '*const ' to make a function pointer type
referenced by:
    main: test.zig:2:24
    callMain: /usr/lib/zig/lib/std/start.zig:573:17
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

### Expected Behavior

Code should compile successfully.

**Comment by Vexu** [comment]
You need to specify `callconv(.C)`.

**Comment by matteo-briani** [comment]
I am a bit confused, maybe I am missing something trivial.

### A similar example
The example of cajwebster does not compile in zig 0.10 or 0.11, so I tweaked it a bit to remove the `@typeInfo`.
I am left with this:
```zig
const std = @import("std");

pub const MyStruct = extern struct { fun: *const fn () void };
fn my_fun() void {}

pub fn main() void {
    const my_struct = MyStruct{
        .fun = &my_fun,
    };
    std.debug.print("{?}.\n", .{my_struct});
}
```
which compiles correctly using zig `0.10.0` and `0.11.0`, but fails with zig `0.12.0-dev.1396+f6de3ec96` with the error message:

```
mymain.zig:3:43: error: extern structs cannot contain fields of type '*const fn () void'
pub const MyStruct = extern struct { fun: *const fn () void };
                                          ^~~~~~~~~~~~~~~~~
mymain.zig:3:43: note: type has no guaranteed in-memory representation
mymain.zig:3:43: note: use '*const ' to make a function pointer type
referenced by:
    MyStruct: mymain.zig:3:29
    main: mymain.zig:7:23
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```
Specifying the `callconv(.C)` fixes the compilation issue.

### Question
Is this a regression of the zig compiler or a silent issue in the previous versions of zig?

**Comment by Vexu** [comment]
It's a silent issue in the previous versions of Zig.
