### ISSUE TITLE
cimport.zig: use of undeclared identifier

### ISSUE THREAD

**Issue by enedil** [ziglang/zig#9774]
I have such zig source file (build file is the stock one, and just adds include path and links C library).

```zig
// h.h contents:
//
// struct Struct_;
// typedef struct Struct_ *Struct;
// struct Struct_ {
//     int dummy;
// };
// Struct make_struct();

const h = @cImport({
    @cInclude("h.h");
});

pub fn f() @TypeOf(h.make_struct()) {
    return h.make_struct();
}

pub fn main() anyerror!void {
    _ = f();
}
```

This results in such an error:
```zig
./zig-cache/o/a66397ff35b1004440bd73e839193707/cimport.zig:6:32: error: use of undeclared identifier 'Struct'
pub extern fn make_struct(...) Struct;
                               ^
./zig-cache/o/a66397ff35b1004440bd73e839193707/cimport.zig:6:32: note: called from here
pub extern fn make_struct(...) Struct;
                               ^
./src/main.zig:5:12: note: called from here
pub fn f() @TypeOf(h.make_struct().*.a) {
           ^
./src/main.zig:5:33: note: referenced here
pub fn f() @TypeOf(h.make_struct().*.a) {
                                ^
./src/main.zig:10:9: note: referenced here
    _ = f();
        ^
```

This issue doesn't appear if not using `h.make_struct()` inside `@TypeOf`.

OS: Fedora 34
Zig version: 0.8.0, as shipped with Fedora.

**Comment by Vexu** [comment]
The issue is not related to `translate-c` and can be reproduced with just plain imports:
```zig
// a.zig
const h = @import("b.zig");
comptime { @TypeOf(h.make_x()); }
// b.zig
pub const X = c_int;
pub extern fn make_x() X;
```

**Comment by Ultra-Code** [comment]
I am having a similar issue with using glfw with zig cImport. ```error: use of undeclared identifier 'GLFWwindow'```. It compiles on zig 0.8.1 but not on 0.9.0-dev.1903+2af94e76a

**Comment by alexrp** [comment]
https://codeberg.org/ziglang/zig/pulls/31892
