### ISSUE TITLE
Incorrect handling of .INVAL in std.posix and the new Threaded API.

### ISSUE THREAD

**Issue by mrdimidium** [ziglang/zig#25951]
### Zig Version

0.16.0-dev.1316+181b25ce4

### Steps to Reproduce and Observed Behavior

The current master has two related issues with handling `.INVAL` when calling the `accept` method.

First of all, `.INVAL` is the return value when calling `posix.shutdown`. This is necessary if you want to gracefully shutdown and first explicitly close the socket to accept new connections.

Note that `shutdown` is not a substitute for `close` — `close` will only close the socket, but will not stop accepting with `.INVAL`.

In 0.15, `posix.accept` is implemented correctly; when `.INVAL` is returned, it returns `posix.AcceptError.SocketNotListening`.

In 0.16, the behavior has diverged:
- the new `std.Io.net.AcceptError` does not include `SocketNotListening`;
- `std.posix` still attempts to [return `SocketNotListening`](https://github.com/ziglang/zig/blob/master/lib/std/posix.zig#L3546), which results in a compilation error;
- `Io.Threaded` considers this a programming error and [crashes in debug mode](https://github.com/ziglang/zig/blob/master/lib/std/Io/Threaded.zig#L3824).

In practice, this means that a server based on `Io.Threaded` cannot implement graceful shutdown (simply calling `Io.net.Server` won't work; it's `posix.close` internally), and accept will remain blocked.

A short sample that works in 0.15 but is broken in 0.16:
```zig
const std = @import("std");
const posix = std.posix;

const response_template =
    "HTTP/1.1 200 OK\r\n" ++
    "Content-Type: text/plain\r\n" ++
    "Content-Length: {d}\r\n" ++
    "Connection: close\r\n" ++
    "\r\n{s}";

pub fn main() !void {
    const server_fd = try posix.socket(posix.AF.INET, posix.SOCK.STREAM, 0);
    defer posix.close(server_fd);

    const port = std.mem.bigToNative(u16, 9001);
    var addr = posix.sockaddr.in{ .family = posix.AF.INET, .addr = 0, .port = port };
    var addr_len: posix.socklen_t = @sizeOf(posix.sockaddr.in);

    try posix.bind(server_fd, @ptrCast(@alignCast(&addr)), addr_len);
    try posix.listen(server_fd, 10);

    while (true) {
        const client_fd = posix.accept(server_fd, @ptrCast(@alignCast(&addr)), &addr_len, 0) catch |err| {
            switch (err) {
                // There's nothing you can do here, it just won't compile
                error.SocketNotListening => break,
                else => return err,
            }
        };
        defer posix.close(@intCast(client_fd));

        var req_buf: [1024]u8 = undefined;
        const read_bytes = try posix.read(@intCast(client_fd), &req_buf);

        var res_buf: [2048]u8 = undefined;
        const response = try std.fmt.bufPrintZ(&res_buf, response_template, .{ read_bytes, req_buf });

        const sent_bytes = try posix.write(@intCast(client_fd), response);
        if (sent_bytes < 0) {
            std.log.err("coudn't write all message", .{});
        }
    }
}
```

### Expected Behavior

You need to return `SocketNotListening` in `AcceptError` and return it from both accept implementations.

You might also consider replacing `close` with `shutdown` in `deinit` so that the deinit call terminates the server. However, this can be done manually via `Stream.handle`.

P.S. I would be happy to send my first PR to fix this :)

**Comment by squeek502** [comment]
https://codeberg.org/ziglang/zig/pulls/30042
