### ISSUE TITLE
"integer part of floating point value out of bounds" panic during f16 -> i32 conversion on macOS

### ISSUE THREAD

**Issue by linusg** [ziglang/zig#22247]
### Zig Version

0.14.0-dev.2474+ee47094a3

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() void {
    var f: f16 = 32785;
    _ = &f;
    const i: i32 = @intFromFloat(f);
    std.debug.print("{}\n", .{i});
}
```

```console
$ zig run test.zig
thread 23687446 panic: integer part of floating point value out of bounds
/Users/linus/Dev/kiesel/test.zig:6:20: 0x1047e0f7b in main (a)
    const i: i32 = @intFromFloat(f);
                   ^
/Users/linus/zig/0.14.0-dev.2474+ee47094a3/files/lib/std/start.zig:647:22: 0x1047e0983 in main (a)
            root.main();
                     ^
```

### Expected Behavior

Works fine on Linux:

```console
$ zig run test.zig
32800
```

Also works fine up to 32784 which rounds to 32768 (see https://float.exposed/32784).

**Comment by alexrp** [comment]
x86_64 or aarch64?

**Comment by linusg** [comment]
M4 Pro, macOS 15.1

**Comment by linusg** [comment]
I can only reproduce this for `-O Debug`, all of the release build modes work as intended.

**Comment by john-h-k** [comment]
This is a clang/LLVM regression it seems, although I have not tracked down exactly the case. After getting the LLVM bitcode for the above program, running it via:

```
❯ clang --version
Apple clang version 16.0.0 (clang-1600.0.26.6)
Target: arm64-apple-darwin24.3.0
```

succeeds, whereas zig's reported clang version

```
❯ zig cc --version
Homebrew clang version 18.1.8
Target: arm64-apple-darwin24.3.0
```

causes the incorrect OOB

**Comment by linusg** [comment]
The reproducer now fails to build after https://github.com/ziglang/zig/pull/24632:

```
test.zig:4:18: error: type 'f16' cannot represent integer value '32785'
    var f: f16 = 32785;
                 ^~~~~
referenced by:
    callMain [inlined]: .local/share/zigup/0.15.1/files/lib/std/start.zig:618:22
    callMainWithArgs [inlined]: .local/share/zigup/0.15.1/files/lib/std/start.zig:587:20
    main: .local/share/zigup/0.15.1/files/lib/std/start.zig:602:28
    1 reference(s) hidden; use '-freference-trace=4' to see all references
```

Changing the line to either `var f: f16 = @floatFromInt(32785);` or `var f: f16 = 32785.0;` makes it yield the correct result. I also cannot reproduce anymore with the original JS snippet that caused the crash in Kiesel (https://codeberg.org/kiesel-js/kiesel/issues/69).

I'm not sure if the fix ultimately was on Zig's side or in LLVM 20 but let's close this 🙂
