### ISSUE TITLE
Support for OSX below 10.13 High Sierra versions

### ISSUE THREAD

**Issue by godDLL** [ziglang/zig#6989]
I have this undefined symbol in `std.os.futimens` in `zig1.o` crapping out when building stage1.
Is OSX 10.12.6 (16G2136) with llvm 11.0.0 supported for this at all?

```
#~∘ cd (brew --prefix llvm)/bin
#/u/l/o/l/bin∘ ./clang --version
clang version 11.0.0
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin/.
```
```
Configuring zig version 0.6.0+17837affd
...
Scanning dependencies of target zig_build_zig1
[ 99%] Building self-hosted component /Users/yuli/Downloads/zig/build/zig1.o
[ 99%] Built target zig_build_zig1
Scanning dependencies of target zig
[ 99%] Building CXX object CMakeFiles/zig.dir/src/stage1/empty.cpp.o
[100%] Linking CXX executable zig
Undefined symbols for architecture x86_64:
  "_futimens", referenced from:
      _std.os.futimens in zig1.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [zig] Error 1
make[1]: *** [CMakeFiles/zig.dir/all] Error 2
make: *** [all] Error 2
#~/D/z/build·master∘ 
```
The reason I'm compiling from source is that I tried the packaged binary, but it crapped out with `SIGTERM`.

**Comment by jedisct1** [comment]
I don't think Zig is being tested on macOS Sierra. That OS version reached end of life more than a year ago (even for security updates), and none of the CI systems we use still offer it either.

You can try to replace the function call with an `unreachable` statement to get Zig to compile, but upgrading would probably not be a bad idea. Even High Sierra is going to be EOL's very soon.

**Comment by godDLL** [comment]
It has been pointed out to me that [Sierra is not supported](https://ziglang.org/#Support-Table), which is a shame.
With Apple operating systems this is the last release that I find usable, with my collection of software there is no point to upgrade – literally nothing works on 10.13 and above (for me).
Besides that I have a perfectly usable second machine here that does not go beyond 10.8 Mountain Lion by design.

I suspect I'm not the only one preferring the earlier versions even on hardware that support later versions.
As such, I'd like to assist in expanding the lower bracket of supported OSX versions for Zig, if that is acceptable to @andrewrk

**Comment by andrewrk** [comment]
You're welcome to submit patches to improve support if they aren't too intrusive, however, the project officially won't offer support for these older versions, which means I won't keep the issue open.

I'm open to changing this policy in the future, but at this stage of the project, this is one area I want to keep the scope manageable, so we don't spread our limited efforts too thin. Currently we match the LTS schedule of Apple.

**Comment by godDLL** [comment]
My findings:

1. I am insufficiently versed in the Apple frameworks to work this out.
2. This seems to be about the of UNIX time, or the preferred way of getting it by Zig.
3. There are seemingly no other references to this functionality elsewhere, so this is the one place to apply a patch.
4. There is other time-formatting functionality in that Apple header, maybe some of it is used by Zig. 
5. All of the time-formatting there is trivial, so this could be dropped as a dependency.
6. There are additional Apple headers that expect this kind of time formatting that Zig depends on.
7. I give up. Zig is moving too fast for me to keep up, with my level of understanding of OSX C system land.

**Comment by iology** [comment]
@godDLL you could try (I haven't) the [Macports recipe](https://trac.macports.org/search?q=zig) which depends on https://github.com/macports/macports-legacy-support

```sh
$ port info zig
zig @0.8.0 (lang)
Variants:             debug, universal

Description:          Zig is a general-purpose programming language designed for robustness,
                      optimality, and maintainability.
Homepage:             https://ziglang.org/

Build Dependencies:   cmake, clang-12, legacy-support
Library Dependencies: llvm-12
Platforms:            darwin
License:              MIT
Maintainers:          [redacted]
```
