### ISSUE TITLE
error: container 'std.macho' has no member called 'EXPORT_SYMBOL_FLAGS_KIND_REGULAR'

### ISSUE THREAD

**Issue by ehaas** [ziglang/zig#7392]
Ran into this building Zig on Windows using the compiler dev kit tarball, on a system that *does* have MSVC installed (not sure if that matters)

According to `git bisect` the problem was introduced in commit a579f8ae8d6009d95ef22879bc725a233f838d6f

Zig repo commit is `f7d600675c548b4e45b24f8e10ebdd892a6b8dba`

dev kit: zig+llvm+lld+clang-x86_64-windows-gnu-0.7.0+1afea36a1

```
 C:\Users\Evan\Downloads\zig+llvm+lld+clang-x86_64-windows-gnu-0.7.0+1afea36a1\bin\zig.exe build -Dstage1 -Dtarget=native-native-gnu --search-prefix C:\Users\Evan\Downloads\zig+llvm+lld+clang-x86_64-windows-gnu-0.7.0+1afea36a1
.\src\link\MachO.zig:1819:34: error: container 'std.macho' has no member called 'EXPORT_SYMBOL_FLAGS_KIND_REGULAR'
            .export_flags = macho.EXPORT_SYMBOL_FLAGS_KIND_REGULAR,
                                 ^
.\src\link\MachO.zig:315:13: note: referenced here
            try self.writeExportTrie();
            ^
.\src\link.zig:479:13: note: referenced here
            try base.flushModule(comp);
            ^
.\src\Compilation.zig:1249:5: note: referenced here
    try self.bin_file.flush(self);
    ^
.\src\main.zig:1927:5: note: referenced here
    try comp.update();
    ^
.\src\main.zig:1789:49: note: referenced here
    updateModule(gpa, comp, zir_out_path, hook) catch |err| switch (err) {
                                                ^
```

**Comment by andrewrk** [comment]
ok so the unsolved problem with the dev kit is that every time we update the compiler in certain ways, you have to refresh the dev kit in order to keep it working. I have some ideas on how to improve this, but for now the solution is that I need to upload a new dev kit .zip file.

**Comment by andrewrk** [comment]
FYI the dev kit link is updated: https://github.com/ziglang/zig/wiki/Building-Zig-on-Windows

It solves this particular problem, but I'm going to keep the issue open to track the fact that we don't have a way to update the dev kit using the dev kit.

**Comment by ehaas** [comment]
One workaround for now is to additionally pass `--override-lib-dir path\to\zig checkout\lib` (e.g. `--override-lib-dir C:\Users\Evan\projects\zig\lib`)  when using the compiler kit. This will work if trying to compile Zig when it uses new standard library features. It may not help if the compiler or build tools change in other ways though.

I confirmed that this workaround allows compiler kit `8076894d8` to build latest master 6ab5bebed1d0808ad8153097332519088d5af95a (without the additional flag it breaks due to missing `std.fs.path.extension`

**Comment by andrewrk** [comment]
I updated the wiki instructions to suggest the `--override-lib-dir` tip.
