### PR TITLE
Sema: give src loc to `requireRuntimeBlock`

### LINKED ISSUE #24273: [Regression] Compiler segfault when comptime expresion contains runtime value
### Zig Version

0.14.0 and 0.15.0-dev.769+4d7980645

### Steps to Reproduce and Observed Behavior

```zig
fn foo(comptime _: []const u8) void {}
fn baz() u8 { return 123; }

const global = baz();

pub fn main() !void {
    // these work
    foo(&.{0});
    foo(&.{baz()});
    foo(&.{global});
    const x = comptime baz();
    foo(&.{x});

    // const y = baz();
    // foo(&.{y});
}
```

Compiler segfaults if the last 2 lines are present, works fine as is

### Expected Behavior

0.13.0 correctly reports the problem
```zig
repro.zig:15:11: error: unable to evaluate comptime expression
    foo(&.{y});
         ~^~~
repro.zig:15:12: note: operation is runtime due to this operand
    foo(&.{y});
           ^
```

### PR DESCRIPTION
**Pull request by JackoCoolio**
Fixes #24273.

It looks like the regression was caused by 1eaeb4a0, which removed the handling for `error.NeededSourceLocation`.

### CODE REVIEW

**Comment by mlugg** [comment]
Pushed a new version which just removes those incorrect calls. I've kept the test cases you wrote. Thanks!
